### ISSUE TITLE
Problems with email configuration SMTP

### ISSUE THREAD

**Issue by cesarca** [sentry-kubernetes/charts#1024]
Hello, following the recommendation of several forums and reading the official documentation, I cannot configure SMTP email.

My helm values are as follows:
```
mail:
      backend: smtp
      useTls: true
      useSsl: false
      username: "*****"
      existingSecret: *****
      existingSecretKey: *****
      port: 587
      host: "email-smtp.us-east-1.amazonaws.com"
      from: "test@email.com"
```

These are the values from the portal:
<img width="393" alt="Captura de pantalla 2023-09-22 a las 9 14 55" src="https://github.com/sentry-kubernetes/charts/assets/7240843/b5e13586-e9d8-40e0-ac35-b6e3c2030788">

When I test the connection, I see this error in the portal:
<img width="360" alt="Captura de pantalla 2023-09-22 a las 9 13 12" src="https://github.com/sentry-kubernetes/charts/assets/7240843/7d7b519d-74d7-4021-8063-f32f5087f58a">

and in the logs:
`sentry-web-576d9d4f6d-nczdk:sentry-web 07:21:49 [ERROR] django.request: Internal Server Error: /api/0/internal/mail/ (status_code=500 request=<WSGIRequest: POST '/api/0/internal/mail/'>)`

any ideas? Thanks

**Comment by pierangelomiceli** [comment]
Hi, in my case worked with a slighty different configuration like this:

```yaml
mail:
  backend: smtp
  from: "avalidatedifyouareinsandbox@email.com"
  host: "email-smtp.eu-north-1.amazonaws.com"
  password: "FGTQnsdfYSkCia00mASh687saP9TwHCF6aXBf52Al9"
  port: 25
  useSsl: false
  useTls: true
  username: "YOURAWSUSRENAME
```

Note that:
- In my case the email was a valid for aws email in sandbox environment
- I set 25 for port and it worked

Hope it helps!
