### ISSUE TITLE
Sentry external Kafka with enabled TLS

### ISSUE THREAD

**Issue by cloud-digitaltag** [sentry-kubernetes/charts#1031]
Hi.
I deployed Sentry with external  Redis and Kafka. 
For Redis everything works fine, but for Kafka I have some issue.
I have enabled TLS on Kafka server and I can't change it to plaintext.
I add to my values file following lines with variable:
```
snuba:
  dbInitJob:
    env:
    - name: KAFKA_SECURITY_PROTOCOL
      value: SSL
```
I added this also for every snuba deploy in values files in env sections and all snuba pods connect to external Kafka.
I did the same for sentry deployed pods, but this time this variable not works :(.
I also tried add manually to relay configmap template : 
configmap-relay.yaml additionall default entry:
```
      kafka_config:
        - name: "bootstrap.servers"
          value: {{ (include "sentry.kafka.bootstrap_servers_string" .) | quote }}
        - name: "security.protocol"
          value: "SSL"
        - name: "message.max.bytes"
          value: 50000000  # 50MB or bust
```
and for sentry configmap template:
configmap-sentry.yaml additional entry:
```
    DEFAULT_KAFKA_OPTIONS = {
        "bootstrap.servers": {{ (include "sentry.kafka.bootstrap_servers_string" .) | quote }},
        "security.protocol": "SSL",
        "message.max.bytes": 50000000,
        "socket.timeout.ms": 1000,
```
With this changes, I see on k8s in configmap new values, but pods uses this new cm still can't connect to Kafka because is set wrong protocol. Relay pod going to CrashLoopBackOff status without any logs that will say what's happen.

Could someone have the same issue and resolved it ?
