### ISSUE TITLE
sentry-worker issues

### ISSUE THREAD

**Issue by slarktits** [sentry-kubernetes/charts#1064]
Hello everyone.
I can't completely to deploy sentry on my k8s cluster.

sentry worker produce next error.

`django.db.utils.ProgrammingError: UndefinedTable('relation "sentry_option" does not exist\nLINE 1: ..."."last_updated_by", "sentry_option"."value" FROM "sentry_op...\n                                                             ^\n')
SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s
17:52:31 [ERROR] celery.app.trace: Task sentry.tasks.options.sync_options[50657e30-d20b-4b5f-b59d-feebe9a91034] raised unexpected: ProgrammingError('UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ..."."last_updated_by", "sentry_option"."value" FROM "sentry_op...\\n `

I tried to use postg DB included into deployment, also tried ti use external from AWS RDS.
My config.
```
`  values:
    ingress:
      enabled: true
      hostname: sentry.******
      regexPathStyle: aws-alb
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
        alb.ingress.kubernetes.io/subnets: *******
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/certificate-arn: "***********"
        external-dns.alpha.kubernetes.io/hostname: "sentry.*********"
    user:
      create: true
      email: examplemail
      password: **********
    postgresql:
      enabled: false
    externalPostgresql:
      host: sentry.***********.us-east-1.rds.amazonaws.com
      port: 5432
      username: user
      password: ********
      database: sentry
      connMaxAge: 0
    nginx:
      enabled: false
    rabbitmq:
      enabled: false
    sentry:
      web:
        service:
          annotations:
            alb.ingress.kubernetes.io/healthcheck-path: /_health/
            alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    relay:
      service:
        annotations:
          alb.ingress.kubernetes.io/healthcheck-path: /api/relay/healthcheck/ready/
          alb.ingress.kubernetes.io/healthcheck-port: traffic-port`
          ```
