### ISSUE TITLE
can you support external rabbitmq for high throughput transactions?

### ISSUE THREAD

**Issue by goodosoft** [sentry-kubernetes/charts#1079]
high throughput transactions broken buildin rabbitmq deployment.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by goooseman** [comment]
<img width="915" alt="Screenshot 2024-04-04 at 23 22 54" src="https://github.com/sentry-kubernetes/charts/assets/3503252/cde737c1-add5-45f4-ad96-e7fec44c4b5c">

Actually as far as I see you can just make 

```
rabbitmq:
  enabled: false
```

But to provide a custom `BROKER_URL` env var.

I do provide additional env vars by using yaml variables:


```
env: &sentryEnv # CHANGED
- name: S3_USER_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: sentry-s3-user
      key: accessKey
- name: S3_USER_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: sentry-s3-user
      key: secretKey
- name: OIDC_CLIENT_ID
  valueFrom:
    secretKeyRef:
      name: openid-sso
      key: clientId
- name: OIDC_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: openid-sso
      key: clientSecret
- name: SENTRY_EVENT_RETENTION_DAYS
  value: "30"
- name: BROKER_URL
  value: "amqp://guest:guest@aws-address:5672//"


sentry:
  # to not generate a sentry-secret, use these 2 values to reference an existing secret
  # existingSecret: "my-secret"
  # existingSecretKey: "my-secret-key"
  singleOrganization: true
  web:
    env: *sentryEnv
```
