### ISSUE TITLE
Ingress regex path style - XHR Requests and Error Logging

### ISSUE THREAD

**Issue by honghainguyen777** [sentry-kubernetes/charts#1086]
Hi guys,

I am currently having a problem with my self-hosted Sentry's XHR Requests and Error Logging. And I am seeking for your help :)

When `regexPathStyle` is set to `traefik` in the Sentry chart's Ingress configuration, the relay's path is `/api/{[1-9][0-9]*}/{(.*)}`. XHR requests are coming successfully to Sentry. However, we can't perform any XHR requests. Most XHR operations, like closing an issue, return a 403 HTTP status with a body:
```json
{
  "detail":"CSRF Failed: Referer checking failed - https://sentry.example.com/organizations/my-org-slug/issues/6576/?query=is%3Aunresolved+ConnectionBad&statsPeriod=14d does not match any trusted origins."
}
```

However, if I change  `regexPathStyle` to `nginx` (default value),  XHR requests work successfully, but no Errors are logged into Sentry.

This is my Ingress value:
```yaml
ingress:
  enabled: true
  regexPathStyle: 'traefik'
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.provider: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: corp-websecure
    traefik.ingress.kubernetes.io/router.tls.options: kube-system-tlsoption-intermediate@kubernetescrd
    cert-manager.io/cluster-issuer: acme-clusterissuer
  hostname: sentry.example.com
  hosts:
    - host: sentry.example.com
      paths: 
        - /
  tls:
    - secretName: sentry-tls
      hosts:
        - sentry.example.com
```

Sentry app version: 21.6.3
Sentry chart version: 11.4.0 (I see no difference for Ingress in the newest version related to path patterns)
traefik: v2.2.5
Ingress: networking.k8s.io/v1beta1
k8s: 1.17
