### ISSUE TITLE
Ingest Consumer Deployments Fail Using Concurrency Values

### ISSUE THREAD

**Issue by grippy** [sentry-kubernetes/charts#1095]
We're seeing issues with the `sentry-ingest-consumer-events` worker deployed w/ a concurrency value.

# Versions

Chart Version: `20.11.0`
Sentry App Version: `23.11.0`

# Chart Values

```
sentry:
    ingestConsumer:
      concurrency: 4
```

# Manifest Spec for ReplicaSet sentry-ingest-consumer-events-????

The run command for the container looks like this:

```
    spec:
      containers:
        - args:
            - run
            - consumer
            - ingest-events
            - '--consumer-group'
            - ingest-consumer
            - '--concurrency'
            - '4'
```

# Fails with this error

```
Usage: sentry run consumer [OPTIONS] CONSUMER_NAME [CONSUMER_ARGS]...

Try 'sentry run consumer --help' for help.


Error: No such option: --concurrency
```

# Sentry Run Command

Reading the code paths for the `sentry run consumer` command here's where the issues appear to be:

No `--concurrency` command arg defined here:
https://github.com/getsentry/sentry/blob/23.11.0/src/sentry/runner/commands/run.py#L559-L622

The stream processor factory should accept `concurrency` as an argument:
https://github.com/getsentry/sentry/blob/23.11.0/src/sentry/consumers/__init__.py#L285-L302

And then override the "processes" value here to not use the default number of processes:
https://github.com/getsentry/sentry/blob/23.11.0/src/sentry/consumers/__init__.py#L184-L191
