### ISSUE TITLE
Memcached instance reads vars from hardcoded configmap which gets prefixed on deployment

### ISSUE THREAD

**Issue by IvanovOleg** [sentry-kubernetes/charts#1159]
Hello,
If I enable sourcemaps in the helm chart, the memcached instance is created, but fails:
```yaml
envFrom:
  - configMapRef:
    name: sentry-memcached
```
Helm chart creates a configmap that called:
<release_name>-memcached

```
Error: configmap "sentry-memcached" not found
```
