### ISSUE TITLE
envelope buffer capacity exceeded

### ISSUE THREAD

**Issue by ajith-nataraj** [sentry-kubernetes/charts#1191]
if we have high traffic sentry, we are more likely to encounter this issue.
i did increase the number of replica to 10 from to resolve the issue as workaround.

below is the error, when the number of replay workers were 5
textPayload: "2024-03-28T06:21:06.523911Z ERROR relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]"

How can we increase the envelope buffer capacity.

**Comment by wozniakpl** [comment]
I had a similar problem, this helped me

```
config:
  relay: |-
    cache:
      envelope_buffer_size: 1000000
```
