### ISSUE TITLE
Allow to use `credentials set` instead of `credentials generate` in relay's initContainers

### ISSUE THREAD

**Issue by wozniakpl** [sentry-kubernetes/charts#1193]
When setting up sentry-relay deployment, initContainers has hardcoded such lines:
```
      initContainers:
        - name: {{ .Chart.Name }}-relay-init
          image: "{{ template "relay.image" . }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
          args:
            - "credentials"
            - "generate"
{{- if .Values.relay.init.additionalArgs }}
{{ toYaml .Values.relay.init.additionalArgs | indent 12 }}
{{- end }}
```

And when I look at the relay's code, I see that it would be useful to be able to set up credentials by env, not always generate them.
https://github.com/getsentry/relay/blob/master/relay/src/cli.rs#L139
