### ISSUE TITLE
`sentry-post-process-forward-` memory

### ISSUE THREAD

**Issue by KrawczowaKris** [sentry-kubernetes/charts#1205]
Hello,

Memory consumption of pods `sentry-post-process-forward-errors`, `sentry-post-process-forward-issue-platform` and `sentry-post-process-forward-transactions` is continuously increasing:

![image](https://github.com/sentry-kubernetes/charts/assets/72573143/a4e1bb36-2d6d-401f-af3b-ab91f63df7a7)

If resources are not limited, the memory consumption of each pod increased to more than 3GB.

What could be causing this?

`values.yaml`:
```yaml
sentry:
  postProcessForwardTransactions:
    resources: 
      limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
  postProcessForwardErrors:
    resources: 
     limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
  postProcessForwardIssuePlatform:
    resources: 
      limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 100Mi
```

helm chart version: `21.6.3`
