### ISSUE TITLE
Does Sentry Helm charts run out of the box ?

### ISSUE THREAD

**Issue by piellick** [sentry-kubernetes/charts#1225]
Hy everyone,

to the creation date of creation of this issues, sentry seems not run "out of the box" with default values of the charts.

```
╰─$ helm install sentry sentry/sentry -n sentry                                                                                                                                                                                                                 

coalesce.go:175: warning: skipped value for kafka.config: Not a table.
Error: INSTALLATION FAILED: failed post-install: job failed: DeadlineExceeded
```
I found plenty of ticket with `--timeout` and or `hook.activeDeadlineSeconds` increased values and or a "set of" values for a fresh install but nothing works.

I use the latest release available `22.1.1`  `22.2` looks not available on helm repo. 

Thanks

**Comment by bkk-bcd** [comment]
No, its very very troublesome. Try adding real load and the fun begins...

I think for your issue you want to add the following to your values file:

```
        hooks:
          activeDeadlineSeconds: 600
```

**Comment by piellick** [comment]
Hi @bkk-bcd , you right  so much trouble :-D .

I tried a mix of everything

with helm install -n sentry sentry sentry/sentry --version 20.0.0 --timeout 1h --values values.yaml

i have a bunch of:
`Error: INSTALLATION FAILED: failed post-install: job failed: BackoffLimitExceeded
`
or
`Error: INSTALLATION FAILED: failed post-install: job failed: DeadlineExceeded
`

values.yaml

```
user:
  create: true
  email: e@mail.com
  password: aworkingpassword

mail:
  backend: smtp
  useTls: true
  username: "username"
  password: "password"
  port: 25
  host: "smtp.someprovider.com"
  from: "from@something.domain"

service:
  name: sentry
  type: ClusterIP
  externalPort: 9000
  annotations: {}

hooks:
  activeDeadlineSeconds: 600

snuba:
  api:
    replicas: 1
  consumer:
    replicas: 1
  issueOccurrenceConsumer:
    replicas: 1
  outcomesConsumer:
    replicas: 1
  profilingFunctionsConsumer:
    replicas: 1
  profilingProfilesConsumer:
    replicas: 1
  replacer:
    replicas: 1
  replaysConsumer:
    replicas: 1
  sessionsConsumer:
    replicas: 1
  subscriptionConsumerEvents:
    replicas: 1
  subscriptionConsumerSessions:
    replicas: 1
  subscriptionConsumerTransactions:
    replicas: 1
  transactionsConsumer:
    replicas: 1
memcached:
  replicaCount: 1
rabbitmq:
  replicaCount: 1
symbolicator:
  replicas: 1

sentry:
  singleOrganization: false
  worker:
    replicas: 1
  ingestConsumer:
    replicas: 1
  ingestMetricsConsumerPerf:
    replicas: 1
  ingestMetricsConsumerRh:
    replicas: 1
  ingestMonitors:
    replicas: 1

clickhouse:
  clickhouse:
    replicas: "1"
  tabix:
    replicas: "1"

kafka:
  replicaCount: 3
  zookeeper:
    replicaCount: 1
zookeeper:
  replicaCount: 3

```

**Comment by kraegpoeth** [comment]
I got it to work by increasing the ressources:
```
sentry:
    # Allow more resources in order for deploy process to succeed
    resources:
      limits:
        cpu: 512m
        memory: 4096Mi
      requests:
        cpu: 256m
        memory: 256Mi
```
