### ISSUE TITLE
ISSUE - "certificate verify failed: self signed certificate in certificate chain" FIXED - workaround provided

### ISSUE THREAD

**Issue by chipzzz** [sentry-kubernetes/charts#1238]
Version Sentry: 24.1.2
HELM chart version: 21.5.0

Error only seen on sentry-ingest-consumer-attachments &  sentry-ingest-replay-recordings 

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dev.sentry.obs.drw', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1006)')))
21:40:36 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```

My setup with customCA:

I manually placed my certfiicate chain in both web and worker pods in `/usr/local/lib/python3.11/site-packages/certifi/cacert.pem`. I can confirm my cert chain is appended to the file. I did it as such for web and similar very similar to worker

```
        command:
          - /bin/bash
          - -c
          - |
            cp /etc/pki/ca-trust/custom/ca.pem /usr/local/share/ca-certificates/ca.pem ;
            update-ca-certificates;
            cat /usr/local/share/ca-certificates/ca.pem >> /usr/local/lib/python3.11/site-packages/certifi/cacert.pem ;
            cat /usr/local/share/ca-certificates/ca.pem >> /usr/local/lib/python3.11/site-packages/pip/_vendor/certifi/cacert.pem ;
            sentry run web
        ports:
```

On both I can confirm that's what[ certifi](https://github.com/getsentry/sentry-python/blob/30f339db3e76384e23fc951627c689197cb0e7d5/sentry_sdk/transport.py#L26) is reading 

```
>>> import certifi
>>> certifi.where()
'/usr/local/lib/python3.11/site-packages/certifi/cacert.pem'
```

Yet only for my
`sentry-ingest-consumer-attachments` and `sentry-ingest-replay-recordings` the cert verification is failing. I don't see it anywhere failing anywhere else. Tried everything without success

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<my-endpoint-url>', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1006)')))
21:24:52 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```

**Comment by chipzzz** [comment]
Similar Issues/Requests:
https://github.com/sentry-kubernetes/charts/issues/1158
https://github.com/sentry-kubernetes/charts/issues/371
https://github.com/sentry-kubernetes/charts/issues/425
https://github.com/getsentry/sentry-python/issues/164
https://github.com/getsentry/self-hosted/pull/1015

**Comment by chipzzz** [comment]
Fixed by modifying chart commands ran when sentry components start on the pods and copying my cert chain into the following paths. Same was done on worker and web

```
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - |-
          cp /etc/pki/ca-trust/custom/ca.pem /usr/local/share/ca-certificates/ca.pem ;
          update-ca-certificates ;
          cat /usr/local/share/ca-certificates/ca.pem >> /usr/local/lib/python3.11/site-packages/certifi/cacert.pem ;
          cat /usr/local/share/ca-certificates/ca.pem >> /usr/local/lib/python3.11/site-packages/pip/_vendor/certifi/cacert.pem ;
          .. <sentry command based on component>
  ```
  
  Set volumeMount and volume:
  
  ```
    volumes:
...
    - name: custom-ca
      secret:
        defaultMode: 420
        items:
          - key: ca.pem
            path: ca.pem
        secretName: sentry-dev-public-chain-cert
 ...
```


```
....
      volumeMounts:
        - mountPath: /etc/pki/ca-trust/custom
          name: custom-ca

.... 
  ````

**Comment by zentavr** [comment]
Seems like we just need to put `certificates` folder with our certs, like the doc says: https://develop.sentry.dev/self-hosted/custom-ca-roots/

**Comment by zentavr** [comment]
P.S.: Tried that and not helped

**Comment by calebmayeux** [comment]
For the next poor sucker that has to set up sentry in a corporate environment with their own CA, this is how I worked around it without having to rebake images or fork helm charts.

First, create a Kubernetes secret called corporate-ca whose contents are a key ca.crt and the value base64 encoded private CA file. Then, pass these variables to your helm chart. The web container kinda does the work for you, but for the cron and worker pods, you have to set environment variables to get python to read your CA and mount your secret as a file inside the pods.


```
sentry:
  web:
    customCA:
      secretName: corporate-ca
  worker:
    env:
      - name: REQUESTS_CA_BUNDLE
        value: /etc/ssl/certs/ca.crt
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca.crt
    volumes:
      - name: corporate-ca-volume
        secret:
          secretName: corporate-ca
    volumeMounts:
      - name: corporate-ca-volume
        mountPath: /etc/ssl/certs/ca.crt
        subPath: ca.crt
  cron:
    env:
      - name: REQUESTS_CA_BUNDLE
        value: /etc/ssl/certs/ca.crt
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca.crt
    volumes:
      - name: corporate-ca-volume
        secret:
          secretName: corporate-ca
    volumeMounts:
      - name: corporate-ca-volume
        mountPath: /etc/ssl/certs/ca.crt
        subPath: ca.crt
```

If somebody wants to make this better, they could basically put the logic for the worker and cron in the helm chart and just have a sentry customCA field that when set does all the heavy lifting.
