### ISSUE TITLE
Error in Kafka with fresh install

### ISSUE THREAD

**Issue by DrDJIng** [sentry-kubernetes/charts#1241]
Good afternoon!

Using the default values file, I use helm install to get Sentry on our Kubernetes 1.25 cluster using chart 22+

However, Kafka (and sometimes zookeeper when trying chart version 21.5.0) seem to error:

kafka Error: Could not find or load main class kafka.tools.StorageTool

I cannot for the life of me figure out what to do. Please let me know if there's any more information you need from me, I realise this isn't much to go on.

**Comment by eht16** [comment]
Same problem here.
I upgraded from chart version 20.x to 22.5.1 and got the same error.
For the upgrade, I switched from Zookeeper to Kraft but without keeping any data. Though I reused the PV of the previous Kafka instance. Assumed this might have caused the error and just started over with a fresh PV without any data. But I get the same error.

@DrDJIng did you find any solution or workaround?

I cannot find any references in the net to this error.

EDIT:
if it is relevant, I'm trying to use a combined controller+broker node and this my Kafka specific overridden config:
```yaml
kafka:
  enabled: true

  volumePermissions:
    enabled: true

  kraft:
    enabled: true
    clusterId: "(redacted)"

  controller:
    replicaCount: 1
    controllerOnly: false
    persistence:
      enabled: true
      existingClaim: sentry-kafka-storage-claim
```

EDIT 2:
What I've tried so far:
- use a fresh, new PV
- changing the clusterId
- trying with `kafka.volumePermissions.enabled: false`
- enabling "BITNAMI_DEBUG" via `kafka.image.debug: true`
- tried to start Kafka completely without storage

All attempts ended in the same error and no change in log output.
