### ISSUE TITLE
Clickhouse helm chart not updated in release 23.1.0

### ISSUE THREAD

**Issue by alexandrovas** [sentry-kubernetes/charts#1282]
Version of Clickhouse helm chart in Chart.yaml:
```yml
dependencies:
  ...
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.9.0
    condition: clickhouse.enabled
```

Version in helm chart sentry-23.1.0.tar.gz:

Cliskhouse Chart.yaml
```yml
version: 3.7.1
```

Maybe because in [this](https://github.com/sentry-kubernetes/charts/tree/develop/sentry/charts) directory old chart presented.
