### ISSUE TITLE
Sentry Relay - Breaking Change in 24.4.0 removal of metrics_transactions alias from relay - how does this affect the Sentry chart?

### ISSUE THREAD

**Issue by chipzzz** [sentry-kubernetes/charts#1306]
I'm doing a sentry upgrade and noticed the following change in relay config

```
           value: 50000000  # 50MB or bust
       redis: "redis://:@sentry-sentry-redis-master:6379"
       topics:
-        metrics_transactions: ingest-performance-metrics
         metrics_sessions: ingest-metrics
```

Related to : https://github.com/getsentry/relay/releases/tag/24.4.0

> Breaking change: Kafka topic configuration keys now support the default topic name. The previous aliases metrics and metrics_transactions are no longer supported if configuring topics manually. Use ingest-metrics or metrics_sessions instead of metrics, and ingest-performance-metrics or metrics_generic instead of metrics_transactions. (https://github.com/getsentry/relay/pull/3361)

How is this being handled in the Sentry chart- does it have to be ?
