### ISSUE TITLE
Failed helm upgrade on `23.9.0`

### ISSUE THREAD

**Issue by bmassemin** [sentry-kubernetes/charts#1322]
Flux helm controller returns this error:

```
Helm upgrade failed for release sentry/sentry with chart sentry@23.9.0: template: sentry/templates/hooks/user-create.yaml:90:3: executing "sentry/templates/hooks/user-create.yaml" at <include "sentry.env" .>: error calling include: template: sentry/templates/_helper.tpl:518:24: executing "sentry.env" at <.Values.externalPostgresql.existingSecretKeys.password>: nil pointer evaluating interface {}.password Last Helm logs: 2024-06-17T11:17:13.630783247Z: preparing upgrade for sentry 2024-06-17T11:17:13.85908239Z: resetting values to the chart's original version
```

My config:

```
    postgresql:
      enabled: false
    externalPostgresql:
      host: [REDACTED]
      port: [REDACTED]
      username: sentry
      database: sentry
      existingSecret: postgres
```

Looks like https://github.com/sentry-kubernetes/charts/pull/1279 introduced a breaking change, while the description is telling the other way around.

cc @karol-szymanowski
