### ISSUE TITLE
change kafka topic names

### ISSUE THREAD

**Issue by Meraj** [sentry-kubernetes/charts#1359]
Hi,

Is there a way to change the Kafka topic names in Sentry? I want to use an external Kafka and modify the topic names that Sentry uses. I could not find the setting or config that does this task.

Thank you!

**Comment by ivoistaken** [comment]
Please, check this might help your case: https://github.com/getsentry/snuba/issues/838

**Comment by Meraj** [comment]
Thanks, it's great. I think I should update the Helm chart for this use case. I didn't find anything that overwrites the Sentry config file.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Meraj** [comment]
hi, Custom Kafka topic names are not currently supported by this chart. To use custom names, you'll need to modify the chart templates:

### deployment-snuba-outcomes-billing-consumer.yaml
**path:** `sentry/templates/deployment-snuba-outcomes-billing-consumer.yaml`
pass the topic name to `--raw-events-topic`.

-----

### deployment-sentry-post-process-forwarder-transactions.yaml
**path:** `sentry/templates/deployment-sentry-post-process-forwarder-transactions.yaml`
pass the topic name to `--synchronize-commit-log-topic`, 

-----

### deployment-sentry-post-process-forwarder-issue-platform.yaml
**path:** `sentry/templates/deployment-sentry-post-process-forwarder-issue-platform.yaml`
pass the topic name to `--synchronize-commit-log-topic=`.

-----

### sentry/templates/deployment-sentry-post-process-forwarder-errors.yaml
**path:** `deployment-sentry-post-process-forwarder-errors.yaml`
pass the topic name to `--synchronize-commit-log-topic`

-----

### _helper-sentry-relay.tpl
**path:** `sentry/templates/_helper-sentry-relay.tpl`
you have to add the following under `processing` to map the topics for [relay server](https://github.com/getsentry/relay):
```
topics:
      events: "YOUR_PREFIX.ingest-events"
      attachments: "YOUR_PREFIX.ingest-attachments"
      transactions: "YOUR_PREFIX.ingest-transactions"
      outcomes: "YOUR_PREFIX.outcomes"
      outcomes_billing: "YOUR_PREFIX.outcomes-billing"
      metrics_sessions: "YOUR_PREFIX.ingest-metrics"
      metrics_generic: "YOUR_PREFIX.ingest-performance-metrics"
      profiles: "YOUR_PREFIX.profiles"
      replay_events: "YOUR_PREFIX.ingest-replay-events"
      replay_recordings: "YOUR_PREFIX.ingest-replay-recordings"
      monitors: "YOUR_PREFIX.ingest-monitors"
      spans: "YOUR_PREFIX.snuba-spans"
      metrics_summaries: "YOUR_PREFIX.snuba-metrics-summaries"
      cogs: "YOUR_PREFIX.shared-resources-usage"
      feedback: "YOUR_PREFIX.ingest-feedback-events"
```

-----


now you need to add KAFKA_TOPIC_OVERRIDES ([source](https://github.com/getsentry/sentry/blob/bbf0b096a8b17cd06e58f1f865dac3f21a8de38c/src/sentry/conf/server.py#L2858)) for sentry config and KAFKA_TOPIC_MAP ([source](https://github.com/getsentry/snuba/blob/21.5.0/snuba/utils/streams/topics.py))


`snubaSettingsPy` and `sentryConfPy` are in values.yaml


I'm interested in contributing to the project by adding support for custom Kafka topic names. I'd like to know if this feature is on the project roadmap or if there's an interest in incorporating it.
