### ISSUE TITLE
 warning: skipped value for kafka.config: Not a table.

### ISSUE THREAD

**Issue by yujiaao** [sentry-kubernetes/charts#1370]
According to https://artifacthub.io/packages/helm/sentry/sentry
I try install on windows wsl with Ubuntu 22.04.4 LTS.

```
$ microk8s helm install sentry sentry/sentry
coalesce.go:175: warning: skipped value for kafka.config: Not a table.
Error: INSTALLATION FAILED: failed post-install: job failed: DeadlineExceeded
```
I have try `helm uninstall sentry` then reinstall, but still failed.

Please, people, help me!

**Comment by lbcd** [comment]
Same for me. I can move forward by executing: 

`kubectl exec -it sentry-web-xxxxxxxx -n sentry -- sentry upgrade`

But I have an error after login and configuring first page.

**Comment by lbcd** [comment]
You can try:
`helm upgrade sentry sentry/sentry`

or / and doing all hook manualy (https://github.com/sentry-kubernetes/charts/tree/develop/charts/sentry/templates/hooks) : 
- db-check and db-init was done in helm upgrade for me
- `snuba bootstrap --no-migrate --kafka --force` (in snuba container)
- `snuba migrations migrate --force` (in snuba container)
- `sentry upgrade` (in sentry-web container) at the end, you can create user, so no need last hook after that create user

And that works for me :).

**Comment by lbcd** [comment]
I get others problems when I try to log some issues in sentry with my application.

So finally I remove everything an I launch: 
```
helm template sentry sentry/sentry -f values.yaml > sentry-manifest.yaml
kubectl apply -f sentry-manifest.yaml
```

I let some time to containers to start. I get some error on one time jobs (hooks) that doesn't wait containers to be ready. So I extract jobs from  `sentry-manifest.yaml` to put them in single files and I start them manually one by one.

```
kubectl apply -f hook/sentry-db-check.yaml
kubectl apply -f hook/sentry-db-init.yaml
kubectl apply -f hook/sentry-snuba-migrate.yaml
kubectl apply -f hook/user-create.yaml
```

At the end I had an ingress : 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentry
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-protocol-headers: "HTTP_X_FORWARDED_PROTO=https"
spec:
  ingressClassName: nginx
  rules:
  - host: sentry.xxxxxxx.com
    http:
      paths:
      - path: /api/store
        pathType: ImplementationSpecific
        backend:
          service:
            name: sentry-relay
            port:
              number: 3000
      - path: /api/[1-9][0-9]*/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sentry-relay
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentry-web
            port:
              number: 9000
  tls:
  - hosts:
    - sentry.xxxxxxx.com
    secretName: xxxxxxx-com-wild-card-2023-2024
```

And all works!
