### ISSUE TITLE
postgres password regenerated

### ISSUE THREAD

**Issue by KrawczowaKris** [sentry-kubernetes/charts#1385]
Hello,

I updated helm chart from `23.9.1` to `23.12.1` and got this error in `sentry-postgresql` pod:

```
2024-08-11 05:56:25.809 GMT [257378] FATAL:  password authentication failed for user "sentry"
2024-08-11 05:56:25.809 GMT [257378] DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

My postgresql parameters are set like this:
```
postgresql:
  enabled: true
  auth:
    database: sentry
    username: sentry
    password: XXXXXX
    postgresPassword: XXXXXX
```

I don't see any changes in the chart code related to postgresql.

I manually changed the password for the `sentry` user and now everything works correctly.

What could have caused this?
