### ISSUE TITLE
Cannot Sign In - Empty Form

### ISSUE THREAD

**Issue by Clashsoft** [sentry-kubernetes/charts#1400]
See https://github.com/getsentry/sentry/issues/76384

Signing in is not possible after the first time.
Clicking Continue sends me to Register, which is not what I want.

![Image](https://github.com/user-attachments/assets/c92ec78c-b1cc-4954-ac50-45d1ea266b80)

This is a completely new and default installation.
The only changed values are
```yaml
sentry:
  singleOrganization: false
nginx:
  enabled: false
ingress:
  enabled: true
  # ...
```

There are no errors in the browser console or any container.
