### ISSUE TITLE
sentry-web kubernetes pod distribution

### ISSUE THREAD

**Issue by evgenii-avdiukhin** [sentry-kubernetes/charts#1442]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

I have my sentry deployed in kubernetes using helm chart
I have key component replicas increased to 2-3 ( web, worker, cron, relay , etc)
I also have pod-anti-affinity cluster policy deployed with kyverno
All the pods except sentry-worker, are distributed evenly across worker nodes
All 3 sentry-worker pods are scheduled on worker-1
Moreover, whenever i shutdown worker-1, to check if pods evict, sentry-web pods are stuck in pending with event
`0/8 nodes are available: 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 5 node(s) didn't match pod anti-affinity rules. preemption: 0/8 nodes are available: 3 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod. `
Kyverno policies are cluster wide and are applied the same way for all sentry objects
The problem is only with sentry-web deployment, everything else works fine, distributes and evicts as it should
Do i miss something here? Been stuck with this issue for couple of days and cant find any solution.

### Your installation details

1.
```
sentry:
  web:
    enabled: true
    replicas: 3
    podLabels:
      critical: "true"
    labels:
      critical: "true"
  worker:
    enabled: true
    replicas: 3
    podLabels:
      critical: "true"
    labels:
      critical: "true"
    livenessProbe:
      enabled: true
      exec:
        command:
          - sentry
          - exec
          - '-c'
          - >-
            from sentry.celery import app; import os;
            dest="celery@{}".format(os.environ["HOSTNAME"]);
            print(app.control.ping(destination=[dest],
            timeout=10)[0][dest]["ok"])
      initialDelaySeconds: 60
      periodSeconds: 60
      timeoutSeconds: 15
      failureThreshold: 5
      successThreshold: 1
  cron:
    enabled: true
    replicaCount: 3
    podLabels:
      critical: "true"
    labels:
      critical: "true"
relay:
  enabled: true
  replicaCount: 2
  podLabels:
    critical: "true"
  labels:
    critical: "true"

rabbitmq:
  pdb:
    create: false
  enabled: true
  clustering:
    forceBoot: true
    rebalance: true
  replicaCount: 3
  podLabels:
    critical: "true"
  labels:
    critical: "true"
redis:
  enabled: true
  replica:
    replicaCount: 3
  podLabels:
    critical: "true"
  labels:
    critical: "true"
  commonConfiguration: |-
    appendonly no
    save ""
clickhouse:
  enabled: true
  clickhouse:
    replicas: "3"
  podLabels:
    critical: "true"
  labels:
    critical: "true"
kafka:
  podLabels:
    critical: "true"
  labels:
    critical: "true"
postgresql:
  enabled: false
externalPostgresql:
  host: sentry-postgresql-ha-pgpool.sentry.svc.cluster.local
  port: 5432
  username: postgres
  password: secret
  database: postgres
  sslMode: disable
  connMaxAge: 0
user:
  create: true
  email: secret
  password: secret
google:
  clientId: secret
  clientSecret: secret
hooks:
  activeDeadlineSeconds: 1000000
```
2.
chart version: 25.3.0, app version: 24.5.1 

### Steps to reproduce

deploy sentry with chart having sentry-web replicas increased and see if they schedule on different workers
