### ISSUE TITLE
Like to check whether it can support sub path for ingress

### ISSUE THREAD

**Issue by tanjianyong** [sentry-kubernetes/charts#1457]
I have two questions below. Please help to ask.
1) I‘d like to check whether sentry/sentry can support **sub path** in ingress to access sentry web and api. Here is the setting from my side. It will access to  https://xxxx/auth/login/sentry/ and get 404 from nginx.

```
nginx:
  existingServerBlockConfigmap: sentry-nginx
  enabled: false
  containerPort: 8080
  existingServerBlockConfigmap: '{{ template "sentry.fullname" . }}'
  resources: {}
  replicaCount: 1
  service:
    type: ClusterIP
    ports:
      http: 80
  extraLocationSnippet: false
  customReadinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  # extraLocationSnippet: |
  #  location /admin {
  #    allow 1.2.3.4; # VPN network
  #    deny all;
  #    proxy_pass http://sentry;
  #  }
  # Use this to enable an extra service account
  # serviceAccount:
  #   create: false
  #   name: nginx

ingress:
  enabled: false
  ingressClassName: ava-nginx
  path: /sentry
  # If you are using traefik ingress controller, switch this to 'traefik'
  # if you are using AWS ALB Ingress controller, switch this to 'aws-alb'
  # if you are using GKE Ingress controller, switch this to 'gke'annotations
  regexPathStyle: nginx
  # ingressClassName: nginx
  # If you are using AWS ALB Ingress controller, switch to true if you want activate the http to https redirection.
  alb:
    httpRedirect: true
  annotations:
  #   If you are using nginx ingress controller, please use at least those 2 annotations
    kubernetes.io/ingress.class: ava-nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  #   https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    kubernetes.io/name: sentry-nginx
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/secure-backends: "true"
  #
  # hostname: xxxx
  # additionalHostNames: []
  # #
  # tls:
  # - secretName: ava-tls-secret
  #   hosts: 
  #     - xxxx
```

2) When I use nginx setting in other ingress to access sentry-web directly, it can work to access sentry-web. But I can't access api. It can't work. I can get log in sentry-web like these below.  Please comment if you have any ideas.

04:37:39 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=a6dc7645a71130216a08ac0aaa5bfc36&sentry_version=7&sentry_client=sentry.javascript.react%2F8.30.0'>)

**Comment by patsevanton** [comment]
Please correct the formatting. Move the code to markdown quotes

**Comment by tanjianyong** [comment]
Hi @patsevanton ,
I've formatted the configuration. Thanks for the info.

**Comment by patsevanton** [comment]
Take the following configuration as a basis for testing

```
user:
  password: "xxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
  regexPathStyle: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    # https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
symbolicator:
  enabled: true
```
