### ISSUE TITLE
Not correct order of arguments for sentry consumers

### ISSUE THREAD

**Issue by MemberIT** [sentry-kubernetes/charts#1463]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Failed start sentry consumers after merge commit https://github.com/sentry-kubernetes/charts/commit/dbafa66025fd9ecb3eb4b07a5df53f97221e77da - not correct order of arguments for sentry consumers (24.7.1)

Official help of sentry consumers (24.7.1):
```
docker run --rm --entrypoint sentry getsentry/sentry:24.7.1 run consumer --help | grep -A 1 -B 13 "\-\-processes"

  Launch a "new-style" consumer based on its "consumer name".

  Example:

      sentry run consumer ingest-profiles --consumer-group ingest-profiles

  runs the ingest-profiles consumer with the consumer group ingest-profiles.

  Consumers are defined in 'sentry.consumers'. Each consumer can take
  additional CLI options. Those can be passed after '--':

      sentry run consumer ingest-occurrences --consumer-group occurrence-
      consumer -- --processes 1

```

### values.yaml

```
...
sentry:
  ingestConsumerAttachments:
    enabled: true
    replicas: 2
    concurrency: 1 
    env: []
    resources:
      requests:
        cpu: 300m
        memory: 768Mi
      limits:
        cpu: 600m
        memory: 1536Mi
    affinity: {}
    nodeSelector: {}
    securityContext: {}
    containerSecurityContext: {}
...
```

### Helm chart version

v28.5.0

### Steps to reproduce

For example set:
```
.Values.sentry.ingestConsumerEvents.concurrency: 1
```
in values.yaml
