### ISSUE TITLE
Incompatibility with own CA since helm chart version 25.6.0

### ISSUE THREAD

**Issue by boindil** [sentry-kubernetes/charts#1475]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Since https://github.com/sentry-kubernetes/charts/compare/sentry-v25.5.1...sentry-v25.6.0 (updating sentry to 24.7.1) own CAs are not working anymore.

Behavior:
https://github.com/getsentry/self-hosted/issues/2950 (happening in web-container as well)

There is a workaround in that ticket, however this would have to be handled by the helm chart with additional initialization scripts.

### Expected behavior

No errors

### values.yaml

```
[...]
ingress:
  alb:
    httpRedirect: false
  enabled: true
  regexPathStyle: nginx
  ingressClassName: nginx
  hostname: sentry.hostname.intern
  tls:
    - hosts:
        - sentry.hostname.intern
      secretName: tls-hostname
system:
  adminEmail: admin@xxxx
  public: true
  url: https://sentry.hostname.intern
  secretKey: xxx
[...]
```

### Helm chart version

since 25.6.0

### Steps to reproduce

use internally signed CA certificate that is valid for domain
