### ISSUE TITLE
jmx-metrics servicemonitor has wrong path

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1476]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

- prometheus-operator will pick up the new service
- target reports as DOWN in prometheus with error expected a valid start token, got "<" ("INVALID") while parsing: "<"

### Expected behavior

prometheus being able to scrape metrics

### values.yaml

```
user:
  password: "xxxxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
  regexPathStyle: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    # https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
symbolicator:
  enabled: true
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"
kafka:
  provisioning:
    replicationFactor: 3
  heapOpts: -Xmx4096m -Xms4096m
  global:
    storageClass: yc-network-ssd
  controller:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  broker:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  metrics:
    enabled: true
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      path: /metrics
      labels:
        release: prometheus
```

### Helm chart version

```
v25.9.0
```

### Steps to reproduce

```
helm install sentry -n test sentry/sentry --version 25.9.0  -f values-sentry-local.yaml --wait --timeout=1000s
```

### Logs

expected a valid start token, got "<" ("INVALID") while parsing: "<"

### Additional context

Kafka issue https://github.com/bitnami/charts/issues/27546
Kafka fix https://github.com/bitnami/charts/pull/27562
