### ISSUE TITLE
sentry.tasks.derive_code_mappings: No installation or organization integration found

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1481]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

```
sentry-worker 04:47:42 [INFO] sentry.tasks.derive_code_mappings: No installation or organization integration found. (organization.slug='sentry'
```

### values.yaml

```
user:
  password: "xxxxxxxxxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
  regexPathStyle: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    # https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
symbolicator:
  enabled: true
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"
kafka:
  provisioning:
    replicationFactor: 3
  heapOpts: -Xmx4096m -Xms4096m
  global:
    storageClass: yc-network-ssd
  controller:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  broker:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  metrics:
    enabled: true
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
config:
  snubaSettingsPy: |
    TOPIC_PARTITION_COUNTS = {
      "ingest-events": 10,
    }
sentry:
  ingestConsumerEvents:
    replicas: 10
  worker:
    replicas: 10
```  

### Helm chart version

```
25.6.0-25.10.0
```

### Steps to reproduce

```
helm install sentry -n test sentry/sentry --version 25.6.0  -f values-sentry-local.yaml --wait --timeout=1000s
```

### Logs

```
sentry-worker-7fb9f98ddf-h2q2m sentry-worker 04:47:42 [INFO] sentry.tasks.post_process: derive_code_mappings: Queuing code mapping derivation (organization.slug='sentry' project.slug='go' group_id=6 next_time=datetime.datetime(2024, 9, 26, 5, 47, 42, 303874, tzinfo=datetime.timezone.utc))
sentry-worker-7fb9f98ddf-f7hhs sentry-worker 04:47:42 [INFO] sentry.tasks.derive_code_mappings: No installation or organization integration found. (organization.slug='sentry')
sentry-worker-7fb9f98ddf-v68zp sentry-worker 04:47:42 [INFO] sentry.tasks.derive_code_mappings: No installation or organization integration found. (organization.slug='sentry')
sentry-worker-7fb9f98ddf-zhfvs sentry-worker 04:47:42 [INFO] sentry.tasks.post_process: derive_code_mappings: Queuing code mapping derivation (organization.slug='sentry' project.slug='go' group_id=1 next_time=datetime.datetime(2024, 9, 26, 5, 47, 42, 319167, tzinfo=datetime.timezone.utc))
sentry-worker-7fb9f98ddf-shrmw sentry-worker 04:47:42 [INFO] sentry.tasks.post_process: derive_code_mappings: Queuing code mapping derivation (organization.slug='sentry' project.slug='go' group_id=6 next_time=datetime.datetime(2024, 9, 26, 5, 47, 42, 319892, tzinfo=datetime.timezone.utc))
sentry-worker-7fb9f98ddf-h2q2m sentry-worker 04:47:42 [INFO] sentry.tasks.derive_code_mappings: No installation or organization integration found. (organization.slug='sentry'
```
