### ISSUE TITLE
The "Last Seen" field is not updated

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1482]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

![image](https://github.com/user-attachments/assets/e9bfc05b-02d6-42de-9839-5f9d066dc78e)

a few moment later

![image](https://github.com/user-attachments/assets/dbd1198c-9398-4946-8c1c-7d2d4a9ffcf9)

### Expected behavior

To update the "Last Seen" field

### values.yaml

```
user:
  password: "xxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
  regexPathStyle: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    # https://github.com/getsentry/self-hosted/issues/1927
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
symbolicator:
  enabled: true
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"
kafka:
  provisioning:
    replicationFactor: 3
  heapOpts: -Xmx4096m -Xms4096m
  global:
    storageClass: yc-network-ssd
  controller:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  broker:
    persistence:
      size: 100Gi
    logPersistence:
      size: 100Gi
    resourcesPreset: large
  metrics:
    enabled: true
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
config:
  snubaSettingsPy: |
    TOPIC_PARTITION_COUNTS = {
      "ingest-events": 10,
    }
sentry:
  ingestConsumerEvents:
    replicas: 10
  worker:
    replicas: 10
```

### Helm chart version

```
25.6.0-25.10.0
```

### Steps to reproduce

```
helm install sentry -n test sentry/sentry --version 25.6.0  -f values-sentry-local.yaml --wait --timeout=1000s
```

**Comment by patsevanton** [comment]
Fixed by values.yaml with 25.10.0 helm chart version:
```
user:
  password: "xxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
nginx:
  enabled: false
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"
sentry:
  features:
    enableProfiling: true
  genericMetricsConsumer:
    replicas: 2
  ingestConsumer:
    replicas: 5
  ingestConsumerEvents:
    replicas: 5
  ingestMonitors:
    replicas: 2
  postProcessForwardTransactions:
    replicas: 2
  worker:
    replicas: 15
    concurrency: 2
snuba:
  consumer:
    replicas: 2
  outcomesConsumer:
    replicas: 2
  sessionsConsumer:
    replicas: 2
  subscriptionConsumerEvents:
    enabled: false
  subscriptionConsumerGenericMetrics:
    enabled: false
  subscriptionConsumerMetrics:
    enabled: false
  subscriptionConsumerSessions:
    enabled: false
  subscriptionConsumerTransactions:
    enabled: false
  replaysConsumer:
    enabled: false
  genericMetricsCountersConsumer:
    enabled: false
  genericMetricsDistributionsConsumer:
    enabled: false
  genericMetricsSetsConsumer:
    enabled: false
  metricsConsumer:
    enabled: false
symbolicator:
  enabled: true
rabbitmq:
  enabled: false
```

**Comment by patsevanton** [comment]
![Uploading image.png…]()

**Comment by patsevanton** [comment]
also, the "Last Seen" field is updated with the following values.yaml with 25.10.0 helm chart version:
```
user:
  password: "xxxxxxxxxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
nginx:
  enabled: false
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "400"
sentry:
  features:
    enableProfiling: true
  genericMetricsConsumer:
    replicas: 2
  ingestConsumer:
    replicas: 5
  ingestConsumerEvents:
    replicas: 5
  ingestMonitors:
    replicas: 2
  postProcessForwardTransactions:
    replicas: 2
  worker:
    replicas: 15
    concurrency: 2
snuba:
  consumer:
    replicas: 2
  outcomesConsumer:
    replicas: 2
  sessionsConsumer:
    replicas: 2
  subscriptionConsumerEvents:
    enabled: false
  subscriptionConsumerGenericMetrics:
    enabled: false
  subscriptionConsumerMetrics:
    enabled: false
  subscriptionConsumerSessions:
    enabled: false
  subscriptionConsumerTransactions:
    enabled: false
  replaysConsumer:
    enabled: false
  genericMetricsCountersConsumer:
    enabled: false
  genericMetricsDistributionsConsumer:
    enabled: false
  genericMetricsSetsConsumer:
    enabled: false
  metricsConsumer:
    enabled: false
symbolicator:
  enabled: true
```

**Comment by patsevanton** [comment]
also, the "Last Seen" field is updated with the following values.yaml with 25.10.0 helm chart version:
```
user:
  password: "xxxxxxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
nginx:
  enabled: false
sentry:
  features:
    enableProfiling: true
  genericMetricsConsumer:
    replicas: 2
  ingestConsumer:
    replicas: 5
  ingestConsumerEvents:
    replicas: 5
```

**Comment by patsevanton** [comment]
Strangely, the "Last seen" field is updated with the following values.yaml with 25.10.0 helm chart version:
```
user:
  password: "xxxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
nginx:
  enabled: false
```
