### ISSUE TITLE
FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1488]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

```
sentry-sentry-postgresql-0 postgresql 2024-09-27 07:14:15.945 GMT [529640] FATAL:  sorry, too many clients already
sentry-sentry-postgresql-0 postgresql 2024-09-27 07:14:15.948 GMT [529641] FATAL:  sorry, too many clients already
```

### Expected behavior

no errors

### values.yaml

```
user:
  password: "xxxx"
  create: true
  email: admin@sentry.apatsev.org.ru
system:
  url: "http://sentry.apatsev.org.ru"
hooks:
  activeDeadlineSeconds: 600
ingress:
  enabled: true
  hostname: sentry.apatsev.org.ru
  ingressClassName: "nginx"
nginx:
  enabled: true
sentry:
  ingestConsumer:
    replicas: 5
  ingestConsumerEvents:
    replicas: 5
  worker:
    replicas: 15
```

### Helm chart version

```
25.10.0
```

### Steps to reproduce

```
helm install sentry -n test sentry/sentry --version 25.10.0  -f values-sentry-local.yaml --wait --timeout=1000s
```
send many exceptions to sentry

### Logs

```
sentry-sentry-postgresql-0 postgresql 2024-09-27 07:14:15.796 GMT [529630] FATAL:  sorry, too many clients already
sentry-sentry-postgresql-0 postgresql 2024-09-27 07:14:15.945 GMT [529640] FATAL:  sorry, too many clients already
sentry-sentry-postgresql-0 postgresql 2024-09-27 07:14:15.948 GMT [529641] FATAL:  sorry, too many clients already
```

and
```
sentry-web-c76f54dfd-z4vms sentry-web psycopg2.OperationalError: connection to server at "sentry-sentry-postgresql" (10.96.247.106), port 5432 failed: FATAL:  sorry, too many clients already
```
