### ISSUE TITLE
external services not obeyed 

### ISSUE THREAD

**Issue by Perfect-Web** [sentry-kubernetes/charts#149]
having 
```
kafka:
  enabled: false
rabbitmq:
  enabled: false
postgresql:
  enabled: false
```

does not have any effect, the chart ignores those and still deploys them
