### ISSUE TITLE
Upgrade failure: Chart 18.0.0 to 20.0.0

### ISSUE THREAD

**Issue by swade1987** [sentry-kubernetes/charts#1504]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

The sentry worker failed to start due to the below:

```
psycopg2.errors.UndefinedColumn: column sentry_monitorcheckin.expected_time does not exist
LINE 1: ...pdated", "sentry_monitorcheckin"."attachment_id", "sentry_mo...
``` 

### Expected behavior

The booting of sentry worker comes up clean

### values.yaml

```
    mail:
      existingSecret: sentry-mail-password
      backend: smtp
      useTls: true
      username: "REDACTED"
      port: 587
      host: REDACTED
      from: "sentry@REDACTED.com"
    user:
      create: true
      email: service-account-sentry@REDACTED.com
      existingSecret: sentry-admin-password
      existingSecretKey: admin-password
    serviceAccount:
      enabled: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::${aws_acc_no}:role/sentry-${cluster_region_short}
    filestore:
      backend: s3
      s3:
        bucketName: ${sentry_filestore_bucket}
        region_name: ${cluster_region}
        default_acl: private
        encryption: "true"
    # Data store configuration
    zookeeper:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          memory: 450Mi
          cpu: 250m
      persistence:
        size: 32Gi
      serviceAccount:
        create: true
        name: sentry-zookeeper-clickhouse
      sidecars:
        - name: cleanup-logs
          image: alpine:3.18.2
          command:
            - /bin/sh
          args:
            - -c
            - "while true; do sleep 86400 && find /bitnami/zookeeper/data -type f -mtime +14 -name 'log.*' -print0 | xargs -r0 rm --; done;"
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
    kafka:
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          memory: 1Gi
          cpu: 250m
      zookeeper:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            memory: 400Mi
            cpu: 250m
        serviceAccount:
          create: true
          name: sentry-zookeeper
    clickhouse:
      serviceAccount:
        enabled: true
        name: sentry-clickhouse
    redis:
      enabled: false
    externalRedis:
      host: redis-master.sentry-v25.svc.cluster.local
      port: 6379
    postgresql:
      enabled: false
    externalPostgresql:
      database: sentry
      host: postgres-postgresql.sentry-v25.svc.cluster.local
      port: 5432
      username: sentry
      existingSecret: postgres-credentials
      existingSecretKey: user-password
    rabbitmq:
      enabled: false
    # Ingress configuration
    nginx:
      enabled: false
    ingress:
      enabled: true
      istioNamespace: istio-system
      hostname: sentry-v25.${cluster_region_short}.${cluster_env}-REDACTED.com
      ingressGatewayName: istio-ingressgateway
      certArn: ${app_wildcard_cert_arn}
      scheme: internet-facing
      targetType: ip
      wafArn: ${sentry_waf_arn}
      logging:
        enabled: ${alb_logging_enabled}
        bucket: ${alb_logging_s3_bucket}
    # Sentry components configuration
    relay:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 100Mi
      init:
        resources:
          limits:
            cpu: 500m
            memory: 450Mi
          requests:
            cpu: 200m
            memory: 150Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sentry
                  - key: role
                    operator: In
                    values:
                      - relay
              topologyKey: topology.kubernetes.io/zone
    sentry:
      web:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - web
                topologyKey: topology.kubernetes.io/zone
      worker:
        resources:
          limits:
            cpu: 700m
            memory: 2Gi
          requests:
            cpu: 30m
            memory: 100Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - worker
                topologyKey: kubernetes.io/hostname
      ingestConsumer:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 170Mi
      ingestMetricsConsumerPerf:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 310Mi
      ingestMetricsConsumerRh:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 300Mi
      ingestReplayRecordings:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 150Mi
      billingMetricsConsumer:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 150Mi
      cron:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 50m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - cron
                topologyKey: topology.kubernetes.io/zone
      subscriptionConsumerEvents:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 80Mi
      subscriptionConsumerSessions:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
      subscriptionConsumerTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
      postProcessForwardErrors:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      postProcessForwardTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      cleanup:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
        serviceAccount:
          name: sentry-cleanup
    snuba:
      # Note: The full list has not been added here YET to configure each component
      api:
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 20m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - snuba-api
                topologyKey: topology.kubernetes.io/zone
      consumer:
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      outcomesConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      outcomesBillingConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      replacer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      metricsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      subscriptionConsumerEvents:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      subscriptionConsumerTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      subscriptionConsumerSessions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      replaysConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      sessionsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      transactionsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
```

### Helm chart version

20.0.0

### Steps to reproduce

- Stood up new Postgres cluster  (see config below)
- Migrated existing database across to Postgres
- Forked version 20.0.0 of the chart
- Made the necessary changes (required for Istio)
- Attempted first clean installation
- Bug in the upstream chart 
- Made the necessary fix to our forked chart
- Re-deployed
- Hit the issue [here](https://gist.github.com/swade1987/13392a8f92cb6d26348adcd0c63cc84c) with the worker failing to boot successfully (data issues)

### Postgres configuration

```
  chart:
    spec:
      chart: postgresql
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 15.5.34
  interval: 5m
  releaseName: postgres
  values:
    architecture: standalone
    auth:
      enablePostgresUser: true
      existingSecret: postgres-credentials
      database: sentry
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.4.0-debian-12-r11
      pullPolicy: Always
```

### Logs

https://gist.github.com/swade1987/13392a8f92cb6d26348adcd0c63cc84c

**Comment by swade1987** [comment]
Update:

Attempt to re-run the migration using the following Postgres configuration (see below)

```
    spec:
      chart: postgresql
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 12.5.9
  interval: 5m
  releaseName: postgres
  values:
    architecture: standalone
    auth:
      enablePostgresUser: true
      existingSecret: postgres-credentials
      database: sentry
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 15.3.0-debian-11-r85
      pullPolicy: Always
```

But I got different errors from the Sentry worker (https://gist.github.com/swade1987/ac2fd3f4fe9a5e5eed5bbcc5807906e3)

**Comment by swade1987** [comment]
Update: I managed to get it working by upgrading from `v23.3.1` to `v23.4.0` but using the following configuration:

```
    clickhouse:
      clickhouse:
        replicas: "1"
        imageVersion: "21.8.14.5"
```
