### ISSUE TITLE
Fresh installation of v25.9.0 chart fails

### ISSUE THREAD

**Issue by swade1987** [sentry-kubernetes/charts#1508]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

The following log output occurs from `sentry-snuba-migration` on a fresh install with a brand new empty database

```
snuba.clusters.cluster.UndefinedClickhouseCluster: StorageSetKey.EVENTS_ANALYTICS_PLATFORM is not defined in the CLUSTERS setting for this environment
```

For the full log output please see [here](https://gist.githubusercontent.com/swade1987/670eb0cf0df7cd8c94650db2a82aa412/raw/0a0abb7ca449b0342b03200e431a768dea92fc0f/sentry-snuba-migrate).

### Expected behavior

The application should boot successfully without issue

### values.yaml

Postgres

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: sentry-v25
spec:
  # Ref: https://github.com/bitnami/charts/tree/postgresql/15.5.34/bitnami/postgresql
  chart:
    spec:
      chart: postgresql
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 15.5.34
  interval: 5m
  releaseName: postgres
  values:
    architecture: standalone
    auth:
      enablePostgresUser: true
      existingSecret: postgres-credentials
      database: sentry
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 16.4.0-debian-12-r11
      pullPolicy: Always
    primary:
      name: sentry
      persistence:
        enabled: true
        storageClass: "ebs-encrypted"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
```

Redis

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: sentry-v25
spec:
  # Ref: https://github.com/bitnami/charts/blob/redis/20.1.4/bitnami/redis/values.yaml
  chart:
    spec:
      chart: redis
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 20.1.4
  interval: 5m
  releaseName: redis
  values:
    architecture: standalone
    auth:
      enabled: true
      existingSecret: redis-credentials
      existingSecretPasswordKey: redis-password
      sentinel: false
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 7.4.0-debian-12-r4
      pullPolicy: Always
    master:
      persistence:
        enabled: true
        storageClass: "ebs-encrypted"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 1
          memory: 1Gi

```

Sentry

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sentry
  namespace: sentry-v25
spec:
  timeout: 15m
  interval: 1m
  # Ref: https://github.com/REDACTED/infrastructure/tree/main/charts/sentry
  chart:
    spec:
      chart: sentry
      version: 25.9.0-rc.5
      sourceRef:
        kind: HelmRepository
        name: harbor-oci-stable
        namespace: flux-system
      interval: 1m
  values:
    mail:
      existingSecret: sentry-mail-password
      backend: smtp
      useTls: true
      username: "algbra"
      port: 587
      host: smtp.mandrillapp.com
      from: "sentry@algbra.com"
    user:
      create: true
      email: service-account-sentry@REDACTED.com
      existingSecret: sentry-admin-password
      existingSecretKey: admin-password
    serviceAccount:
      enabled: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::${aws_acc_no}:role/sentry-${cluster_region_short}
    filestore:
      backend: s3
      s3:
        bucketName: ${sentry_filestore_bucket}
        region_name: ${cluster_region}
        default_acl: private
        encryption: "true"
    # Data store configuration
    zookeeper:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          memory: 450Mi
          cpu: 250m
      persistence:
        size: 32Gi
      serviceAccount:
        create: true
        name: sentry-zookeeper-clickhouse
      sidecars:
        - name: cleanup-logs
          image: alpine:3.18.2
          command:
            - /bin/sh
          args:
            - -c
            - "while true; do sleep 86400 && find /bitnami/zookeeper/data -type f -mtime +14 -name 'log.*' -print0 | xargs -r0 rm --; done;"
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
    kafka:
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          memory: 1Gi
          cpu: 250m
      zookeeper:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            memory: 400Mi
            cpu: 250m
        serviceAccount:
          create: true
          name: sentry-zookeeper
    clickhouse:
      clickhouse:
        replicas: "1"
        imageVersion: "21.8.14.5" # Ref: https://github.com/sentry-kubernetes/charts/issues/945#issuecomment-1685731039
      serviceAccount:
        enabled: true
        name: sentry-clickhouse
    redis:
      enabled: false
    externalRedis:
      host: redis-master.sentry-v25.svc.cluster.local
      port: 6379
    postgresql:
      enabled: false
    externalPostgresql:
      database: sentry
      host: postgres-postgresql.sentry-v25.svc.cluster.local
      port: 5432
      username: sentry
      existingSecret: postgres-credentials
      existingSecretKeys:
        password: user-password
    rabbitmq:
      enabled: false
    # Ingress configuration
    nginx:
      enabled: false
    ingress:
      enabled: true
      istioNamespace: istio-system
      hostname: sentry-v25.${cluster_region_short}.${cluster_env}-REDACTED.com
      ingressGatewayName: istio-ingressgateway
      certArn: ${app_wildcard_cert_arn}
      scheme: internet-facing
      targetType: ip
      wafArn: ${sentry_waf_arn}
      logging:
        enabled: ${alb_logging_enabled}
        bucket: ${alb_logging_s3_bucket}
    # Sentry components configuration
    relay:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 100Mi
      init:
        resources:
          limits:
            cpu: 500m
            memory: 450Mi
          requests:
            cpu: 200m
            memory: 150Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sentry
                  - key: role
                    operator: In
                    values:
                      - relay
              topologyKey: topology.kubernetes.io/zone
    sentry:
      web:
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - web
                topologyKey: topology.kubernetes.io/zone
      worker:
        resources:
          limits:
            cpu: 700m
            memory: 2Gi
          requests:
            cpu: 30m
            memory: 100Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - worker
                topologyKey: kubernetes.io/hostname
      ingestConsumer:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 170Mi
      ingestMetricsConsumerPerf:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 310Mi
      ingestMetricsConsumerRh:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 300Mi
      ingestReplayRecordings:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 150Mi
      billingMetricsConsumer:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 10m
            memory: 150Mi
      cron:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 50m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - cron
                topologyKey: topology.kubernetes.io/zone
      subscriptionConsumerEvents:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 80Mi
      subscriptionConsumerSessions:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
      subscriptionConsumerTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
      postProcessForwardErrors:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      postProcessForwardTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      cleanup:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 80Mi
        serviceAccount:
          name: sentry-cleanup
    snuba:
      # Note: The full list has not been added here YET to configure each component
      api:
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 20m
            memory: 200Mi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sentry
                    - key: role
                      operator: In
                      values:
                        - snuba-api
                topologyKey: topology.kubernetes.io/zone
      consumer:
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      outcomesConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      outcomesBillingConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      replacer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      metricsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      subscriptionConsumerEvents:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      subscriptionConsumerTransactions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      subscriptionConsumerSessions:
        resources:
          limits:
            cpu: 200m
            memory: 700Mi
          requests:
            cpu: 20m
            memory: 120Mi
      replaysConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      sessionsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
      transactionsConsumer:
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
```

### Helm chart version

v25.9.0 

Note: It's a forked version with some additional changes for Istio to work successfully.

### Steps to reproduce

Standup Postgres and Redis and deploy the Sentry HelmRelease as defined above.

### Logs

```
snuba.clusters.cluster.UndefinedClickhouseCluster: StorageSetKey.EVENTS_ANALYTICS_PLATFORM is not defined in the CLUSTERS setting for this environment
```

For the full log output please see [here](https://gist.githubusercontent.com/swade1987/670eb0cf0df7cd8c94650db2a82aa412/raw/0a0abb7ca449b0342b03200e431a768dea92fc0f/sentry-snuba-migrate).
