### ISSUE TITLE
Cannot edit SENTRY_SINGLE_ORGANIZATION

### ISSUE THREAD

**Issue by tetsun** [sentry-kubernetes/charts#157]
https://github.com/sentry-kubernetes/charts/blob/7ae365187da883efd891c351dc75c2e566112718/sentry/templates/configmap-sentry.yaml#L141

want enable multiple organization.

**Comment by sijmenvos** [comment]
You can override it in the helm values:

```yaml
config:
  sentryConfPy: |
    SENTRY_SINGLE_ORGANIZATION = False
```
