### ISSUE TITLE
Sentry cleanup terminates unexpectedly

### ISSUE THREAD

**Issue by swade1987** [sentry-kubernetes/charts#1585]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

The sentry cleanup task fails daily, and I cannot determine the reason for the failure. 

### Expected behavior

Either the job runs successfully or the error is visible in the logs.

### values.yaml

```
sentry:
    cleanup:
      successfulJobsHistoryLimit: 5
      failedJobsHistoryLimit: 5
      activeDeadlineSeconds: 100
      concurrencyPolicy: Allow
      concurrency: 1
      enabled: true
      schedule: "0 0 * * *"
      days: 90
      logLevel: DEBUG
      # securityContext: {}
      # containerSecurityContext: {}
      sidecars: []
      volumes: []
      # volumeMounts: []
      serviceAccount: {}
```

### Helm chart version

A forked version of 25.9.0

### Steps to reproduce

Deploy the version of 25.9.0 and tail the logs of the cleanup job.

### Screenshots

<img width="634" alt="Screenshot 2024-11-05 at 10 57 16" src="https://github.com/user-attachments/assets/9ecea5a8-7216-484f-9de9-42d05d397cd8">

### Logs

Note: The cleanup job log level is `debug` see the `values.yaml` provided.

**Comment by swade1987** [comment]
I think this behaviour is happening because:

1. The main [cleanup code](https://github.com/getsentry/sentry/blob/06a7404ef00ce4af95ab615c420a73730e60fee2/src/sentry/runner/commands/cleanup.py#L4) has completed all its intended cleanup tasks successfully
2. The final message about "attempting to send 1 pending events" appears to be related to Sentry SDK's own instrumentation of the cleanup job.

Looking at the code, I can see that the cleanup job creates a transaction to track its own execution:

```
pythonCopytransaction = sentry_sdk.start_transaction(op="cleanup", name="cleanup")
transaction.__enter__()
# ... cleanup work happens ...
if transaction:
    transaction.__exit__(None, None, None)
```

When the cleanup job finishes, the Sentry SDK tries to send its own monitoring event about the cleanup job's execution. Still, the process exits before the SDK can complete sending this monitoring data. This does not affect the actual cleanup work—all the intended cleanup tasks have already been completed successfully.

**Comment by swade1987** [comment]
Fixed (see below)

Increased the `activeDeadlineSeconds` to give more time for the cleanup to complete before forcing termination:

```yaml
sentry:
  cleanup:
    activeDeadlineSeconds: 1000
```
