### ISSUE TITLE
Why are all the pods in my deployed Sentry unable to connect to sentry-sentry-redis-master-0?

### ISSUE THREAD

**Issue by ZLBillShaw** [sentry-kubernetes/charts#1594]
In my sentry-sentry-redis-master-0 pod, it shows `*Ready to accept connections`, but all my other pods cannot connect. For example:

In `sentry-sentry-redis-replicas-0`:
```
* Connecting to MASTER sentry-sentry-redis-master-0.sentry-sentry-redis-headless.default.svc.cluster.local:6379
1:S 04 Nov 2024 12:58:58.628 # Unable to connect to MASTER: Resource temporarily unavailable
```

`In sentry-web-79d7b6dd85-lpcqj`:
```
sentry.exceptions.InvalidConfiguration: Error -3 connecting to sentry-sentry-redis-master:6379. Temporary failure in name resolution.
```

**Comment by wooch82** [comment]
Hello, maybe there are some misconfigurations in your values file. Replica tried to connect to the master in the default namespace, and the web searched for it in the same namespace. Where does the master exist?

**Comment by ZLBillShaw** [comment]
All my Sentry-related pods are running in the default namespace. 
<img width="858" alt="image" src="https://github.com/user-attachments/assets/704f694a-fb1a-4537-8bdf-2204fcbcb726">

Here is my Redis configuration, which seems correct
```
redis:
  enabled: true
  replica:
    replicaCount: 1
    persistence:
      size: 10Gi
  auth:
    enabled: false
    sentinel: false
    ## Just omit the password field if your redis cluster doesn't use password
    # password: redis
    # existingSecret: secret-name
    ## set existingSecretPasswordKey if key name inside existingSecret is different from redis-password'
    # existingSecretPasswordKey: secret-key-name
  nameOverride: sentry-redis
  master:
    persistence:
      enabled: true
      size: 10Gi
  ## Use this to enable an extra service account
  # serviceAccount:
  #   create: false
  #   name: sentry-redis
```
