### ISSUE TITLE
Profiling insights not working

### ISSUE THREAD

**Issue by boris-savic** [sentry-kubernetes/charts#1601]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Installed the latest chart with sentry version 24.9.0 and enabled the profiling.

I seem to have everything now working, except for Profiling. 

The Performance data is there, i can see individual profiles, but when I click on the Profiling its empty.

Seems like something is not being processed in the background, I've checked all containers and logs and I cannot find anything useful. Would greatly appreciate any help 

### values.yaml

```yaml
user:
  create: true
  email: some-email@example.com
  password: supersecret

asHook: true

nginx:
  enabled: false

postgresql:
  enabled: false


kafka:
  controller:
    resourcesPreset: large


externalPostgresql:
  existingSecret: sentry-db-app
  existingSecretKeys: 
    password: password
    username: username
    database: dbname
    port: port
    host: host

rabbitmq: 
  enabled: false


filestore:
  backend: s3
  s3:
    existingSecret: sentry-s3
    accessKeyIdRef: ACCESS_KEY
    secretAccessKeyRef: SECRET_KEY
    endpointUrl: https://aws-endpoint-here
    bucketName: name-of-the-bucket

sentry:
  features:
    enableProfiling: true
    enableFeedback: true
    enableSessionReplay: true
    enableSpan: true

billingMetricsConsumer:
  enabled: true
```

### Helm chart version

26.5.0

### Steps to reproduce

- Have a project sending Profiling data
-  Can see data under Perforamance
- Cannot see data under Profiling

### Screenshots

<img width="1325" alt="Screenshot 2024-11-11 at 20 04 23" src="https://github.com/user-attachments/assets/2c2787d9-614e-493d-8003-e212e49c87cf">
<img width="865" alt="Screenshot 2024-11-11 at 20 05 35" src="https://github.com/user-attachments/assets/42641da2-438b-46fe-8034-600898be4236">
