### ISSUE TITLE
External kafka configuration does not trigger a provisioning

### ISSUE THREAD

**Issue by bmassemin** [sentry-kubernetes/charts#1603]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Consumers complain about missing topics.

### Expected behavior

The pod for kafka provisioning is not deployed as it is with `kafka.enabled: true`

### values.yaml

```
    externalKafka:
      host: "redpanda-0.redpanda.sentry.svc.cluster.local."
      port: 9093
      sasl:
        mechanism: SCRAM-SHA-512
        username: user
        password: password
      security:
        protocol: SASL_PLAINTEXT
    kafka:
      enabled: false
      provisioning:
        enabled: true
```

### Helm chart version

26.5.0

### Steps to reproduce

- deploy and external kafka
- use my config
- wait for deployment, no kafka provisioning is running

### Additional context

Provisioning is not evaluated in the template if `kafka.enabled: false`: https://github.com/sentry-kubernetes/charts/blob/9e95d7b1b18a39b0017355bacce58c2b27655528/charts/sentry/templates/snuba/_helper-snuba.tpl#L13-L24
