### ISSUE TITLE
why is the lag of group="generic-metrics-consumer", topic="events" growing?

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1612]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Hello! i have sentry with growing lag group="generic-metrics-consumer", topic="events"
Why is the lag of group="generic-metrics-consumer", topic="events" growing?
How troubleshoot this issue?

### Expected behavior

no lag

### values.yaml

```
    asHook: true
    user:
      create: true
      email: admin@sentry.dev.corp
    system:
      url: "https://sentry-backend.dev.corp"
    global:
      nodeSelector:
        role: sentry
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "sentry"
          effect: "NoSchedule"
    mail: {}
    nginx:
      enabled: false
    ingress:
      enabled: true
      hostname: sentry-backend.dev.corp
      ingressClassName: "nginx"
      regexPathStyle: nginx
      annotations:
        cert-manager.io/cluster-issuer: "cluster-issuer"
        nginx.ingress.kubernetes.io/proxy-body-size: 200m
        # https://github.com/getsentry/self-hosted/issues/1927
        nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
      tls:
        - hosts:
            - sentry-backend.dev.corp
          secretName: sentry-backend-tls
    filestore:
      backend: "s3"
      s3:
        region_name: ru-central1
        bucketName: sentry-backend-filestore-web
        endpointUrl: "https://storage.yandexcloud.net"
        location: "sentry-backend-filestore"
    postgresql:
      enabled: false
    externalPostgresql:
      host: externalPostgresql-host
      port: 6432
      username: sentry_backend
      database: sentry_backend
    rabbitmq:
      ## If disabled, Redis will be used instead as the broker.
      enabled: true
      replicaCount: 3
      global:
        storageClass: yc-network-ssd
      pdb:
        create: true
        minAvailable: 2
      persistence:
        enabled: true
        size: 30Gi
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests:
          cpu: 1000m
          memory: 1000Mi
      memoryHighWatermark:
        enabled: true
        type: relative
        value: 0.9
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          path: "/metrics/per-object"
          metricRelabelings:
            - sourceLabels: [queue]
              regex: ".*.celery.pidbox"
              action: drop
    redis:
      enabled: false
    externalRedis:
      host: externalRedis-host
      port: 6379
    externalKafka:
      cluster:
        - host: externalKafka-host1
          port: 9092
        - host: externalKafka-host2
          port: 9092
        - host: externalKafka-host3
          port: 9092
      sasl:
        mechanism: SCRAM-SHA-512
        username: sentry
      security:
        protocol: SASL_PLAINTEXT
    kafka:
      enabled: false
    zookeeper:
      enabled: false
    clickhouse:
      enabled: false
    externalClickhouse:
      host: externalClickhouse-host
      database: sentry
      httpPort: 8123
      tcpPort: 9000
      username: sentry
    metrics:
      enabled: true
      # Enable this if you're using https://github.com/coreos/prometheus-operator
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          memory: 256Mi
    sentry:
      features:
        enableProfiling: true
      ingestReplayRecordings:
        enabled: false
      subscriptionConsumerEvents: # topic events-subscription-results
        enabled: false
      subscriptionConsumerGenericMetrics: # topic generic-metrics-subscription-results
        enabled: false
      subscriptionConsumerMetrics: # topic metrics-subscription-results
        enabled: false
      subscriptionConsumerSessions:
        enabled: false
      subscriptionConsumerTransactions: # topic transactions-subscription-results
        enabled: false
      cleanup:
        activeDeadlineSeconds: 1800
        days: 14
      web:
        enabled: true
        replicas: 2
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 1Gi
      worker:
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 500m
            memory: 800Mi
          limits:
            memory: 2Gi
      workerEvents:
        enabled: true
        replicas: 10
        resources:
          requests:
            cpu: 1000m
            memory: 1500Mi
      workerTransactions:
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 400m
            memory: 1500Mi
      ingestConsumerAttachments: # topic ingest-attachments
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 300m
            memory: 700Mi
      ingestConsumerEvents: # topic ingest-events
        enabled: true
        replicas: 10
        resources:
          requests:
            cpu: 550m
            memory: 500Mi
      ingestConsumerTransactions: # topic ingest-transactions
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
      ingestProfiles: # topic profiles
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
      ingestOccurrences: # topic ingest-occurrences
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
      ingestMonitors: # topic ingest-monitors
        enabled: true
        replicas: 2
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 512Mi
      billingMetricsConsumer: # topic snuba-generic-metrics
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
      genericMetricsConsumer: # topic ingest-performance-metrics group generic-metrics-consumer
        enabled: true
        replicas: 2
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            memory: 1000Mi
      metricsConsumer: # topic ingest-metrics
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 300m
            memory: 600Mi
          limits:
            memory: 1000Mi
      cron:
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 1000m
            memory: 700Mi
      postProcessForwardErrors: # topic events
        enabled: true
        replicas: 10
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      postProcessForwardTransactions: # topic transactions
        enabled: true
        replicas: 2
        resources:
          requests:
            cpu: 600m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      postProcessForwardIssuePlatform: # topic generic-events
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
    snuba:
      replaysConsumer: # ingest-replay-events
        enabled: false
      genericMetricsCountersConsumer: # topic snuba-generic-metrics
        enabled: true
      genericMetricsDistributionConsumer: # topic snuba-generic-metrics
        enabled: false
      genericMetricsSetsConsumer: # snuba-generic-metrics
        enabled: false
      metricsConsumer: # snuba-metrics
        enabled: true
      api:
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            memory: 1Gi
      consumer: # topic events
        enabled: true
        replicas: 10
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 512Mi
      outcomesConsumer: # topic outcomes
        enabled: true
        replicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 512Mi
      outcomesBillingConsumer: # topic outcomes-billing
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
      replacer: # topic event-replacements
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      subscriptionConsumerEvents: # topic snuba-commit-log
        enabled: false
      subscriptionConsumerMetrics: # topic snuba-metrics-commit-log
        enabled: false
      subscriptionConsumerTransactions: # topic snuba-transactions-commit-log
        enabled: false
      subscriptionConsumerSessions:
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      sessionsConsumer:
        replicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      transactionsConsumer: # topic transactions
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      profilingProfilesConsumer:
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
      profilingFunctionsConsumer:
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
      issueOccurrenceConsumer: # topic generic-events
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      spansConsumer: # topic snuba-spans
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
      groupAttributesConsumer: # topic group-attributes
        enabled: true
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
    symbolicator:
      enabled: true
      api:
        usedeployment: false  # Set true to use Deployment, false for StatefulSet
        persistence:
          size: "40Gi"
        replicas: 1
    sourcemaps:
      enabled: true
    vroom:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
    relay:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
      resources:
        requests:
          cpu: 500m
          memory: 300Mi
        limits:
          memory: 1Gi
    hooks:
      snubaInit:
        kafka:
          enabled: false

```

### Helm chart version

26.6.0

### Steps to reproduce

helm install -n test --wait sentry . --values values.yaml --timeout=1000s

### Screenshots

![image](https://github.com/user-attachments/assets/9f251a3f-dce2-46af-922a-7fd2c0a2e484)
