### ISSUE TITLE
sentry 24.11.2: Snuba requires minimum Clickhouse version 23.8.11.29

### ISSUE THREAD

**Issue by fcuello-fudo** [sentry-kubernetes/charts#1636]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Trying to upgrade to sentry 24.11.2 fails with all snuba deploys entering a crash loop

### Expected behavior

Not crashing

### values.yaml

```
     images:
       sentry:
         tag: 24.11.2
       snuba:
         tag: 24.11.2
       relay:
         tag: 24.11.2
       symbolicator:
         tag: 24.11.2
       vroom:
         tag: 24.11.2
```

### Helm chart version

26.9.0

### Steps to reproduce

Deploy helmchart using the values above
