### ISSUE TITLE
Unable to complete sentry helm fresh install

### ISSUE THREAD

**Issue by dmuralibabu** [sentry-kubernetes/charts#1658]
Hi Team,

I tried to do sentry fresh install with helm and able to see all the pvc created by helm are in pending state.

```$ k get pvc -n sentry-new
NAME                                         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
data-sentry-kafka-controller-0               Pending                                      standard       <unset>                 14m
data-sentry-kafka-controller-1               Pending                                      standard       <unset>                 14m
data-sentry-kafka-controller-2               Pending                                      standard       <unset>                 14m
data-sentry-sentry-postgresql-0              Pending                                                     <unset>                 14m
data-sentry-zookeeper-clickhouse-0           Pending                                      standard       <unset>                 14m
redis-data-sentry-sentry-redis-master-0      Pending                                                     <unset>                 14m
redis-data-sentry-sentry-redis-replicas-0    Pending                                                     <unset>                 14m
sentry-clickhouse-data-sentry-clickhouse-0   Pending                                                     <unset>                 14m
sentry-data                                  Pending                                                     <unset>                 14m
```

My values.yaml file is:

```
user:
  create: true
  email: sentryadmin-local@example.com
  password: "xxx"
ingress:
  enabled: true
  regexPathStyle: nginx
  alb:
    httpRedirect: false
  hostname: sentry.app.example.com
postgresql:
  enabled: true
  persistence:
    storageClass: "standard"
rabbitmq:
  enabled: false
hooks:
  activeDeadlineSeconds: 10000

kafka:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "750m"
      memory: "2Gi"
  extraConfig: |-
      log.retention.ms=10000000
  controller:
     replicaCount: 3
     resources:
        requestes:
        cpu: "500m"
        memory: "1Gi"
     limits:
        cpu: "700m"
        memory: "2Gi"
     persistence:
        size: "1Gi"
        storageClass: "standard"
zookeeper:
  enabled: true
  persistence:
     storageClass: "standard"

clickhouse:
  enabled: true
  persistence:
     storageClass: "standard"

redis:
  enabled: true
  persistence:
     storageClass: "standard"


sentry:
   cleanup:
     days: 30


filestore:
    persistence:
      storageClass: "standard"
```

I already created pv in the namespace:

```# k get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
sentry-pv   10Gi       RWO            Retain           Bound    sentry/sentry-data   standard       <unset>```
