### ISSUE TITLE
Sentry helm externalKafka SSL config

### ISSUE THREAD

**Issue by kalan89** [sentry-kubernetes/charts#1659]
Hi Sentry Team,

When trying to configure the sentry fresh installation with externalKafka SSL.
Getting below error and no options exist to enable SSL Cert/key on helm values.yaml.

Values.yaml:
```
# Disable the in-cluster Kafka
kafka:
  enabled: false

# Configure external Kafka
externalKafka:
  host: data-test1.example.com
  port: 32500
  enabled: true
  security:
    protocol: SSL
```

Error:
```
%6|1736793971.761|FAIL|rdkafka#producer-46| [thrd:data-test1.example.com:32500/bootstrap]: data-test1.example.com:32500/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 36ms in state APIVERSION_QUERY, 1 identical error(s) suppressed)
```

Please share if we can enable cert and key on helm values.yaml or other workaround.

**Comment by kalan89** [comment]
When using the backend node as externalKafaka host, getting below error.

Let me know to kafka SSL location `ssl.ca.location` in the chart values.yaml file.



```
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2025-01-16 16:58:16,630 Attempting to connect to Kafka (attempt 24)...
%3|1737046696.813|FAIL|rdkafka#producer-25| [thrd:ssl://kafka.example.com:9093/bootstrap]: ssl://kafka.example.com:9093/bootstrap: SSL handshake failed: ssl/statem/statem_clnt.c:1890:tls_post_process_server_certificate error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 85ms in state SSL_HANDSHAKE)
%3|1737046696.998|FAIL|rdkafka#producer-25| [thrd:ssl://kafka.example.com:9093/bootstrap]: ssl://kafka.example.com:9093/bootstrap: SSL handshake failed: ssl/statem/statem_clnt.c:1890:tls_post_process_server_certificate error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 94ms in state SSL_HANDSHAKE, 1 identical error(s) suppressed)
2025-01-16 16:58:17,647 Connection to Kafka failed (attempt 24)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 72, in bootstrap
```

**Comment by patsevanton** [comment]
my config:
```
    externalKafka:
      cluster:
        - host: rc1a-xxx.mdb.cloud.net.
          port: 9092
        - host: rc1b-xxx.mdb.cloud.net.
          port: 9092
        - host: rc1d-xxx.mdb.cloud.net.
          port: 9092
      sasl:
        mechanism: SCRAM-SHA-512
        username: sentry
      security:
        protocol: SASL_PLAINTEXT
```

**Comment by kalan89** [comment]
> my config:
> 
> ```
>     externalKafka:
>       cluster:
>         - host: rc1a-xxx.mdb.cloud.net.
>           port: 9092
>         - host: rc1b-xxx.mdb.cloud.net.
>           port: 9092
>         - host: rc1d-xxx.mdb.cloud.net.
>           port: 9092
>       sasl:
>         mechanism: SCRAM-SHA-512
>         username: sentry
>       security:
>         protocol: SASL_PLAINTEXT
> ```

Thanks for your response.
I am trying to use kafa SSL with cert and key.
It looks like you are using SASL.

**Comment by Cheunn-Panaa** [comment]
You can use a sketchy workaround, as there is no other way you can set this up in the `externalKafka` part of the `values.yml` file.

```yaml
config:
  configYml: {}
  sentryConfPy: |
      KAFKA_CLUSTERS["default"] = {
      "common": {
          # See https://github.com/getsentry/arroyo/blob/main/arroyo/backends/kafka/configuration.py#L16-L38 for the supported options
          "bootstrap.servers": "$KAFKA_HOST:$KAFKA_PORT",
          "ssl.ca.location": "/usr/local/share/ca-certificates/cert.pem",
          # If you need cert + key for users
          # "ssl.certificate.location": os.environ.get("KAFKA_SSL_CERT_PATH", ""),
          # "ssl.key.location": os.environ.get("KAFKA_SSL_KEY_PATH", ""),
          "security.protocol": "SASL_SSL",
          "sasl.mechanism": "PLAIN",
          "sasl.username": "$KAFKA_USER_NAME",
          "sasl.password": "$KAFKA_USER_OPS",
        }
      }
  snubaSettingsPy: |
    BROKER_CONFIG: Mapping[str, Any] = {
      # See https://github.com/getsentry/arroyo/blob/main/arroyo/backends/kafka/configuration.py#L16-L38 for the supported options
          "bootstrap.servers": "$KAFKA_HOST:$KAFKA_PORT",
          "ssl.ca.location": "/usr/local/share/ca-certificates/cert.pem",
          # If you need cert + key for users
          # "ssl.certificate.location": os.environ.get("KAFKA_SSL_CERT_PATH", ""),
          # "ssl.key.location": os.environ.get("KAFKA_SSL_KEY_PATH", ""),
          "security.protocol": "SASL_SSL",
          "sasl.mechanism": "PLAIN",
          "sasl.username": "$KAFKA_USER_NAME",
          "sasl.password": "$KAFKA_USER_OPS",
    }
```

I had to dig up in the [snuba](https://github.com/getsentry/snuba/tree/master) and [sentry](https://github.com/getsentry/self-hosted/tree/master/sentry) configuration to find what i needed. (also in the helm helpers)


This configuration works for me but i only hit a single server, you might be able to adjust it with some more digging [sentry_helper](https://github.com/sentry-kubernetes/charts/blob/develop/charts/sentry/templates/sentry/_helper-sentry.tpl).


For the maintainers maybe adding something like (sadly i dont have the time to contribute)

```yaml
kafka:
  ssl:
    ca:
      secret: my-ca-cert-secret
      path: '/usr/local/share/cert.pem'
```


```yaml
      {{- $sentryKafkaSslCaPath := include "sentry.kafka.ssl.ca.path" .}}
      {{- if $sentryKafkaSslCaPath) }}
          "ssl.ca.location": {{ $sentryKafkaSslCaPath | quote}},
      {{- end }}
```

```yaml
        {{- $sentryKafkaSslCaPath := include "sentry.kafka.ssl.ca.path" .}}
        {{- if $sentryKafkaSslCaPath) }}
        - name: my-ca-cert-secret
          mountPath: $sentryKafkaSslCaPath
        {{ end }}
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by patsevanton** [comment]
@Cheunn-Panaa can you share you code ?

**Comment by alistairmaclean** [comment]
In order to use a Kafka with a custom CA there is a considerable amount of configuration that has to be done manually.

1. Deploy a custom-ca secret object
2. Use the custom-ca secret object in all pods

Example values.yaml configuration:
```yaml
  sentry:
    billingMetricsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    genericMetricsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestConsumerAttachments:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestConsumerEvents:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestConsumerTransactions:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestMonitors:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestOccurrences:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    ingestReplayRecordings:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    metricsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    postProcessForwardErrors:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
    postProcessForwardIssuePlatform:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    postProcessForwardTransactions:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    processSegments:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    processSpans:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerEvents:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerGenericMetrics:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerMetrics:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerResultsEapItems:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerTransactions:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    uptimeResults:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    worker:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
  snuba:
    migrateJob:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
    issueOccurrenceConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    eapItemsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerEapItems:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerEvents:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerGenericMetricsCounters:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerGenericMetricsDistributions:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerGenericMetricsGauges:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerGenericMetricsSets:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerMetrics:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    subscriptionConsumerTransactions:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    transactionsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    uptimeResultsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    spansConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    replaysConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    replacer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    outcomesConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    outcomesBillingConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    metricsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    groupAttributesConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    genericMetricsSetsConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    genericMetricsGaugesConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    genericMetricsDistributionConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    genericMetricsCountersConsumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    consumer:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
    api:
      env:
        - name: KAFKA_SSL_CA_PATH
          value: /etc/kafka/ca/ca.crt
      volumes:
        - name: custom-ca
          secret:
            secretName: custom-ca
      volumeMounts:
        - name: custom-ca
          mountPath: /etc/kafka/ca
  relay:
    processing:
      additionalKafkaConfig:
      - name: ssl.ca.location
        value: /etc/kafka/ca/ca.crt
    volumes:
      - name: custom-ca
        secret:
          secretName: custom-ca
    volumeMounts:
      - name: custom-ca
        mountPath: /etc/kafka/ca
  config:
    sentryConfPy: |
      KAFKA_CLUSTERS["default"]["common"]["ssl.ca.location"] = env("KAFKA_SSL_CA_PATH")
```

Ideally, the Kafka `ssl.ca.location` configuration should be configurable with a single property in values.yaml
