### ISSUE TITLE
Noticeable increased on DB CPU after upgrade to 26.14.0

### ISSUE THREAD

**Issue by x-504** [sentry-kubernetes/charts#1702]
### Issue submitter TODO list

- [x] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

After upgrading the helm chart from `26.10.0` to `26.14.0` a noticeable increase in the Postgres CPU DB.

### Expected behavior

Do not spike in DB CPU usage after upgrade.

### values.yaml

```
sentry:
  system:
    url: REDACTED

  user:
    create: true
    email: REDACTED

    asHook: false

  config:
    web:
      maxWorkerLifetime: 0

  mail:
    backend: smtp
    useSsl: true
    existingSecret: mail-password
    port: REDACTED
    host: REDACTED
    from: REDACTED
    username:REDACTED

  nginx:
    enabled: false

  service:
    type: NodePort

  postgresql:
    enabled: false

  externalPostgresql:
    host: REDACTED
    port: 5432
    username: REDACTED
    existingSecret: REDACTED
    existingSecretKey: REDACTED
    database: sentry
    sslMode: require

  rabbitmq:
    enabled: false

  clickhouse:
    clickhouse:
      replicas: 2
      persistentVolumeClaim:
        enabled: true
        dataPersistentVolume:
          enabled: true
          storage: "500Gi"

  zookeeper:
    replicaCount: 3
    autopurge:
      snapRetainCount: 10
      purgeInterval: 1

  kafka:
    controller:
      resourcesPreset: "xlarge"
      size: 100Gi
    extraConfig: |
      log.retention.hours=24

  redis:
    replica:
      replicaCount: 3


  sentry:
    cleanup:
      successfulJobsHistoryLimit: 5
      failedJobsHistoryLimit: 5
      activeDeadlineSeconds: 600
      concurrencyPolicy: Allow
      concurrency: 1
      enabled: true
      schedule: "0 0 * * *"
      days: 20
    web:
      replicas: 1
      strategyType: RollingUpdate
    worker:
      replicas: 3
    ingestConsumerEvents:
      replicas: 3
      concurrency: 4

  metrics:
    enabled: false

  filestore:
    backend: s3
    s3:
      bucketName: REDACTED
      region_name: REDACTED
      existingSecret: REDACTED
      existingSecretAccessKey: REDACTED
      existingSecretSecretKey: REDACTED

  symbolicator:
    enabled: true
    api:
  github:
    appId: REDACTED
    appName: REDACTED
    existingSecret: REDACTED
    existingSecretClientIdKey: REDACTED
    existingSecretClientSecretKey: REDACTED
    existingSecretPrivateKeyKey: REDACTED
    existingSecretWebhookSecretKey: REDACTED
  slack:
    clientId: REDACTED
    clientSecret: REDACTED
    signingSecret: REDACTED

```

### Helm chart version

26.14.0

### Steps to reproduce

Upgrade helm chart to 26.14.0

### Screenshots

![Image](https://github.com/user-attachments/assets/699f636c-bf65-4138-aaf8-69f92ce212d5)
