### ISSUE TITLE
Helm installation broken

### ISSUE THREAD

**Issue by docimin** [sentry-kubernetes/charts#1728]
### Issue submitter TODO list

- [x] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

When installing, I keep getting errors in the postgresql & web pods
Installation seems to be broken because of it, doesn't start without a fix.

### values.yaml

Default

### Helm chart version

sentry:26.15.1

### Steps to reproduce

Install sentry/sentry helm chart by following the readme.

### Screenshots

![Image](https://github.com/user-attachments/assets/5571db4a-7cf8-4f72-8535-1ac1ac1bd702)

![Image](https://github.com/user-attachments/assets/f5ff541d-1ef8-4523-9472-78ce6fbfaf73)

### Logs

```
2025-03-11 17:23:00.192 GMT [862] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'transaction-events.force-disable-internal-project' LIMIT 21
```
and
```
psycopg2.errors.UndefinedTable: UndefinedTable('relation "sentry_projectkey" does not exist\nLINE 1: ...tkey"."data", "sentry_projectkey"."use_case" FROM "sentry_pr...\n                                                             ^\n')
SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data", "sentry_projectkey"."use_case" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s AND "sentry_projectkey"."roles" = ("sentry_projectkey"."roles" | %s) AND "sentry_projectkey"."use_case" = %s)
```

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by jmealo** [comment]
@docimin Did you find a fix for this?
@Mokto: I'm having the same issue, even though I set the timeout to 15 minutes. I never see any tables get connected with Postgres. I've triple checked my connection info.

```yaml
# Disable the built-in PostgreSQL
postgresql:
  enabled: false

# Configure external PostgreSQL
externalPostgresql:
  host: staging-pg-common-pooler-rw.db.svc.cluster.local
  username: sentry
  password: <redacted>
  database: sentry
  port: 5432

# I added this because the migrations weren't running - to no effect
asHook: true

# I added this because the migrations weren't running - to no effect
hooks:
  enabled: true
  dbInit:
    enabled: true

global:
  user:
    create: true
    email: <redacted>
    password: <redacted>

ingress:
  enabled: false

service:
  annotations: {}
  externalPort: 9000
  name: sentry
  type: ClusterIP
```

**Comment by jmealo** [comment]
When I try to use the built-in Postgres. `sentry-worker` is unable to connect using the `postgres` user (password authentication fails).

**Comment by docimin** [comment]
Hey @jmealo, I did not and still require a fix.

**Comment by byrnedo** [comment]
Also experiencing the issue with the database not being set up correctly

**Comment by jmealo** [comment]
@byrnedo @docimin: I opened a new ticket, I thought it might be limited to Azure AKS. #1747

**Comment by jmealo** [comment]
@byrnedo @docimin: Are we trying to use the internal database or an external one? I'm happy to turn on connection logging to verify if an attempt is even being made. I triple checked that I could connect to the database using the provided credentials from inside one of the pods and it worked fine.

Did either of you try the `hook` bits I added in my values (posted in #1747).

**Comment by docimin** [comment]
> [@byrnedo](https://github.com/byrnedo) [@docimin](https://github.com/docimin): Are we trying to use the internal database or an external one? I'm happy to turn on connection logging to verify if an attempt is even being made. I triple checked that I could connect to the database using the provided credentials from inside one of the pods and it worked fine.
> 
> Did either of you try the `hook` bits I added in my values (posted in [#1747](https://github.com/sentry-kubernetes/charts/issues/1747)).

Keep in mind that I tried to use the completely default helm chart, everything mostly how it was and only change things like the login.

Only thing I changed was the default user/pass for sentry itself.

**Comment by jmealo** [comment]
@docimin: Are you using managed k8s on a cloud provider (if so who?) Thanks for the quick reply.

I also cannot get the "default" chart to deploy.

I'm trying to see if there's any open PRs that could be related to this:
https://github.com/sentry-kubernetes/charts/pull/1704

I saw someone else who never had the database migrations run and they had an issue with hooks running.

**Comment by docimin** [comment]
> [@docimin](https://github.com/docimin): Are you using managed k8s on a cloud provider (if so who?) Thanks for the quick reply.
> 
> I also cannot get the "default" chart to deploy.
> 
> I'm trying to see if there's any open PRs that could be related to this: [#1704](https://github.com/sentry-kubernetes/charts/pull/1704)
> 
> I saw someone else who never had the database migrations run and they had an issue with hooks running.

I'm using Rancher with RKE2 cluster. Self hosted.

**Comment by byrnedo** [comment]
> @byrnedo @docimin: Are we trying to use the internal database or an external one? I'm happy to turn on connection logging to verify if an attempt is even being made. I triple checked that I could connect to the database using the provided credentials from inside one of the pods and it worked fine.
> 
> Did either of you try the `hook` bits I added in my values (posted in #1747).

I'm using the defaults, so Postgres internal I guess. FWIW the first time I installed the chart in my ns it worked, then I wanted to change the ingress host, so reinstalled, and then the issue appeared. I've deleted the ns and all and still the same.

I haven't tried the hooks.

**Comment by jmealo** [comment]
Dang, I was hoping it was due to service accounts and the db init hooks, because there's two open/unmerged PRs with fixes:
- https://github.com/sentry-kubernetes/charts/pull/1102
- https://github.com/sentry-kubernetes/charts/pull/1704

I wonder if there's a way to manually run the migrations to verify that's the only issue here.

I'm going to try to reproduce on k3s locally.

**Comment by byrnedo** [comment]
Also using rancher, also self hosted, also migrations not running.

**Comment by jmealo** [comment]
I was unable to test locally, arm64 images aren't available, I tried to override platform but it didn't work:
```yaml
images:
  sentry:
    platform: linux/amd64
  snuba:
    platform: linux/amd64
  relay:
    platform: linux/amd64
  symbolicator:
    platform: linux/amd64
  vroom:
    platform: linux/amd64
```

```
sentry-clickhouse-0                 0/1     ContainerCreating   0          1s
sentry-cron-5cc58f95f8-rs854        0/1     ErrImagePull        0          7s
sentry-kafka-controller-0           0/1     Running             0          7s
sentry-kafka-controller-1           0/1     Running             0          7s
sentry-kafka-controller-2           0/1     PodInitializing     0          2s
sentry-nginx-797b94b8b-xhlqc        0/1     Running             0          7s
sentry-rabbitmq-0                   1/1     Terminating         0          2m32s
sentry-sentry-postgresql-0          0/1     Running             0          7s
sentry-sentry-redis-master-0        0/1     Running             0          7s
sentry-sentry-redis-replicas-0      0/1     Running             0          7s
sentry-snuba-api-844cc6b959-4xk25   0/1     ErrImagePull        0          7s
sentry-web-55f5d48d7b-bkskb         0/1     ErrImagePull        0          7s
sentry-worker-7fd7d5684c-rhjw2      0/1     ErrImagePull        0          7s
sentry-zookeeper-clickhouse-0       1/1     Running             0          7s
```
