### ISSUE TITLE
Kafka-Controller Cannot reserve x bytes of direct buffer memory

### ISSUE THREAD

**Issue by Dentling** [sentry-kubernetes/charts#1733]
### Issue submitter TODO list

- [x] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

Some type after deploying the kafka-controllers, all of them get the following error:

```
[2025-03-20 08:04:15,034] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.OutOfMemoryError: Cannot reserve 369295617 bytes of direct buffer memory (allocated: 1866930914, limit: 2147483648)
```

I already had this issue with the default 1G and increased the Java-Memory to 2G via the `heapOpts`-Field in the values.yaml but it seems like it doesnt't matter how much I give it.

This leads to unavailability of the cluster for the consumers which then leads to restarts of the consumers.

### Expected behavior

Not causing restarts

### values.yaml

```
kafka:
  extraConfigYaml:
    log.cleanup.policy: delete
    log.retention.hours: 24
    socket.request.max.bytes: 500000000
  provisioning:
    enabled: true
  controller:
    heapOpts: "-Xmx2G -Xms2G"
    resourcesPreset: xlarge
```

### Helm chart version

26.15.1

### Steps to reproduce

Deploy the Helm-Chart and wait about 12 hours

### Logs

Log from one of the consumers that crashed

```
cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Commit failed: Local: Timed out"}
Producer terminating with 2 messages (303 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```
