### ISSUE TITLE
[feature request] support sentry 20.9.0

### ISSUE THREAD

**Issue by nsyujian** [sentry-kubernetes/charts#174]
20.9.0 fix Worker / celery stops working

https://github.com/getsentry/onpremise/issues/629

**Comment by Mokto** [comment]
People seem to have issues with Redis specifically ?
I'm trying 20.9.0 with RabbitMQ right now, let's see ;)

**Comment by Mokto** [comment]
Currently the 20.9.0 has 2 issues :
- Releases is displaying : "You do not have access to this feature"
- Alerts is crashing : 

```
Unable to load all required endpoints: /organizations/:orgId/alerts/rules/
UndefinedTable('relation "sentry_ruleactivity" does not exist\nLINE 1: ...er"."date_joined", "auth_user"."last_active" FROM "sentry_ru...\n ^\n',) SQL: SELECT "sen
```

**Comment by nsyujian** [comment]
We have upgraded to 20.9.0,  need update relay config
```yaml
data:
  config.yml: |-
    relay:
      mode: managed # need remove
      upstream: "http://{{ template "sentry.fullname" . }}-web:{{ template "sentry.port" }}/"
      host: 0.0.0.0
      port: {{ template "relay.port" }}
```
