### ISSUE TITLE
Trace view does not work

### ISSUE THREAD

**Issue by inakimalerba** [sentry-kubernetes/charts#1745]
Hello !

We migrated from the cloud version to a self-hosted instance provisioned using this chart, but we are having troubles enabling the "trace view" features.

Helm chart version: 26.16.0

<details>
<summary>values.yml</summary>

```
---
system:
  url: "https://sentry.myorg"

user:
  create: true
  email: admin@myorg
  password: default-change-me

filestore:
  backend: s3
  s3:
    existingSecret: sentry-credentials
    bucketName: sentry
    endpointUrl: https://minio.myorg
    signature_version: v4
    region_name: us-east-1

ingress:
  hostname: sentry.myorg
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "myorg-k8s-ca"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
  tls:
    - secretName: sentry-tls
      hosts:
        - sentry.myorg

hooks:
  dbInit:
    enabled: true
  snubaInit:
    enabled: true

mail:
  backend: smtp
  useTls: true
  username: "smtp@myorg"
  existingSecret: sentry-credentials
  port: 587
  host: "smtp.gmail.com"
  from: "Sentry"

sentry:
  features:
    enableProfiling: true
  customFeatures:
    - organizations:trace-view-v1
    - organizations:replay-trace-view-v1
    - organizations:trace-drawer-action
    - organizations:trace-spans-format
    - organizations:performance-new-widget-designs
    - organizations:performance-span-histogram-view
    - organizations:performance-spans-new-ui
    - organizations:performance-use-metrics
    - organizations:performance-trace-details
    - organizations:performance-trace-explorer
    - organizations:performance-trace-explorer-sorting
    - organizations:performance-tracing-without-performance
    - organizations:transaction-metrics-extraction
    - organizations:anomaly-detection-eap
    - organizations:dashboards-eap
    - organizations:insights-use-eap
    - organizations:ingest-spans-in-eap
    - projects:use-eap-spans-for-metrics-explorer
    - organizations:indexed-spans-extraction
    - organizations:visibility-explore-view
    - organizations:visibility-explore-admin
    - organizations:visibility-explore-equations
    - organizations:visibility-explore-dataset
    - organizations:visibility-explore-rpc
    - organizations:visibility-explore-range-high
    - organizations:explore-multi-query

kafka:
  controller:
    resourcesPreset: "large"
```
</details>

The custom features were added based on the following comments:

- https://github.com/getsentry/self-hosted/issues/3272#issuecomment-2339539089
- https://github.com/getsentry/self-hosted/issues/3592#issuecomment-2731546545

The last link mentions a few extra containers required for this feature, maybe that's the issue? I couldn't understand exactly what `sentry.features.enableProfiling: true` covers.

Is there something wrong on our deployment or is this feature not yet supported?

Thanks!

## Expected

This is the previous behavior on sentry.io

![Image](https://github.com/user-attachments/assets/0db653aa-c19c-42be-aa90-f2e93283a435)
![Image](https://github.com/user-attachments/assets/086bf1a7-8035-46f2-a44d-c80b7cefccd5)

## Actual

This is what it looks like on the self hosted instance

![Image](https://github.com/user-attachments/assets/4bec2126-902d-43d9-8418-4edb470cc2d6)
![Image](https://github.com/user-attachments/assets/2ceb2e3e-639b-4cdc-9ba1-6dfb97588d1b)
