### ISSUE TITLE
Database migrations not running - Fresh deploy fails on three different Azure AKS 1.29.10 clusters

### ISSUE THREAD

**Issue by jmealo** [sentry-kubernetes/charts#1747]
### Issue submitter TODO list

- [x] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

- I'm trying to deploy with a minimal config.
- I've increased the timeout to 15 minutes.
- I've tried on 3 separate Azure subscriptions/K8s (AKS) clusters.
- Two other users report the same issue on Rancher #1728 

### Expected behavior

To deploy Sentry using helm to Azure AKS.

For when a deployment fails, for the jobs to be cleaned up (I understand PVCs are probably not deleted for data safety reasons):

**After deployment fails:**
```
➜  kubernetes git:(feat/ENG-3051) ✗ kubectl get jobs -n monitoring | grep sentry
sentry-db-check             1/1           4s         35m
sentry-kafka-provisioning   1/1           7m39s      35m
➜  kubernetes git:(feat/ENG-3051) ✗ kubectl get pvc -n monitoring | grep sentry
data-sentry-kafka-controller-0               Bound    pvc-7add6e99-37f0-4000-8d24-a7255a6ed5c0   8Gi        RWO            default               <unset>                 37m
data-sentry-kafka-controller-1               Bound    pvc-ef6de4fa-470c-43a4-96d0-97a80d00a692   8Gi        RWO            default               <unset>                 37m
data-sentry-kafka-controller-2               Bound    pvc-2a43f9f0-b85b-4e2c-8fc7-3ae4f213381f   8Gi        RWO            default               <unset>                 37m
data-sentry-rabbitmq-0                       Bound    pvc-587d6d5e-43ff-4e7f-a82f-5adf083eeb98   8Gi        RWO            default               <unset>                 37m
data-sentry-sentry-postgresql-0              Bound    pvc-6f18cec6-ea2e-4908-9225-50d0f72e8d1e   8Gi        RWO            default               <unset>                 37m
data-sentry-zookeeper-clickhouse-0           Bound    pvc-86ef1213-6263-4b60-b9e3-fd1eea852a97   8Gi        RWO            default               <unset>                 37m
redis-data-sentry-sentry-redis-master-0      Bound    pvc-236445a4-f95e-49e6-b179-f50491d123c4   8Gi        RWO            default               <unset>                 37m
redis-data-sentry-sentry-redis-replicas-0    Bound    pvc-78803ecf-1583-4a76-b2ca-0804c67954e0   8Gi        RWO            default               <unset>                 37m
sentry-clickhouse-data-sentry-clickhouse-0   Bound    pvc-270d6e63-e360-4028-95fe-a2dbeff987c7   30Gi       RWO            default               <unset>                 37m
```

```yaml
### values.yaml

#################################################################################
# I tried adding this part because when I used external postgres the migrations #
# were never run -- it did not help.                                            #
#################################################################################
asHook: true

hooks:
  enabled: true
  dbInit:
    enabled: true
  snubaInit:
    enabled: true

#################################################################################
# End portion of the above comment
################################################################################
global:
  user:
    create: true
    email: <redacted>
    password: <redacted>

ingress:
  enabled: false

service:
  annotations: {}
  externalPort: 9000
  name: sentry
  type: ClusterIP
```

### Helm chart version

26.16.0

### Steps to reproduce

Deploy using values.yaml with `--timeout=15m`

### Logs

➜  kubernetes git:(feat/ENG-3051) ✗ ./bin/deploy_app.sh -d applications/infrastructure/charts/sentry
Installing app infrastructure/charts/sentry into the demo cluster
Release "sentry" does not exist. Installing it now.
coalesce.go:237: warning: skipped value for kafka.config: Not a table.
Error: release sentry failed, and has been uninstalled due to atomic being set: failed post-install: 1 error occurred:
        * timed out waiting for the condition

exit 1

### Additional context

- I was never able to get the migrations to get applied to an external database.
- I switched to as vanilla config as I could and it always times out.
- Most of the pods are in a good/ready state, but I always see errors relating to the schema/tables not existing.
