### ISSUE TITLE
Question: Setting Zookeeper Resources

### ISSUE THREAD

**Issue by jwaldrip** [sentry-kubernetes/charts#1748]
How do you set the resources on zookeeper in the sentry chart?

**Comment by kiku99** [comment]
Hey there! I noticed you're trying to manage Zookeeper resources in the Sentry chart. I ran into the same issue and solved it by converting the Zookeeper dependency to a local subchart.

For the Chart.yaml modification, I simply did this:


```
dependencies:
  - name: zookeeper
    version: 11.4.11
    condition: zookeeper.enabled
```
I just removed the repository line that pointed to the external chart. This tells Helm to look for the Zookeeper chart directly in my local charts/ directory instead of downloading it from Bitnami.

If you want to be super explicit about it, you could also use:

`repository: "file://charts/zookeeper"`

But I found the simpler approach works fine! After making this change, I ran helm dependency update and then I could easily customize all the Zookeeper settings directly in my local copy.

Hope this helps!

**Comment by ivoistaken** [comment]
```yaml
...
zookeeper:
  resources:
    requests:
      cpu: 300m
      memory: 700Mi
...
```
