### ISSUE TITLE
Add symbolicator cleanup job to prevent PVC storage exhaustion

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#1768]
## Problem
The `sentry-symbolicator-api` PVC periodically runs out of storage space because there's no automated cleanup process in place. This causes service disruptions and requires manual intervention to free up disk space.

## Current Situation
- The symbolicator service accumulates cache and temporary files over time
- No automated cleanup mechanism is configured
- Storage exhaustion leads to service failures and downtime

## Proposed Solution
Implement a cleanup job similar to the one used in docker-compose deployments. The cleanup should run periodically (e.g., daily) to remove old cache files and maintain optimal storage usage.

## Reference Implementation
From the docker-compose setup, there's already a working cleanup mechanism:
```yaml
  symbolicator-cleanup:
    <<: *restart_policy
    image: symbolicator-cleanup-self-hosted-local
    build:
      context: ./cron
      args:
        BASE_IMAGE: "$SYMBOLICATOR_IMAGE"
    command: '"55 23 * * * gosu symbolicator symbolicator cleanup"'
    volumes:
      - "sentry-symbolicator:/data"
```
