### ISSUE TITLE
Support using external RabbitMQ and Memcached instances

### ISSUE THREAD

**Issue by drblack666** [sentry-kubernetes/charts#1773]
The Helm chart currently allows users to connect to external services like PostgreSQL and Redis by setting connection parameters in values.yaml, which is very useful in production setups where these services are managed separately.

It would be great to have similar support for external RabbitMQ and Memcached.

**Comment by billowqiu** [comment]
Currently rabbitmq is supported.

```
rabbitmq:
  ## If disabled, Redis will be used instead as the broker.
  enabled: true
  vhost: /
  clustering:
    forceBoot: true
    rebalance: true
  replicaCount: 1
  auth:
    erlangCookie: pHgpy3Q6adTskzAT6bLHCFqFTF7lMxhA
    username: guest
    password: guest
```
