### ISSUE TITLE
Sentry[5.3.0] - Unable to actually capture events

### ISSUE THREAD

**Issue by mariusmitrofanbostontr** [sentry-kubernetes/charts#196]
Hi,

I'm not sure if this is just me or if happening to everyone else, but my sentry installation is *NOT* able to capture any events.

I've noticed however that the following deployments, during `helm install` (with helm v3), cannot be installed during the actual install process, because they start *Before* the Kafka topic is up (through a job migration), hence are failing:

* sentry-relay
* sentry-sessions-consumer
* sentry-snuba-outcomes-consumer
* sentry-snuba-replacer

It's basically a chicken and the egg problem but I solved it by manually doing this during the install:

```
kubectl scale deployment sentry-relay -n sentry --replicas=0
kubectl scale deployment sentry-sessions-consumer -n sentry --replicas=0
kubectl scale deployment sentry-snuba-outcomes-consumer -n sentry --replicas=0
kubectl scale deployment sentry-snuba-replacer -n sentry --replicas=0
```

And then bringing them back up afterwards:

```
kubectl scale deployment sentry-relay -n sentry --replicas=1
kubectl scale deployment sentry-sessions-consumer -n sentry --replicas=1
kubectl scale deployment sentry-snuba-outcomes-consumer -n sentry --replicas=1
kubectl scale deployment sentry-snuba-replacer -n sentry --replicas=1
```

**NOW**, my real problem is this:

When generating a stupid exception from an application, the `sentry-relay` service throws for some reason a 403 when trying to connect to upstream, without any other explanation.

I don't know if these 2 are related, but I surely appreciate some help as this basically makes this helm chart unusable. Literally.

Thanks...

@Mokto would appreciate your input on this very much :( ...

**Comment by Mokto** [comment]
Can you share your values.yaml file with us ?

sentry-relay should be installed as a hook for the chicken&egg problem you were talking about.

**Comment by mariusmitrofanbostontr** [comment]
Sorry, here's the file ->


```
prefix:

user:
  create: true
  email: ${sentry_email_from}
  password: initialpassword

images:
  sentry:
    repository: ${sentry_image_repository}
    tag: ${sentry_image_tag}
    pullPolicy: Always
    imagePullSecrets: []
  snuba:
    # repository: getsentry/snuba
    # tag: Chart.AppVersion
    # pullPolicy: IfNotPresent
    imagePullSecrets: []
  relay:
    # repository: getsentry/relay
    # tag: Chart.AppVersion
    # pullPolicy: IfNotPresent
    imagePullSecrets: []

relay:
  replicas: 1
  env: []
  probeInitialDelaySeconds: 10
  resources: {}
  affinity: {}
  nodeSelector: {}
  # tolerations: []
  # podLabels: []

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

sentry:
  singleOrganization: true
  web:
    replicas: 1
    env: []
    probeInitialDelaySeconds: 10
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50

  worker:
    replicas: 3
    # concurrency: 4
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

    # it's better to use prometheus adapter and scale based on
    # the size of the rabbitmq queue
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50

  ingestConsumer:
    replicas: 1
    # concurrency: 4
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

    # it's better to use prometheus adapter and scale based on
    # the size of the rabbitmq queue
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 50

  cron:
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []
  postProcessForward:
    replicas: 1
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []
    # commitBatchSize: 1

snuba:
  api:
    replicas: 1
    env: []
    probeInitialDelaySeconds: 10
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 50

  consumer:
    replicas: 1
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

  outcomesConsumer:
    replicas: 1
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

  sessionsConsumer:
    replicas: 1
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

  transactionsConsumer:
    replicas: 1
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

  replacer:
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {}
    # tolerations: []
    # podLabels: []

  dbInitJob:
    env: []

  migrateJob:
    env: []

hooks:
  enabled: true
  dbInit:
    env: []
    resources:
      limits:
        memory: 2048Mi
      requests:
        cpu: 300m
        memory: 2048Mi
  snubaInit:
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
      requests:
        cpu: 700m
        memory: 1Gi
system:
  url: ""
  adminEmail: ""
  ## This should only be used if you’re installing Sentry behind your company’s firewall.
  public: false
  ## This will generate one for you (it's must be given upon updates)
  #secretKey: "xx"

mail:
  backend: "smtp"
  useTls: ${sentry_email_tls}
  username: ${sentry_email_user}
  password: ${sentry_email_password}
  port: ${sentry_email_port}
  host: ${sentry_email_host}
  from: ${sentry_email_from}

symbolicator:
  enabled: false

auth:
  register: true

service:
  name: sentry
  type: ClusterIP
  externalPort: 9000
  annotations: {}
  # externalIPs:
  # - 192.168.0.1
  # loadBalancerSourceRanges: []

github: {} # https://github.com/settings/apps (Create a Github App)
# github:
#   appId: "xxxx"
#   appName: MyAppName
#   clientId: "xxxxx"
#   clientSecret: "xxxxx"
#   privateKey: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpA" !!!! Don't forget a trailing \n
#   webhookSecret:  "xxxxx`"

githubSso: {} # https://github.com/settings/developers (Create a OAuth App)
  # clientId: "xx"
# clientSecret: "xx"

slack:
  clientId: "${sentry_slack_client_id}"
  clientSecret: "${sentry_slack_client_secret}"
  verificationToken: "${sentry_slack_verification_token}"
  # channels.* of Slack API is deprecated.
  # All new slack apps created after June 10th, 2020 will give error,
  # you need to specify `False` if you want to use the Slack App created after that.
  # ref : https://github.com/getsentry/sentry/pull/19446
  legacyApp: true

nginx:
  enabled: true
  containerPort: 8080
  existingServerBlockConfigmap: sentry-nginx
  resources: {}
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  hostname: ${sentry_hostname}
  annotations:
    kubernetes.io/ingress.class: traefik

  #
  # tls:
  # - secretName:
  #   hosts:

filestore:
  # Set to one of filesystem, gcs or s3 as supported by Sentry.
  backend: filesystem

  filesystem:
    path: /var/lib/sentry/files

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true
      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClass: "aws-efs"
      accessMode: ReadWriteMany
      size: 1Mi

      ## Whether to mount the persistent volume to the Sentry worker and
      ## cron deployments. This setting needs to be enabled for some advanced
      ## Sentry features, such as private source maps. If you disable this
      ## setting, the Sentry workers will not have access to artifacts you upload
      ## through the web deployment.
      ## Please note that you may need to change your accessMode to ReadWriteMany
      ## if you plan on having the web, worker and cron deployments run on
      ## different nodes.
      persistentWorkers: true

  ## Point this at a pre-configured secret containing a service account. The resulting
  ## secret will be mounted at /var/run/secrets/google
  gcs:
  # credentialsFile: credentials.json
  #  secretName:
  #  bucketName:

  ## Currently unconfigured and changing this has no impact on the template configuration.
  s3: {}
  #  accessKey:
  #  secretKey:
  #  bucketName:
  #  endpointUrl:
  #  signature_version:
  #  region_name:
  #  default_acl:

config:
  configYml: |
    # Nothing extra
  sentryConfPy: |
    # Nothing extra
  snubaSettingsPy: |
    # No Python Extension Config Given
  relay: |
    # No YAML relay config given

clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "19.17"
    configmap:
      remote_servers:
        internal_replication: true
    persistentVolumeClaim:
      enabled: true
      dataPersistentVolume:
        enabled: true
        accessModes:
          - "ReadWriteOnce"
        storage: "1Mi"
        storageClassName: "aws-efs"
        storageClass: "aws-efs"

## This value is only used when clickhouse.enabled is set to false
##
externalClickhouse:
  ## Hostname or ip address of external clickhouse
  ##
  host: "clickhouse"
  tcpPort: 9000
  ## Cluster name, can be found in config
  ## (https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#server-settings-remote-servers)
  ## or by executing `select * from system.clusters`
  ##
  # clusterName: test_shard_localhost

kafka:
  enabled: true
  replicaCount: 3
  allowPlaintextListener: true
  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  transactionStateLogReplicationFactor: 3
  transactionStateLogMinIsr: 3
  persistence:
    enabled: true
    accessModes:
      - "ReadWriteOnce"
    storage: "1Mi"
    storageClassName: "aws-efs"
    storageClass: "aws-efs"

  service:
    port: 9092

  zookeeper:
    enabled: true
    auth:
      enabled: false
    persistence:
      enabled: true
      storageClass: "aws-efs"
      storageClassName: "aws-efs"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      annotations: { }
      dataLogDir:
        size: 8Gi


## This value is only used when kafka.enabled is set to false
##
externalKafka:
  ## Hostname or ip address of external kafka
  ##
  # host: "kafka-confluent"
  port: 9092

redis:
  enabled: true
  nameOverride: sentry-redis
  usePassword: false
  ## Just omit the password field if your redis cluster doesn't use password
  # password: redis
  master:
    persistence:
      enabled: true
      storageClassName: "aws-efs"
      storageClass: "aws-efs"
      accessModes:
        - ReadWriteMany
      size: 1Mi
  slave:
    persistence:
      enabled: true
      storageClassName: "aws-efs"
      storageClass: "aws-efs"
      accessModes:
        - ReadWriteMany
      size: 1Mi

## This value is only used when redis.enabled is set to false
##
externalRedis:
  ## Hostname or ip address of external redis cluster
  ##
  # host: "redis"
  port: 6379
  ## Just omit the password field if your redis cluster doesn't use password
  # password: redis

postgresql:
  enabled: true
  nameOverride: sentry-postgresql
  postgresqlUsername: postgres
  postgresqlDatabase: sentry
  postgresqlPassword: sentry
  persistence:
    enabled: true
    mountPath: /bitnami/postgresql
    subPath: ""
    storageClass: "aws-efs"
    accessModes:
      - ReadWriteMany
    size: 1Mi
  replication:
    enabled: false
    slaveReplicas: 2
    synchronousCommit: "on"
    numSynchronousReplicas: 1

## This value is only used when postgresql.enabled is set to false
##
externalPostgresql:
  # host: postgres
  port: 5432
  username: postgres
  # password: postgres
  database: sentry
  # sslMode: require

rabbitmq:
  ## If disabled, Redis will be used instead as the broker.
  enabled: true
  forceBoot: true
  replicaCount: 3
  rabbitmqErlangCookie: pHgpy3Q6adTskzAT6bLHCFqFTF7lMxhA
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  nameOverride: ""

  podDisruptionBudget:
    minAvailable: 1

  persistentVolume:
    enabled: true
    storageClass: "aws-efs"
    storageClassName: "aws-efs"
    accessMode: ReadWriteMany
    size: 8Gi

  resources: {}
  persistence:
    enabled: true
    storageClass: "aws-efs"
    storageClassName: "aws-efs"
    accessMode: ReadWriteMany
    size: 8Gi

  definitions:
    policies: |-
      {
        "name": "ha-all",
        "pattern": "^((?!celeryev.*).)*$",
        "vhost": "/",
        "definition": {
          "ha-mode": "all",
          "ha-sync-mode": "automatic",
          "ha-sync-batch-size": 1
        }
      }

## Prometheus Exporter / Metrics
##
metrics:
  enabled: true

  ## Configure extra options for liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1

  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  # schedulerName:
  # Optional extra labels for pod, i.e. redis-client: "true"
  # podLabels: []
  service:
    type: ClusterIP
    labels: {}

  image:
    repository: prom/statsd-exporter
    tag: v0.17.0
    pullPolicy: IfNotPresent

  # Enable this if you're using https://github.com/coreos/prometheus-operator
  serviceMonitor:
    enabled: true
    additionalLabels:
      app: sentry
    namespace: ${kubernetes_prometheus_namespace}
    namespaceSelector:
      matchNames:
        - ${sentry_namespace}
    # Default: scrape .Release.Namespace only
    # To scrape all, use the following:
    # namespaceSelector:
    #   any: true
    scrapeInterval: 30s
    # honorLabels: true
```
