### ISSUE TITLE
Helm yaml templating issue for Ingress object

### ISSUE THREAD

**Issue by dnlsndr** [sentry-kubernetes/charts#200]
When installing the Sentry chart from scratch, the Ingress object is not created although ingress.enabled is set to `true`.
This originates from a false ingress templating, where moustache sections contain arbitrary minus (`-`) characters.
## Current status
```
{{- if .Values.ingress.enabled -}}
apiVersion: {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }} networking.k8s.io/v1beta1 {{- else }} extensions/v1beta1 {{- end }}
kind: Ingress
metadata:
 name: {{ template "sentry.fullname" . }}
 labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
 annotations:
   {{- range $key, $value := .Values.ingress.annotations }}
     {{ $key }}: {{ $value | quote }}
   {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
    {{- if .Values.nginx.enabled }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-nginx
              servicePort: {{ .Values.nginx.service.port }}
    {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api/store
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: {{ default "/" .Values.ingress.path }}api/[1-9][0-9]*/(.*)
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
    {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
```
