### ISSUE TITLE
[5.6.0] Setting cert for new Sentry DSN endpoint

### ISSUE THREAD

**Issue by dnlsndr** [sentry-kubernetes/charts#201]
Sentry has changed their DSN endpoint to be under a new subdomain for each organization:
Now:
`https://<sentry-dsn>@o<number>.ingest.<domain>.<tld>`
Then:
`https://<sentry-dsn>@sentry.<domain>.tld`

This leads to a invalid cert on our side, since we only define a cert-manager generated cert at the ingress for TLS termination. 
Our cert is only valid for `*.<domain>.<tld>` and not for `*.ingest.<domain>.<tld>`, thus leading to a ERR_CERT_AUTHORITY_INVALID error on browser side, when a new error is sent to sentry.

How would I go about implementing a cert for that ingest subdomain, since there are no ingress resources created for it? 

Here a reference to the changes: https://forum.sentry.io/t/organization-subdomains-in-dsns/9360

**Comment by Mokto** [comment]
Thanks for the information, it's very interesting! Didn't notice that change.

I guess it depends on which ingress provider you use. In my case I use istio + cert-manager and I work with sub-subdomains with a certificate defined like this :

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: secondary-dns-certificate
  namespace: istio-system
spec:
  secretName: secondary-certificate
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - xxxxx
  dnsNames:
  - "*.domain.com"
  - "*.ingest.domain.com"
  issuerRef:
      name: letsencrypt-prod-issuer
      kind: ClusterIssuer
      group: cert-manager.io
```

and my gateway:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-secondary
      protocol: HTTPS
    hosts:
      - "*.domain.com"
      - "*.ingest.domain.com"
    tls:
      mode: SIMPLE
      credentialName: secondary-certificate
```

**Comment by dnlsndr** [comment]
Interesting!
I've implemented Istio now too, since I always wanted to give it a shot. I think it is much better solvable through the gateway/virtualService CRDs. Would you care to show me how your virtualService looks? Im still quite new to those concepts.

**Comment by Mokto** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sentry-web
spec:
  gateways:
  - gateway.istio-system
  hosts:
  - sentry.domain.com
  http:
  - route:
    - destination:
        host: sentry-nginx
        port:
          number: 80
```

As simple as that! I have to remove nginx at some point & point directly to sentry&relay.
