### ISSUE TITLE
[Sentry] Ingress configuration not compatible with alb-loadbalancer-controller

### ISSUE THREAD

**Issue by Puneeth-n** [sentry-kubernetes/charts#230]
**Kubernetes version:** 1.18
**Helm:** 3
**Chart version:** 7.1.0

**Sentry Helm config:**

```
resource "helm_release" "sentry" {
  name       = local.sentry.name
  repository = "https://sentry-kubernetes.github.io/charts"
  chart      = "sentry"
  version    = "7.1.0"
  namespace  = kubernetes_namespace.sentry.metadata[0].name
  lint       = true

  values = [
    yamlencode(
      {
        user = {
          create   = true
          email    = "lorem.ipsum@foo.com"
          password = random_password.sentry_password.result
        }

        ingress = {
          enabled = true
          annotations = {
            "kubernetes.io/ingress.class"               = "alb"
            "alb.ingress.kubernetes.io/scheme"          = "internet-facing"
            "alb.ingress.kubernetes.io/listen-ports"    = jsonencode([{ HTTP = 443 }])
            "alb.ingress.kubernetes.io/group.name"      = "infra"
            "alb.ingress.kubernetes.io/certificate-arn" = aws_acm_certificate.subdomain.arn
          }
          hostname = "sentry.${module.infra_vpc.public_subdomain}"
        }
      }
    )
  ]
}
```

**alb-load-balancer-controller:**
```
resource "helm_release" "aws_load_balancer_controller" {
  name       = local.aws_load_balancer_controller.name
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  version    = "1.0.3"
  namespace  = local.aws_load_balancer_controller.namespace
  lint       = true

  values = [
    yamlencode(
      {
        dependency  = null_resource.target_group_binding.id
        clusterName = local.kubernetes_cluster_name
        serviceAccount = {
          create = true
          name   = local.aws_load_balancer_controller.service_account_name
          annotations = {
            "eks.amazonaws.com/role-arn" = aws_iam_role.aws_load_balancer_controller.arn
          }
        }
        rbac = {
          create = true
        }
        nodeSelector = {
          "node.kubernetes.io/workergroup-name" = "stateful"
        }
        enableCertManager = false
      }
    )
  ]
}
```

**Error message:**
```
{"level":"error","ts":1604562908.6424568,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"infra-external","namespace":"","error":"failed to create listener rule: ValidationError: Condition value '/api/[1-9][0-9]*/(.*)' contains a character that is not valid\n\tstatus code: 400, request id: 64b2b463-00c1-4b8f-a436-243b8c66b7da"}
```

**Comment by DandyDeveloper** [comment]
This is because the relay regex exists:

https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/ingress.yaml#L30

I don't remember the syntax for AWS LB Ingress, is it just expecting `path-patterns` rather than `path`? 

You could submit a PR with a conditional added specifically for AWS LB being enabled. It's a tough one making this a 1 size fits all.

The alternative is to copy the above files into your own `templates`, adjust it to fit the AWS LB and just set `ingress.enabled` to `false`

**Comment by phenixdotnet** [comment]
@Puneeth-n ALB path pattern doesn't support regex. The chart use nginx style regex in path configuration which results in the error you have.
I'm actually working on a solution but I don't have somethings acceptable.
My current configuration is 
```yaml
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api/store/*
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: /api/*/store/
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: /api/*/envelope/
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: /api/0-9*/*
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: "/*"
            backend:
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
```

As you can see, you have to list sub path in `/path/` to forward specific call to the relay instead of the web. 
The `/api/0-9*/*` doesn't seem to work.

**Comment by joel-schaal** [comment]
If I understand the [Ingress documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) properly, and the different use cases described in the `ingress.yaml` template, I guess the following should have +/- the same outcome, no ?
```
    {{- if .Values.nginx.enabled }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-nginx
              servicePort: {{ .Values.nginx.service.port }}
    {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: {{ default "/*" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
    {{- end }}
```

When the URL starts wth `/api/*`, we go to the *relay* service, and for everything else we go to the *web* service.

Do you see a risk/a regression in such implementation ?

**Comment by phenixdotnet** [comment]
Yes there is an issue because the web app also use the `/api/XXXX/` path ...
For example: `/api/0/organizations/XXXXX/stats/` when you open the admin panel

**Comment by joel-schaal** [comment]
I may understand it wrong but I thought `/api/0/organizations/XXXXX/stats/` would match the section 
```
        {{- if eq (default "nginx" .Values.ingress.regexPathStyle) "traefik" }}
          - path: {{ default "/" .Values.ingress.path }}api/{[1-9][0-9]*}/{(.*)}
        {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api/[1-9][0-9]*/(.*)
        {{- end }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
```
of the ingress,yaml, and therefore go to the _relay_ service, not the _web_ service.

**Comment by phenixdotnet** [comment]
@joel-schaal : Are you sure the request `/api/0/organizations/XXXXX/stats/` could/should be handled by the relay service ?

As far as understand the relay service, it should only handle the events ingestion but this request come from the web UI and should be handled by the web service. This is how it work in my deployment. I will try to send this kind of requests to the relay service to confirm or not.

Anyway, more I think about this configuration, more I think the best solution is to have 2 hosts, one for the relay service and one the web. It will greatly simplify the configuration and the management.

**Comment by joel-schaal** [comment]
You are right, [after investigation](https://forum.sentry.io/t/switch-form-nginx-to-aws-alb/13000/7?u=joel.schaal) I discovered that ` /api/0/*` should actually go to the web service and not relay. So my `ingress,yaml` now looks like: 
```yaml
{{- if .Values.ingress.enabled -}}
apiVersion: {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }} networking.k8s.io/v1beta1 {{- else }} extensions/v1beta1 {{- end }}
kind: Ingress
metadata:
 name: {{ template "sentry.fullname" . }}
 labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
 annotations:
   {{- range $key, $value := .Values.ingress.annotations }}
     {{ $key }}: {{ $value | quote }}
   {{- end }}
   {{- if .Values.ingress.alb.redirectHTTP }}
     alb.ingress.kubernetes.io/actions.ssl-redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
     alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
   {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
    {{- if .Values.nginx.enabled }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-nginx
              servicePort: {{ .Values.nginx.service.port }}
    {{- else }}
      {{- if .Values.ingress.alb.redirectHTTP }}
          - path: "/*"
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
      {{- end }}
          - path: {{ default "/" .Values.ingress.path }}api/0/*
            backend:
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
          - path: {{ default "/" .Values.ingress.path }}api/*
            backend:
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
          - path: {{ default "/*" .Values.ingress.path | quote }}
            backend:
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
    {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
```

**Comment by yurymkomarov** [comment]
@Puneeth-n hi, did u solve your issue with aws-alb?

I'm asking because I can't deploy sentry with AWS alb controller :/

**Comment by phenixdotnet** [comment]
HI @yurymkomarov,
You still can't deploy it with the [new option](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L370) `aws-alb` ? 
Do you have a specific issue ?

**Comment by Puneeth-n** [comment]
> @Puneeth-n hi, did u solve your issue with aws-alb?
> 
> I'm asking because I can't deploy sentry with AWS alb controller :/

Honestly, I did not try it out. I did not deploy sentry on k8s

**Comment by joel-schaal** [comment]
I think the new option solves the main issues with ALB.
For me, the only thing that's missing is HTTP to HTTPS redirection.

I had [some changes](https://github.com/dentalwings/sentry-helm/commit/d094e5d4cb9d410b59e7cb4e5ac332d89a0cf84f) for our own setup, it may inspire you if you need that feature too.

**Comment by LouisPolyconseil** [comment]
Since https://github.com/sentry-kubernetes/charts/pull/375 is merged, you must be able to totally remove the nginx. It works in my case

**Comment by rkmudunuru** [comment]
I am facing a weird issue when I used aws-alb option. The rabbitmq and worker pods go into CrashLoopBackOff mode. It throws below error for rabbitmq

Chart Version used:
```
apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 12.0.0
appVersion: 21.8.0
```

```
entry-rabbitmq-1                              0/1     PostStartHookError: command '/bin/bash -ec until rabbitmqctl cluster_status >/dev/null; do
    echo "Waiting for cluster readiness..."
    sleep 5
done
rabbitmq-queues rebalance "all"
' exited with 69: Error: unable to perform an operation on node 'rabbit@sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: ['rabbit@sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local']

rabbit@sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local:
  * connected to epmd (port 4369) on sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local
  * epmd reports: node 'rabbit' not running at all
                  other nodes on sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local: ['rabbitmqcli-179-rabbit']
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-704-rabbit@sentry-rabbitmq-1.sentry-rabbitmq-headless.sentry-ing.svc.cluster.local'
 * effective user's home directory: /opt/bitnami/rabbitmq/.rabbitmq
 * Erlang cookie hash: TFB4SFB8T1o+tf/yiGTPCA==

Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
                                               cluster_status

Usage

rabbitmqctl [--node <node>] [--longnames] [--quiet] cluster_status [--timeout <timeout>]

08:57:31.553 [error] Discarding message {'$gen_call',{<0.1213.0>,#Ref<0.3071371048.1286864898.77934>},{info,[messages]}} from <0.1213.0> to <0.845.0> in an old incarnation (2) of this node (3)


Error:
{:noproc, {:gen_server2, :call, [#PID<11553.845.0>, {:info, [:messages]}, :infinity]}}
```

**Comment by sfc-gh-pkommini** [comment]
Have this same issue:

This is my `${path.module}/templates/sentry_values.yaml` file:
```yaml
prefix: ${module_prefix}

user:
  create: true
  email: ${sentry_email}
  password: ${sentry_password}

nginx:
  enabled: false

ingress:
  enabled: true
  hostname: ${sentry_dns_name}
  regexPathStyle: aws-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/inbound-cidrs: ${allowed_cidr_blocks_str}
    alb.ingress.kubernetes.io/subnets:  ${public_subnet_ids_str}
    alb.ingress.kubernetes.io/certificate-arn: ${subdomain_cert_arn}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 443}]'
    external-dns.alpha.kubernetes.io/hostname: ${sentry_dns_name}
```

This is how the `helm_release` looks like:
```
resource "helm_release" "sentry" {
  name       = "sentry"
  chart      = "sentry"
  repository = "https://sentry-kubernetes.github.io/charts"
  version    = "12.0.0"

  namespace = kubernetes_namespace.sentry.metadata[0].name
  timeout   = 600
  wait      = false

  values = [
    templatefile(
      "${path.module}/templates/sentry_values.yaml",
      {
        module_prefix = "${var.module_prefix}",

        sentry_email    = "${var.sentry_email}",
        sentry_password = "${var.sentry_password}",

        sentry_dns_name         = "${local.sentry_dns_name}",
        subdomain_cert_arn      = "${var.subdomain_cert_arn}",
        allowed_cidr_blocks_str = "${join(",", var.allowed_cidr_blocks)}",
        public_subnet_ids_str = "${join(",", var.public_subnet_ids)}",
      }
    )
  ]
}
```

What works:
1. Target groups are created
2. External DNS works and creates an A record and TXT record in Route53 Hosted Zone (due to separate external-dns configs, which I can link on request)
3. Listener however the cert is not applied

What doesn't work:
1. The certificate-arn mentioned doesn't get applied to the listener
2. The target groups don't get registered on the listener

@yurymkomarov @phenixdotnet @Puneeth-n @LouisPolyconseil @rkmudunuru @Mokto Do you have any suggestions as to what I can do?
