### ISSUE TITLE
[QUESTION] How do you setup tabix?

### ISSUE THREAD

**Issue by mariusmitrofanbostontr** [sentry-kubernetes/charts#231]
Hey @Mokto  :)

Any idea how do you set up Tabix?

I mean, after launching an ingress and opening it in a browser it asks for the following things:
* Connection -> which I think should be `http://sentry10-clickhouse:8123`
* Login
* Password

Where do I get this username/password thing?

My hunch is that I should have something like this defined in values.yaml:

```
clickhouse:
  enabled: true
  clickhouse:
    configmap:
      profiles:
        enabled: true
        profile:
          - name: "default"
            config:
              max_memory_usage: "10000000000"
              use_uncompressed_cache: "0"
              load_balancing: "random"
      users:
        enabled: true
        user:
          - name: "admin"
            config:
              password: "admin"
              networks:
                - "::/0"
              profile: "default"
              quota: "default"
```

Hence the username/password there should be admin and admin. Right?

But it doesn't seem to be working...
