### ISSUE TITLE
Setting up S3 with Minio

### ISSUE THREAD

**Issue by L-U-C-K-Y** [sentry-kubernetes/charts#255]
Hi all

Thanks for the great work on this chart!

I got mostly everything running and as a final step I try to integrate S3 (minio) so that I can upload sourcemaps.

The thing that I am stuck with is the endpointUrl (I assume).

I tried different URL's without success:

- http://tenant1-hl.minio.svc.cluster.local
- http://tenant1-hl.minio.svc.cluster.local:9000
- tenant1-hl.minio.svc.cluster.local:9000
- https://minio.minio.svc.cluster.local
- https://tenant1-zone-0-{0...1}.tenant1-hl.minio.svc.cluster.local/export{0...1}
- https://tenant1-zone-0-0.tenant1-hl.minio.svc.cluster.local
- http://tenant1-zone-0-0.tenant1-hl.minio.svc.cluster.local
- https://tenant1-zone-0-0.tenant1-hl.minio.svc.cluster.local:9000

### Errors

```bash
error: API request failed
  caused by: sentry reported an error: bad gateway (http status: 502)
```

```bash
error: API request failed
  caused by: sentry reported an error: [Errno 104] Connection reset by peer (http status: 400)
```

```bash
error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object({"detail": String("Internal Error"), "errorId": String("e0bf89a811da4388a11a508c67970976")})
```

```bash
error: API request failed
  caused by: sentry reported an error: ('Connection aborted.', error(111, 'Connection refused')) (http status: 400)
```

```bash
error: API request failed
  caused by: sentry reported an error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727) (http status: 400)
```

<img width="1293" alt="Screenshot 2020-12-01 at 11 35 53" src="https://user-images.githubusercontent.com/14868134/100729777-7cca2e00-33c9-11eb-8b6d-48ea22fe3251.png">

## Setup

Values.yaml

```yaml
  filestore:
    backend: s3

    filesystem:
      persistence:
        persistentWorkers: false # Lucky: https://github.com/sentry-kubernetes/charts/issues/190#issuecomment-704924025

    s3:
      accessKey: xxx # minio accessKey base64 encoded, directly taken from the tenant.yaml generated by the minio operator
      secretKey: xxx # minio secretKey base 64 encoded, directly taken from the tenant.yaml generated by the minio operator
      bucketName: sentry # created the bucket through the minio UI
      endpointUrl: http://tenant1-hl.minio.svc.cluster.local
      # signature_version:
      # region_name:
      # default_acl:
```

I have created minio through the operator with the following command:

```bash
kubectl minio tenant create --name tenant1 --servers 1 --volumes 4 --capacity 40Gi -o -n minio> tenant.yaml
```

Edit: Added another error
