### ISSUE TITLE
Unable to write event to Sentry via DSN in Kubernetes

### ISSUE THREAD

**Issue by madanton1994** [sentry-kubernetes/charts#263]
Good day!

I try to deploy the Sentry chart in kubernetes, Sentry starts, the web interface is accessible via ingress, but when I record an event via DSN, I get a 403 error.

I use the chart from the branch https://github.com/sentry-kubernetes/charts/tree/sentry-august

I tried to record the event both through centry-cli and using Python, the result is the same 403 Forbidden error

Of course SENTRY_DSN indicated

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: default-nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    
  
  hostname: sentry.example.com
  
  tls:
  - secretName: example-secret
    hosts:
      - sentry.example.com
```

Nginx service is disabled

```yaml
nginx:
  enabled: false
```

Sentry Version 20.8.0 17e488c

**Comment by J0sh0nat0r** [comment]
Hey! The August branch doesn't include the patch which configures relay in proxy mode, which seems to solve this error in some (if not most) cases. Are you able to run version 7.0.0+ of the chart?

**Comment by pavanfhw** [comment]
Hello @madanton1994 @J0sh0nat0r! I am having the same issue in Kubernetes. I am using my own ingress (Istio)
What do I need to do to solve this "Forbidden" status when sending events?

**Comment by kmmanto** [comment]
Having this issue as well.

I can see this log in `sentry-kubernetes` but I don't see the event ingested in Sentry
```
2021-05-28 01:55:43,535 Sending message of length 2659 to https://[SENTRY_URL]/api/11/store/
```

**Comment by billakuduru** [comment]
Hello @pavanfhw I am facing the same issue, can you please share the solution if it is resolved

**Comment by jsbrain** [comment]
You need to make sure, you specify the correct cluster-issuer and so on.

This config is working for me:

```yaml
ingress:
  enabled: true # (default: false)
  # If you are using traefik ingress controller, switch this to 'traefik'
  # if you are using AWS ALB Ingress controller, switch this to 'aws-alb'
  # if you are using GKE Ingress controller, switch this to 'gke'
  regexPathStyle: nginx
  #If you are using AWS ALB Ingress controller, switch to true if you want activate the http to https redirection.
  alb:
    httpRedirect: false
  annotations:
    #   If you are using nginx ingress controller, please use at least those 2 annotations
    #   kubernetes.io/ingress.class: nginx
    #   nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod # <- make sure to include your cluster-issuer
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hostname: sentry.example.com
  tls:
    - hosts:
        - sentry.example.com
      secretName: sentry.example.com-cert
```
