### ISSUE TITLE
How to disable http logging

### ISSUE THREAD

**Issue by stefanocke** [sentry-kubernetes/charts#265]
In our Kibana I noticed a lot of http log entries for sentry-web and sentry-snuba (api):
```
 "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.17+"
``` 
Since the kube probes happen every few seconds, and since we have the http ingress logs anyway, I wanted to disable http logging in sentry-web and sentry-snuba.

I tried with SENTRY_LOG_LEVEL but with no success.

Since I don't know anything about the django or python universe, it took me some time to recognize it is not sentry logging, but **uwsgi** logging.

I would like to document my solution here if someone else needs it.
Maybe something about UWSGI configuration could be mentioned in the readme...

In values.yaml I added:
```
sentry:
...
  web:
...
    env:
    - name:  UWSGI_DISABLE_LOGGING
      value: 'true'

...

snuba:
  api:
...
    env:
    - name:  UWSGI_DISABLE_LOGGING
      value: 'true'

```
