### ISSUE TITLE
config.configYml failing to accept valid YAML

### ISSUE THREAD

**Issue by Yinabled** [sentry-kubernetes/charts#287]
In [`sentry-kubernetes` v6.0.0](https://github.com/sentry-kubernetes/charts#upgrading-from-5xx-version-of-this-chart-to-600), `config.configYml` was updated to take in YAML instead of the original config format. However, it seems like valid YAML still results in YAML parsing errors within `sentry-web`, as follows: `in "/etc/sentry/config.yml", line 1, column 1 expected <block end>, but found '-'`.

For context, we're using Terraform to provision our Sentry deployment. Both of the following YAML values for `config.configYml` fail when pushed to prod:
```
set {
    name  = "config.configYml"
    value = "{\"slack.client-id\": ${var.sentry_config.slack_client_id}, \"slack.client-secret\": ${var.sentry_config.slack_client_secret}, \"slack.verification-token\": ${var.sentry_config.slack_verification_token}, \"github-app.id\": ${var.sentry_config.github_app_id}, \"github-app.name\": ${var.sentry_config.github_app_name}, \"github-app.webhook-secret\": ${var.sentry_config.github_app_webhook_secret}, \"github-app.private-key\": ${replace(var.sentry_config.github_app_private_key, "/\n/", "\\n")}, \"github-app.client-id\": ${var.sentry_config.github_app_client_id}, \"github-app.client-secret\": ${var.sentry_config.github_app_client_secret}}"
  }
```

as well as

```
  set {
    name  = "config.configYml"
    value = <<-EOT
--- 
slack.client-id: "${var.sentry_config.slack_client_id}"	
slack.client-secret: "${var.sentry_config.slack_client_secret}"	
slack.verification-token: "${var.sentry_config.slack_verification_token}"	
github-app.id: ${var.sentry_config.github_app_id}	
github-app.name: "${var.sentry_config.github_app_name}"	
github-app.webhook-secret: "${var.sentry_config.github_app_webhook_secret}"	
github-app.private-key: "${replace(var.sentry_config.github_app_private_key, "/\n/", "\\n")}"	
github-app.client-id: "${var.sentry_config.github_app_client_id}"	
github-app.client-secret: "${var.sentry_config.github_app_client_secret}"	
    EOT
  }
```

Any ideas on what might be going wrong with our YAML, or if there exists some kind of alternative that can still be provisioned via the helm chart `values.yaml`?

**Comment by Yinabled** [comment]
cc @DandyDeveloper @Mokto - [this change](https://github.com/sentry-kubernetes/charts/pull/186) changed how the `config.configYml` value is parsed, but it seems as if the parsing doesn't happen properly. As an example, the below is my `/etc/sentry/config.yml` (with sensitive values redacted):
```
system.secret-key: "REDACTED"
postprocess.use-cache-key: 1.0

# This URL will be used to tell Symbolicator where to obtain the Sentry source.
# See https://getsentry.github.io/symbolicator/api/
system.internal-url-prefix: 'http://sentry-web:9000'
symbolicator.enabled: false

################
#    Redis     #
################
redis.clusters:
  default:
    hosts:
      0:
        host: "sentry-sentry-redis-master"
        port: 6379
        password: ""

################
# File storage #
################
# Uploaded media uses these `filestore` settings. The available
# backends are either `filesystem` or `s3`.
filestore.backend: "filesystem"
filestore.options:
  location: "/var/lib/sentry/files"

- '"slack.client-id": REDACTED'
- ' "slack.client-secret": REDACTED'
- ' "slack.verification-token": REDACTED'
- ' "github-app.id": REDACTED'
- ' "github-app.name": REDACTED'
- ' "github-app.webhook-secret": REDACTED'
- ' "github-app.private-key": n-----BEGIN RSA PRIVATE KEY-----REDACTED-----END
  RSA PRIVATE KEY-----n'
- ' "github-app.client-id": REDACTED'
- ' "github-app.client-secret": REDACTED'
```

As you can see, the properties resulting from the `config.configYml` value is clearly incorrectly formatted. Any idea what might be happening here?

**Comment by DandyDeveloper** [comment]
What does the snippet look like in your values? Can you include the whole section including the config.yml key?

This looks like user error, but I need to triple check and want a good example reference to replicate this error.

I know it's made by terraform, but if you can do `helm get values` from the release it might be clearer why this is happening.

**Comment by Yinabled** [comment]
Sure thing - here are the values for the Sentry helm release with redacted sensitive properties:
```
USER-SUPPLIED VALUES:
config:
  configYml:
  - '"slack.client-id": REDACTED'
  - ' "slack.client-secret": REDACTED'
  - ' "slack.verification-token": REDACTED'
  - ' "github-app.id": REDACTED'
  - ' "github-app.name": REDACTED'
  - ' "github-app.webhook-secret": REDACTED'
  - ' "github-app.private-key": n-----BEGIN RSA PRIVATE KEY-----REDACTED-----END
    RSA PRIVATE KEY-----n'
  - ' "github-app.client-id": REDACTED'
  - ' "github-app.client-secret": REDACTED'
  sentryConfPy: SENTRY_FEATURES['projects:custom-inbound-filters'] = True
externalPostgresql:
  database: sentry
  host: REDACTED
  password: REDACTED
  username: sentry
mail:
  backend: smtp
  host: smtp.REDACTED.org
  password: REDACTED
  port: REDACTED
  useTls: true
  username: REDACTED
postgresql:
  enabled: false
service:
  type: ClusterIP
user:
  email: REDACTED
  password: REDACTED
```
