### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by klinux** [sentry-kubernetes/charts#294]
I'm trying to install sentry on Kubernetes, bu if i let the option internal_replication = true, like default values, I receive this error in one instance of clickhouse:

Received exception from server (version 20.12.5):
Code: 60. DB::Exception: Received from sentry-clickhouse-0.sentry-clickhouse-headless:9000. DB::Exception: Table default.discover_local doesn't exist..

This error happens in sentry-clickhouse-init job.

I disabled the backup option of clickhouse,
```
    configmap:
      remote_servers:
        enabled: true
        internal_replication: true
        replica:
          backup:
            enabled: false
```

I tried a lot of clickhouse versions, and the result is always the same.

It only works if I disable **internal_replication** it is a clean installation, there something that  I missed?

Thank you
