### ISSUE TITLE
RabbitMQ chart contains duplicate filenames

### ISSUE THREAD

**Issue by jwoglom** [sentry-kubernetes/charts#340]
The Sentry helm chart is invoking the extraSecrets value on the bitnami RabbitMQ chart in a way such that both secrets identify themselves to helm as having the same filename.

You can see this by running `helm template sentry sentry/sentry --namespace=sentry`:

```

# Source: sentry/charts/rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-rabbitmq
  namespace: "sentry"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.9.1
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "xxxx"
  rabbitmq-erlang-cookie: "xxxx"
---
# Source: sentry/charts/rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: load-definition
  namespace: "sentry"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.9.1
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  load_definition.json: |
    {
      "users": [
        {
          "name": "guest",
          "password": "xxxx",
          "tags": "administrator"
        }
      ],
      "permissions": [{
        "user": "guest",
        "vhost": "/",
        "configure": ".*",
        "write": ".*",
        "read": ".*"
      }],
      "policies": [
        {
          "name": "ha-all",
          "pattern": ".*",
          "vhost": "/",
          "definition": {
            "ha-mode": "all",
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          }
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ]
    }
```

I'm not sure if Helm cares about this, but in my setup I'm using this chart to generate YAMLs which I am deploying to kubernetes clusters manually, and this bug mildly affected my workflow.

**Comment by Mokto** [comment]
With yaml you can put multiple definitions in the same file by separating with `---` 

How did that affect you ?

**Comment by jwoglom** [comment]
I was specifically taking the YAML output which is separated by `---` and then taking the Source filename mentioned in the comment and writing the YAML for that section to that filename, in order to split up the large generated YAML file.

So in this case, I was writing:

```
apiVersion: v1
kind: Secret
metadata:
  name: sentry-rabbitmq
  namespace: "sentry"
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.9.1
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "xxxx"
  rabbitmq-erlang-cookie: "xxxx"
```

to `sentry/charts/rabbitmq/templates/secrets.yaml` since Helm was declaring that as the source file in this case. But because the second secret also reports itself with that same filename I was overwriting the contents. 

I suppose maybe my initial assumption that there would be one kubernetes object per file was wrong?
