### ISSUE TITLE
Default resource limits in chart

### ISSUE THREAD

**Issue by sr258** [sentry-kubernetes/charts#345]
Very useful chart, thank you!

I've noticed that the chart doesn't set many default resource requests, but there are pods which use considerable resources, even without any content, in particular Kafka (RAM) and RabbitMQ (CPU). It would be great if the chart contained sane resource request values so that the pods are started on hosts with enough resources.

It would also be useful to have a minimum resource requirement in the README. Judging from my test deployment, it looks like Sentry needs about 11 GB RAM and 3 CPU cores in the Helm deployment (higher than the requirements for a conventional installation, due to HA). I think it would be useful for new-comers to know these numbers, so that they can plan their resources. I originally had too little resources and the installation failed due to the lack of resources.

**Comment by fullonic** [comment]
I'm having the same issue. I would like to figure out the resources necessary to run Sentry and I came across the same situation as described by @sr258. The only resources (limits/requested) that are present in the chart are related to [metrics](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L902). 
There are some examples? Can someone share some configurations? This could be a good starting point to create an `examples` folder with some configurations examples :smile:

**Comment by sr258** [comment]
I had success in starting Sentry with this resource configuration. It's probably only suitable for low loads, but it's enough to get everything started. Without these values I could not reliably start Sentry in the cluster as pods were scheduled on nodes that didn't have enough memory...

```yaml
sentry:
  worker:
    resources:
      limits:
        cpu: 1000m
        memory: 1500Mi
      requests:
        cpu: 500m
        memory: 700Mi
  cron:
    resources:
      limits:
        cpu: 2000m
        memory: 1000Mi
      requests:
        cpu: 1000m
        memory: 200Mi
hooks:
  dbCheck:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  dbInit:
    resources:
      limits:
        memory: 2048Mi
      requests:
        cpu: 300m
        memory: 2048Mi
  snubaInit:
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
      requests:
        cpu: 700m
        memory: 1Gi
clickhouse:
  clickhouse:
      resources:
        limits:
          cpu: 100m
          memory: 600Mi
        requests:
          cpu: 50m
          memory: 300Mi
kafka:
  resources:
    limits:
      cpu: 400m
      memory: 3000Mi
    requests:
      cpu: 100m
      memory: 1500Mi

redis:
  resources:
    limits:
      cpu: 400m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
rabbitmq:
  resources:
     limits:
       cpu: 1000m
       memory: 400Mi
     requests:
       cpu: 400m
       memory: 100Mi
```

**Comment by fullonic** [comment]
Hi @sr258. Thanks for sharing your configurations. Very helpful! 
One question, do you use these configurations with the default replicas number? Cheers

**Comment by sr258** [comment]
Yes, I've left the default replica number as is

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by scoopex** [comment]
Ping

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by theophanevie** [comment]
As redis is a sentry subchart, ressources should be provide to it. According to https://github.com/bitnami/charts/tree/master/bitnami/redis the correct pattern is 
``` yaml
   redis:
    master:
      nodeSelector:
        node-type: a-type
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 100m
          memory: 100Mi
    replica:
      replicaCount: 1
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 100m
          memory: 100Mi
```
