### ISSUE TITLE
Upgrading chart with internal PostgreSQL not possible when postresqlPassword is unset

### ISSUE THREAD

**Issue by sr258** [sentry-kubernetes/charts#354]
If you install the chart with an internal PostreSQL installation like this

```
postgresql:
  enabled: true
  nameOverride: sentry-postgresql
  postgresqlUsername: postgres
  postgresqlDatabase: sentry
  replication:
    enabled: false
    readReplicas: 2
    synchronousCommit: "on"
    numSynchronousReplicas: 1
    applicationName: sentry
```

upgrading the chart will later fail, as the db-init job can't access the PostgreSQL database for the `postgres` user. It only works if I manually set `postgresqlPassword`. I think this behaviour should be documented, as it is a bit confusing for newcomers.
