### ISSUE TITLE
EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True. 21.4.0

### ISSUE THREAD

**Issue by teebu** [sentry-kubernetes/charts#363]
I'm using the same setting I was using prior to upgrading to 21.4.0, but now i'm seeing this error in the internal sentry error. 
```
mail:
  backend: smtp
  useTls: true
  username: "apikey"
  password: "mypassword"
  port: 587
  host: "smtp.sendgrid.net"
  from: "sentry@domain.com"
```

The in the sentry error, it shows these fields set:
```

fail_silently | False
-- | --
kwargs | {}
password | 'mypassword'
port | 587
ssl_certfile | None
ssl_keyfile | None
timeout | 10
use_ssl | True
use_tls | True
username | 'apikey'
```

### Error:
```
EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
```

# solution
Adding this to the config and updating the `templates\configmap-sentry.yaml` seems to have resolved the issue
```
mail:
  backend: smtp
  useTls: true
  useSsl: false
```

```
    #######################
    # Email Configuration #
    #######################
    SENTRY_OPTIONS['mail.backend'] = os.getenv("SENTRY_EMAIL_BACKEND", {{ .Values.mail.backend | quote }})
    SENTRY_OPTIONS['mail.use-tls'] = bool(strtobool(os.getenv("SENTRY_EMAIL_USE_TLS", {{ .Values.mail.useTls | quote }})))
    SENTRY_OPTIONS['mail.use-ssl'] = bool(strtobool(os.getenv("SENTRY_EMAIL_USE_SSL", {{ .Values.mail.useSsl | quote }})))
```
