### ISSUE TITLE
Setting sentry web replicas more then 1?

### ISSUE THREAD

**Issue by teebu** [sentry-kubernetes/charts#370]
I seem to be having trouble updating the replica counts for this. It throws some volume already assigned error. Am I not supposed to run multiple of this one?

```
sentry:
  singleOrganization: true
  web:
    # if using filestore backend filesystem with RWO access, set strategyType to Recreate
    strategyType: RollingUpdate
    replicas: 1
```
