### ISSUE TITLE
Upgrade from v11.2 to v11.3 fails

### ISSUE THREAD

**Issue by Dilbarjot** [sentry-kubernetes/charts#400]
v11.2 is installed using
helm install --debug --namespace st --set POSTGRES_PASSWORD=postgresqlPassword@localinstallation mysentry ./sentry

and upgraded to v11.3 using
helm upgrade --cleanup-on-fail --debug --timeout 20m0s mysentry ~/Downloads/sentry-11.3.0.tgz --namespace st --set POSTGRES_PASSWORD=postgresqlPassword@localinstallation --set system.secretKey=secretkey

However, 
`mysentry-db-init` job fails, and upon looking at the `db-init` pod, it gives an error that authentication for user `postgres` failed. I tried following steps as well
- Not including any password to install v12 and then upgrading with --set POSTGRES_PASSWORD
- Including a key `.postgresql.postgresqlPassword` in `values.YAML` file and then including its value during upgrade

**Comment by Dilbarjot** [comment]
Maybe it's not an issue or bug, but some documentation is needed to ensure successful upgrading between releases. @Mokto

**Comment by Mokto** [comment]
See https://github.com/sentry-kubernetes/charts#postgressql

**Comment by Dilbarjot** [comment]
When I wrote the comment, I also tried setting `postgresql.postgresqlPassword` in v11.2's `values.yaml` when installing, but I passed it via env when upgrading to v11.3 (since I had a .tgz file) which didn't work.

**Comment by max-wittig** [comment]
@Dilbarjot @peppe77 @hanstsangcwc How did you make it work? Please help. My config:

```yaml
# values.yml

global:
  postgresql:
    postgresqlPassword: postgres
  postgresqlPostgresPassword: postgres

sentry:
  metrics:
    enabled: true
  symbolicator:
    enabled: true
  ingress:
    enabled: true
  nginx:
    enabled: true
  sentry:
    postgresql:
      postgresqlPassword: postgres
      postgresqlUsername: postgres
      password: postgres
      postgresql-postgres-password: postgres
    postgres:
      postgresqlPassword: postgres
      password: postgres
      postgresql-postgres-password: postgres
      postgresqlPostgresPassword: postgres
  postgresql:
    postgres:
        postgresqlPassword: postgres
        password: postgres
        postgresql-postgres-password: postgres
        postgresqlPostgresPassword: postgres
    postgresqlPassword: postgres
    postgresqlUsername: postgres
    password: postgres
    postgresql-postgres-password: postgres

postgresql:
  postgres:
    postgresqlPassword: postgres
    password: postgres
    postgresqlPostgresPassword: postgres
  postgresql:
    postgresqlPassword: postgres
    password: postgres
    postgresqlPostgresPassword: postgres
  postgresqlPassword: postgres
  password: postgres
  postgresqlPostgresPassword: postgres
postgresqlPostgresPassword: postgres
```

```sh
helm install --dry-run --timeout=1h --values values.yml --set sentry.postgresPassword=postgres -f values.yml sentry-1633277588 . > results.yaml
```

The password is still not `postgres`: 

```yaml
# results.yaml

# Source: crash-test/charts/sentry/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-1633277588-sentry-postgresql
  labels:
    app.kubernetes.io/name: sentry-postgresql
    helm.sh/chart: postgresql-10.2.4
    app.kubernetes.io/instance: sentry-1633277588
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgresql-postgres-password: "WkxMZ2k5Zlk5Yw=="
  postgresql-password: "cG9zdGdyZXM="
```
