### ISSUE TITLE
traefik sentry-web PUT 403 CSRF error 

### ISSUE THREAD

**Issue by vasekch** [sentry-kubernetes/charts#414]
I'm running k3s cluster, I'm using Traefik Ingress.

My `values.yaml`

```
...
system:
  url: https://sentry.domain.my
  ...

nginx:
  enabled: false

ingress:
  enabled: true
  regexPathStyle: traefik
  hostname: sentry.domain.my

```

I'm able to log in, but only GET data in web interface. Any PUT request is showing 403 referrer origin CSRF domain origin not known.

I fixed this with adding following to my `values.yaml`:

```
config:
  sentryConfPy: |
    CSRF_TRUSTED_ORIGINS = ['sentry.domain.my']
```
