### ISSUE TITLE
Upgrade sentry helm chart from older version to latest without lost data

### ISSUE THREAD

**Issue by kudodenko** [sentry-kubernetes/charts#421]
Hi there,
I need help with upgrading sentry helm chart from 6.1.0 version to latest.
Now i stuck with error:
`Upgrade "sentry" failed: cannot patch "sentry-sentry-postgresql" with kind StatefulSet: StatefulSet.apps "sentry-sentry-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && cannot patch "sentry-rabbitmq" with kind StatefulSet: StatefulSet.apps "sentry-rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

values file:
```
clickhouse:
  tabix:
    enabled: false
filestore:
  filesystem:
    persistence:
      persistentWorkers: true
ingress:
  annotations:
    '"nginx.ingress.kubernetes.io/use-regex"': true
  enabled: true
  hostname: sentry.domain.com
nginx:
  enabled: false
postgresql:
  postgresqlPassword: changeme
sentry:
  features:
    orgSubdomains: false
system:
  secretKey: changeme
user:
  create: admin
  email: username@domain.com
  password: changeme
```
