### ISSUE TITLE
Not able to use custom CA

### ISSUE THREAD

**Issue by artyom191** [sentry-kubernetes/charts#425]
Tried to use this(release 9.1.0) - feat: added custom CA option for web component ([#314](https://github.com/sentry-kubernetes/charts/pull/314))
Got an error:
>   Warning  FailedReleaseSync  84s (x10 over 20m)  helm-operator  synchronization of release 'sentry-test' in namespace 'support' failed: installation failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[2].secret): unknown field "item" in io.k8s.api.core.v1.SecretVolumeSource

There is no item field if volumes.secret block in web deployment([deployment-sentry-web.yaml](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/deployment-sentry-web.yaml#L144)): 

>    volumes:
>       - name: custom-ca
>         secret:
>  {{ toYaml .Values.sentry.web.customCA | indent 10 }}
>       {{ end }}

**Comment by prskr** [comment]
Yeah the sample is actually wrong.
Try something like this:

```yml
      customCA:
        secretName: my-root-certs
        items:
          - key: whatever-key-you-are-using
            path: ca.crt
```

Should work like a charm. Probably someone can update the values sample
