### ISSUE TITLE
Need to support msteams configuration

### ISSUE THREAD

**Issue by ohjongsung** [sentry-kubernetes/charts#426]
references : https://develop.sentry.dev/integrations/msteams/

Add client id and secret to the config.yml file as shown below

```yaml
# Microsoft Teams #
msteams.client-id: your-client-id
msteams.client-secret: your-secret
```

so that, values.yaml need to support msteams configuration like slack configuration
```yaml
msteams: {}
# msteams:
#   clientId:
#   clientSecret:
#   Reference -> https://develop.sentry.dev/integrations/msteams/
```

and helm template
```yaml
###########
# msteams #
###########
{{- if .Values.msteams.clientId }}
msteams.client-id: {{ .Values.msteams.clientId | quote }}
msteams.client-secret: {{ .Values.msteams.clientSecret | quote }}
{{ end }}
```
