### ISSUE TITLE
Fresh installation - password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by cleveritcz** [sentry-kubernetes/charts#435]
Hello @Mokto,
I tried to get install Sentry but postgresql is giving me error about postgres user.

I also tried to add postgresqlPassword to values.yaml but it is not working.

```
postgresql:
  enabled: true
  nameOverride: sentry-postgresql
  postgresqlUsername: postgres
  postgresqlDatabase: sentry
  postgresqlPassword: postgres
  replication:
    enabled: false
    readReplicas: 2
    synchronousCommit: "on"
    numSynchronousReplicas: 1
    applicationName: sentry
```

Could you help me, please?
