### ISSUE TITLE
New installation cannot receive events - 503 service unavailable / relay?

### ISSUE THREAD

**Issue by ItsReddi** [sentry-kubernetes/charts#436]
We started a fresh install today, with the following options:
```
---
  filestore: 
    filesystem: 
      persistence: 
        persistentWorkers: "false"
  nginx: 
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
    hostname: "ourdomain"
    tls:
    - secretName: secretName
      hosts:
        - ourHost.de
  postgresql: 
    postgresqlPassword: "somepassword"
  user: 
    email: "some mail"
    password: "some password"
```

The result is a running web instance, where we can set all up.
After trying to send events we get 503 errors.

Non of the services show any errors in logs.

Then, **after** upgrading the chart, without any changes to above config.
The 503 error is also shown up in sentry-web.

Sentry-Web:
```
16:02:44 [ERROR] sentry_sdk.errors: Unexpected status code: 503 (body: b'<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.17.10</center>\r\n</body>\r\n</html>\r\n')
```

A direct browser call to `/api/store/` shows the same.

No other Pods show any errors in logs.
Ingress Logs: 503 Service Temporarily Unavailable

Any ideas?
