### ISSUE TITLE
chart documentation

### ISSUE THREAD

**Issue by rickydjohn** [sentry-kubernetes/charts#443]
the lack of a proper installation guide is very frustrating. Other issues are.
- snuba requires elevated permissions
- web needs a geoip.  Even after solving it, the service fails to come up and just fails. The liveliness check fails in fact because the service is not up but it does not log anything. 

I have been wrestling with it for 2 days now. If there is a clear installation guide, please share. Absolutely disheartening when a chart is so poorly documented.

**Comment by matt-psaltis** [comment]
Definitely feel the pain, its the only helm chart that doesn't "just work" on an empty minikube cluster.
The clickhouse init job needs to wait until clickhouse is healthy.

If the container images are precached/already present, we end up with about 4-5 jobs erroring before it eventually succeeds. With Job backoff limits of 6 on the db-init job for example, slower machines will almost always fail. Its much worse if the container images need to be downloaded first. The first installation experience is pretty much guaranteed to fail as the container images cannot download quickly enough however the jobs will have started to init anyway.

In terms of the values file that works in my local minikube:

```
sentry:
  worker:
    replicas: 1

clickhouse:
  clickhouse:
    replicas: "1"

kafka:
  zookeeper:
    serviceAccount:
      create: true

redis:
  serviceAccount:
    create: true

postgresql:
  serviceAccount:
    enabled: true

nginx:
  serviceAccount:
    create: true

rabbitmq:
  replicaCount: 1
  serviceAccount:
    create: true
```

Its quite a few changes to get the basic installation to succeed. Again, this still isn't 100% rock solid, I have to run this on some machines 3 or 4 times before we get a stable installation.

Hope this information helps stabilise the experience for first time users!
