### ISSUE TITLE
Quota doesn't seem to work

### ISSUE THREAD

**Issue by arianf** [sentry-kubernetes/charts#451]
Our Sentry Rate Limiting doesn't seem to be working, which is causing us to run out of resources very quickly.

```
version: 8.1.2
appVersion: 20.12.1
```

### configmap-sentry.yaml

```python
    ###############
    # Rate Limits #
    ###############

    # Rate limits apply to notification handlers and are enforced per-project
    # automatically.

    SENTRY_RATELIMITER = "sentry.ratelimits.redis.RedisRateLimiter"

    ##########
    # Quotas #
    ##########

    # Quotas allow you to rate limit individual projects or the Sentry install as
    # a whole.

    SENTRY_QUOTAS = "sentry.quotas.redis.RedisQuota"
```

### /manage/quotas/
<img width="1648" alt="Screen Shot 2021-08-04 at 10 46 21 AM" src="https://user-images.githubusercontent.com/7397857/128229291-a82c2c4a-fe1f-40f1-98e6-6ff9aef48e44.png">

What's interesting is that buffer works fine and it's using redis:
`SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'`

<img width="1184" alt="Screen Shot 2021-08-04 at 10 52 15 AM" src="https://user-images.githubusercontent.com/7397857/128230162-f77c47da-dc2b-489d-9241-e3632afd1679.png">

Any ideas how I can further debug this or fix this issue?

**Comment by arianf** [comment]
Looking at https://github.com/getsentry/sentry-quotas it seems you can specify the redis host directly. Let me try that.

```python 
SENTRY_QUOTAS = {
    'redis': {
        'hosts': {
            # for more information on configuring hosts, see the documentation for the
            # Nydus python package
            0: {
                'host': 'localhost',
                'port': 6379
            }
        }
    },
    'default_events_per_minute': 100,
}
```

**Comment by arianf** [comment]
It did not like that.

`TypeError: unhashable type: 'dict'`

**Comment by arianf** [comment]
Hmm, I've tried:

```yaml
    ################
    #    Redis     #
    ################
    redis.clusters:
      default:
        hosts:
          0:
            host: {{ $redisHost | quote }}
            port: {{ $redisPort }}
            {{- if $redisPass }}
            password: {{ $redisPass | quote }}
            {{- end }}
      quota:
        hosts:
          0:
            host: sentry-sentry-redis-master
            port: 6379
```

And

```python
    SENTRY_QUOTAS = "sentry.quotas.redis.RedisQuota"

    SENTRY_QUOTA_OPTIONS = {
        'cluster': 'quota',
    }
```

Which successfully deployed without error, but no luck on fixing the issue

```console
$ k exec -it pods/sentry-sentry-redis-slave-0 bash 
I have no name!@sentry-sentry-redis-slave-0:/$ redis-cli -h sentry-sentry-redis-master -p 6379
$ sentry-sentry-redis-master:6379> get key
(nil)
```
