### ISSUE TITLE
ArgoCD wants to change passwords periodically

### ISSUE THREAD

**Issue by cabrinha** [sentry-kubernetes/charts#482]
I'm using ArgoCD to deploy this chart and after every sync, it seems the `system.secret-key` and `postgres` passwords want to change. I have set the postgres password manually, so I'm not sure why it wants to change.

**Comment by cabrinha** [comment]
Looks like I need to set `asHook: false` after the first sync

**Comment by cabrinha** [comment]
Issue still persists with `asHook: false`

**Comment by ninanomenon** [comment]
i have the same problem with fluxcd

**Comment by cabrinha** [comment]
> i have the same problem with fluxcd

Here is what I did to get it working:
```yaml
      postgresql:
        global:
          postgresql:
            postgresqlPassword: postgres
            postgresqlPostgresPassword: postgres
        postgresqlPostgresPassword: postgres
        postgresqlPassword: postgres
```

**Comment by dani-CO-CN** [comment]
For solving the diffing problem with `system.secret-key` i created a secret for the secret-key beforehand. Append code to the sentry.conf.py, which sets the `system.secret-key` to read the value from an environment variable and set the environment variable in the container, all without changing in the helm chart! Maybe the whole chart should do it like that?

create a secret
``` yaml
apiVersion: v1
data:
  system-secretkey: ~~~INSERT_GENERATED_PASSWORD_OVER_32_CHARACTERS~~~
kind: Secret
metadata:
  name: sentry-secret
type: Opaque
```

set the secretKey to a placeholder, otherwise argocd will randomly generate a value.
``` yaml
system:
  secretKey: PLACEHOLDER
```

Change the way the `system.secret-key` gets into sentry by changing sentry.conf.py. We now read the key from an env variable. (This works because the sentry.conf.py is a python script)
``` yaml
config:
  sentryConfPy: |
    SENTRY_OPTIONS["system.secret-key"] = os.environ["SECRETKEY"]
``` 

Setting the env varialbe in the containers from a secret
``` yaml
ingestConsumer:
  env:
    - name: SECRETKEY
      valueFrom:
        secretKeyRef:
          name: sentry-secret
          key: system-secretkey
          
..... do this for all containers that use sentry.conf.py .....
worker:
  env:
    - name: SECRETKEY
      valueFrom:
        secretKeyRef:
          name: sentry-secret
          key: system-secretkey


```
Done!
