### ISSUE TITLE
Unable to set up Azure Devops

### ISSUE THREAD

**Issue by mlyskawinski** [sentry-kubernetes/charts#500]
### Info
version: `11.6.0`
cluster: `minicube (local, testing one)`
values: 
```
externalPostgresql:
  database: sentry
  port: 5432
  username: REDACTED
  password: REDACTED
  host: host.minikube.internal
postgresql:
  enabled: false
user:
  create: true
  email: maciej.lyskawinski@start-up.house
  password: REDACTED
config:
  configYml: 
    vsts.client-id: REDACTED
    vsts.client-secret: REDACTED
```
### Problem

When trying to add integration with azure devops, the client_id is not sent in the request. I've checked the `config.yml` that is being generated (at least on  `web` pod) and it is generated the same as the one I use for testing with docker compose, yet the docker compose is working and yours is not.

Any suggestions?
