### ISSUE TITLE
alb ingress path missing

### ISSUE THREAD

**Issue by yswtrue** [sentry-kubernetes/charts#516]
```

          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: sentry-nginx
                port:
                  number: 80
```

need to add this to ingress to make alb working.
