### ISSUE TITLE
Source Maps files and retrieving them error

### ISSUE THREAD

**Issue by teebu** [sentry-kubernetes/charts#538]
I'm able to upload the files and see them on the frontend without any errors, but when i try to download them from the release it takes me to error page. The worker and the web are on the same node. 

I saw this issue https://github.com/sentry-kubernetes/charts/issues/489 mention something similar. I am running this on GKE. 

Sentry 21.6.1

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/5531844/147164050-b2c8297d-db1b-46ae-8b4a-019f1b6739e4.png">

![image](https://user-images.githubusercontent.com/5531844/147163850-836fe26d-49e8-4043-8ec8-323f793de3c4.png)

```
{
detail: "Internal Error",
errorId: "a6f20f033c0a4dadb3c373ab130054b7",
}
```

```
filestore:
  # Set to one of filesystem, gcs or s3 as supported by Sentry.
  backend: filesystem

  filesystem:
    path: /var/lib/sentry/files

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true
      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 10Gi

      persistentWorkers: true
```

What can I do to solve this?

Also, do i need to enable symbolicator?

**Comment by teebu** [comment]
Some of the artifact files download, many return the `Internal Error` page. 

Seeing internal sentry errors about the missing files reqs.
![image](https://user-images.githubusercontent.com/5531844/147267498-472adb2b-4369-4d4a-95fa-12fea71beb92.png)

**Comment by teebu** [comment]
Upgraded to 21.8 Sentry and enabled S3 as the storage. 

I can upload files through the sentry page, and can verify the avatar upload is working. However, the source maps are still not loading. I'm submitting them through the CLI `sentry-cli releases -p myproj files`

```
sentry-cli releases new $RELEASE_NAME
sentry-cli releases set-commits --auto $RELEASE_NAME
sentry-cli releases files $RELEASE_NAME upload-sourcemaps --validate /work/dist/my-project-name
sentry-cli releases finalize $RELEASE_NAME
```

Still no luck, but I see some files in the s3 bucket (sentry still throwing s3 GetObject error, the ids don't match?).

![image](https://user-images.githubusercontent.com/5531844/147796877-d20427ad-930a-4b96-b7f8-246ef4fe736f.png)
![image](https://user-images.githubusercontent.com/5531844/147796924-e0993f77-7c8f-49ac-be5a-dd74f910c229.png)

**Comment by teebu** [comment]
I'm using nginx ingress with these settings:
```
ingress:
  enabled: true
  # If you are using traefik ingress controller, switch this to 'traefik'
  # if you are using AWS ALB Ingress controller, switch this to 'aws-alb'
  # if you are using GKE Ingress controller, switch this to 'gke'
  regexPathStyle: nginx
  #If you are using AWS ALB Ingress controller, switch to true if you want activate the http to https redirection.
  alb:
    httpRedirect: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 80M
```

I suspect the nginx ingress is missing some values that this needs to process. I added the proxy-body-size to solve the avatar not uploading. Maybe I'm missing more?

It looks like the nginx ingress is in front of the sentry nginx.

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by luckyf** [comment]
> I'm using nginx ingress with these settings:
> 
> ```
> ingress:
>   enabled: true
>   # If you are using traefik ingress controller, switch this to 'traefik'
>   # if you are using AWS ALB Ingress controller, switch this to 'aws-alb'
>   # if you are using GKE Ingress controller, switch this to 'gke'
>   regexPathStyle: nginx
>   #If you are using AWS ALB Ingress controller, switch to true if you want activate the http to https redirection.
>   alb:
>     httpRedirect: false
>   annotations:
>     kubernetes.io/ingress.class: nginx
>     nginx.ingress.kubernetes.io/use-regex: "true"
>     nginx.ingress.kubernetes.io/proxy-body-size: 80M
> ```
> 
> I suspect the nginx ingress is missing some values that this needs to process. I added the proxy-body-size to solve the avatar not uploading. Maybe I'm missing more?
> 
> It looks like the nginx ingress is in front of the sentry nginx.

Hi @teebu,

did you found a solution for this in the end?

I got stuck on the same issue with almost the same setup (S3 Persistence, but NGINX disabled). Uploading Attachments/Sourcemaps works fine but Sentry doesn't map the Sourcemaps to the Errors.
Same Client-Setup for sentry.io works.

### EDIT

I was able to solve it on my own. Forgot to enable the Symbolicator service with with `symbolicator.enabled: true` in my `values.yml`.

**Comment by b-tin** [comment]
> I was able to solve it on my own. Forgot to enable the Symbolicator service with with symbolicator.enabled: true in my values.yml.

thanks @luckyf you save my day, with enable service `symbolicator` --> sourcemap working now with Sentry helm version 23.11.2

**Comment by dmitry-mightydevops** [comment]
for someone who will land this issue in the future, and will want to save time setting up s3 for the sentry using IRSA IAM roles for eks (as I prefer them over IAM user creds)

### terraform code:

```hcl
module "eks_label" {
  source      = "cloudposse/label/null"
  version     = "0.25.0"
  namespace   = "project" # var.client
  environment = "prod" # var.environment
  attributes  = ["eks"]
}

module "sentry_bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "4.1.0"

  bucket = join(module.eks_label.delimiter, [module.eks_label.id, "sentry"])
  acl    = "private"

  # Allow deletion of non-empty bucket
  force_destroy            = false
  control_object_ownership = true
  object_ownership         = "BucketOwnerPreferred"
  expected_bucket_owner    = data.aws_caller_identity.current.account_id

  # S3 bucket-level Public Access Block configuration
  block_public_acls       = false
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  tags = merge(local.tags,
    { description = "This bucket contains sentry traces" }
  )
}

data "aws_iam_policy_document" "sentry" {
  statement {
    actions = [
      "s3:AbortMultipartUpload",
      "s3:DeleteObject",
      "s3:GetObject",
      "s3:GetObjectAcl",
      "s3:GetObjectTagging",
      "s3:ListBucket",
      "s3:ListMultipartUploadParts",
      "S3:ListObjects",
      "s3:PutObject",
      "s3:PutObjectAcl",
      "s3:PutObjectTagging"
    ]
    resources = [
      module.sentry_bucket.s3_bucket_arn,
      "${module.sentry_bucket.s3_bucket_arn}/*",

    ]
  }
}

/*
  ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Define IRSA role/policies to be assumed by sentry pods                                                             │
  │ see more: https://itnext.io/aws-eks-openid-connect-and-serviceaccounts-40e01fbed55f                                │
  │                                                                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 */
module "sentry_irsa" {
  source  = "aws-ia/eks-blueprints-addon/aws"
  version = "1.1.0"

  create_release         = false
  create_role            = true
  role_name              = "sentry-iam-role"
  role_name_use_prefix   = false
  role_description       = "Provides permissions to handle s3 ops for the sentry pods (sourcemaps/files associated with releases) in the eks cluster"
  create_policy          = true
  policy_name            = "sentry-iam-role-policy"
  policy_description     = "Provides permissions to handle s3 ops for the sentry pods (sourcemaps/files associated with releases) in the eks cluster"
  policy_name_use_prefix = false
  policy_statements      = data.aws_iam_policy_document.sentry.statement

  assume_role_condition_test = "StringLike"

  oidc_providers = {
    this = {
      provider_arn    = module.eks.oidc_provider_arn
      namespace       = "sentry"
      service_account = "*"
    }
  }

  tags = local.tags

  depends_on = [module.sentry_bucket]
}

```

important to note here is that this will provision a single IAM role, as current sentry chart is unfortunately does define service accounts for the workload in a weird way (single annotation is shared across all service accounts, yet it has multiple  serviceaccounts for different workloads of the sentry).

**assume_role_condition_test = "StringLike"** 

Then in your HELM chart you will need to set:

```yaml
serviceAccount:
  enabled: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNTID:role/sentry-iam-role-policy

filestore:
  backend: s3
  s3:
    bucketName: project-prod-eks-sentry
    region_name: us-east-1
  persistence:
    persistentWorkers: true
sourcemaps:
  enabled: true
symbolicator:
  cleanup:
    enabled: true
  enabled: true
```
