### ISSUE TITLE
Upgrade to the latest sentry version

### ISSUE THREAD

**Issue by fibis** [sentry-kubernetes/charts#541]
The sentry version of this chart is pretty old. It would be great, if this could be updated.

**Comment by flowbe** [comment]
Hello, this would be really great. A lot of changes were introduced since version 21.8.0 (the one available in this chart), especially the debug symbols download from App Store Connect for iOS. We'd really need this feature but we're dependent on this repo…

**Comment by dnplkndll** [comment]
can't you just spec the image tag in the values.yml? there may be other implications of course. Chart.AppVersion is just the default. 
```
images:
  sentry:
    # repository: getsentry/sentry
    # tag: Chart.AppVersion
    # pullPolicy: IfNotPresent
    imagePullSecrets: []
```
