### ISSUE TITLE
 "system.url-prefix" is not working 

### ISSUE THREAD

**Issue by bhargavsunkara9** [sentry-kubernetes/charts#573]
Hello Guys, 
I tried setting the system.url in values.yml file
```
system:
  url: "https://rewrite.bar.com"
```

Here is my ingress nginx
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rewrite
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: rewrite.bar.com
    http:
      paths:
      - path: /something(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sentry-nginx
            port: 
              number: 80
```
When i try to login to https://rewrite.bar.com/something the URL is not redirecting to sentry-ngnix and the sentry authentication page does not come up.

What am i doing wrong?
