### ISSUE TITLE
Provide a default postgresql password

### ISSUE THREAD

**Issue by robjuz** [sentry-kubernetes/charts#579]
To avoid confusions and simplify the initial deployment, a default postgresql password should be set. See #571

The documentation should also give the user a hint to change this password due to security risks.

**Comment by bhargavsunkara9** [comment]
Hello,

So when ```postgresqlPassword``` is set it should work right?

**Comment by pierreyves-lebrun** [comment]
I would advocate against adding a default password, which can be considered as an anti-pattern since it encourages users to provide passwords in plain text, which might end up in version control.

A better, gitops friendly approach would consists in letting the user specify a secret. Something like the following could be added to sentry chart:

```
postgresql:
  # Specify a secret in order to prevent bitnami postgres chart from generating a new password upon every upgrade
  # existingSecret: sentry-postgresql
```

Or in the case of more recent versions of bitnami postgres:

```
postgresql:
  # auth:
    # Specify a secret in order to prevent bitnami postgres chart from generating a new password upon every upgrade
    # existingSecret: sentry-postgresql
```

`sentry-postgresql` looking like the following:

```
apiVersion: v1
kind: Secret
metadata:
  name: sentry-postgresql
type: Opaque
data:
  postgresql-password: REDACTED
  postgresql-postgres-password: REDACTED
```
