### ISSUE TITLE
support for multiple ingress classes

### ISSUE THREAD

**Issue by partheshparekh** [sentry-kubernetes/charts#604]
Need public endpoint which serve application error on `/api/` and another endpoint for sentry dashboard

example:
```yaml
ingress:
  annotations: {}
  host: dashboard.testonly.net

publicIngress:
  annotations: {}
  host: error.testonly.com
  path:
    - /api/
```
