### ISSUE TITLE
Custom PVC annotations on non big 3 cloud provider with ArgoCD

### ISSUE THREAD

**Issue by tech4242** [sentry-kubernetes/charts#605]
I am working with the German provider Open Telekom Cloud (OTC) where I use ArgoCD + these Helm charts to deploy Sentry. So far so good and I have used the following yaml to deploy sentry and override the values.yaml I needed to setup the nginx-ingress (which worked like a charm:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
# ...
  # ...
  source:
    repoURL: https://sentry-kubernetes.github.io/charts
    chart: sentry
    targetRevision: 13.0.1
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hostname: ...
          tls:
```

Now I want to do a similar exercise to override the PVCs for each service e.g. clickhouse because OTC uses different StorageClasses so the default stuff in values.yaml:

```yaml
clickhouse:
  enabled: true
  #...
  persistentVolumeClaim:
        enabled: true
        dataPersistentVolume:
          enabled: true
          accessModes:
            - "ReadWriteOnce"
          storage: "30Gi"
```

I thought I can do something similar to the nginx-ingress override from above:

```yaml
  helm:
    values: |
      clickhouse:
        persistentVolumeClaim:
          enabled: true
          dataPersistentVolume:
            enabled: true
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
            parameters:
              accessModes:
                - ReadWriteMany
              size: 30Gi
              csi.storage.k8s.io/csi-driver-name: disk.csi.everest.io
              csi.storage.k8s.io/fstype: ext4
              everest.io/disk-volume-type: SATA
              everest.io/passthrough: "true"
            mountPath: /var/lib/sentry/files
            provisioner: everest-csi-provisioner
            reclaimPolicy: Retain
            volumeBindingMode: Immediate
```

but none of the values are being applied and I don't even get errors (that helped with nginx initially)

Any idea how I can get this up and running actually override the values.yaml for the PVCs? At the very least I should be getting errors

P.S.: this is what storage looks like on the OTC:

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-disk-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  csi.storage.k8s.io/csi-driver-name: disk.csi.everest.io
  csi.storage.k8s.io/fstype: ext4
  everest.io/disk-volume-type: SATA
  everest.io/passthrough: "true"
provisioner: everest-csi-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
