### ISSUE TITLE
Can't change zookeeper's storageClass in values.yaml - pods failing

### ISSUE THREAD

**Issue by tech4242** [sentry-kubernetes/charts#606]
We are using a cloud provider where leaving the `storageClass` for PVC blank/empty does not create PVCs and instead leaves the system in pending status, so we need to manually change the `storageClass`, which is described more or less if you dig into the values.yaml file of these charts.

The magic needed is `storageClass: csi-disk`, which let's our cloud provider know it can attach PVCs of that type (instead of doing nothing as described above)

What we've done below also matches the values.yaml provided by bitnami: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml, which we are supposed to check as mentioned in your charts' values.yaml: https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L714 

AND all the other Bitnami charts work (PGDB etc.) I have left one example below and commented out the rest.

but no matter what I do I cannot get `storageClass` parsed in as the `desiredManifest` and I can't do I live manifest change since it's a StatefulSet, so I somehow need to get `storageClass` parsed correctly. 

Already spent quite a lot of time trying everything, looking for typos etc.

We use Helm and ArgoCD and this is the ArgoCD app:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sentry
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://sentry-kubernetes.github.io/charts
    chart: sentry
    targetRevision: 13.0.1
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hostname: ...
          tls:
          # ...
        clickhouse:
          # ..
        filestore:
          # ..
        redis:
          master:
          #...
          replica:
          #...
        rabbitmq:
          persistence:
            enabled: true
            annotations:
              everest.io/disk-volume-type: SSD
            labels:
              failure-domain.beta.kubernetes.io/region: eu-de
              failure-domain.beta.kubernetes.io/zone: 
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
            storageClass: csi-disk
        kafka:
        # ...
        postgresql:
        # ...
        zookeeper:
          enabled: true
          persistence:
            enabled: true
            annotations:
              everest.io/disk-volume-type: SSD
            labels:
              failure-domain.beta.kubernetes.io/region: eu-de
              failure-domain.beta.kubernetes.io/zone: 
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
            storageClass: csi-disk
            storageClassName: csi-disk # tried both storageClass and storageClassName, together and separately!
```

The desired manifest is always stuck at:

```yaml
  volumeClaimTemplates:
    - metadata:
        annotations: null
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
```

so neither the metadata, nor the spec is changed. also tried with the Gigs for the storage request. basically the whole zookeeper part is not being parsed and there are no sync errors or syntax errors.

**Comment by zhongweili2010** [comment]
Did not read careful, the template used in this storageclass field is in _storage.tpl under common subchart.

**Comment by tech4242** [comment]
> We are using a cloud provider where leaving the `storageClass` for PVC blank/empty does not create PVCs and instead leaves the system in pending status, so we need to manually change the `storageClass`, which is described more or less if you dig into the values.yaml file of these charts.
> 
> The magic needed is `storageClass: csi-disk`, which let's our cloud provider know it can attach PVCs of that type (instead of doing nothing as described above)
> 
> What we've done below also matches the values.yaml provided by bitnami: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml, which we are supposed to check as mentioned in your charts' values.yaml: https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L714
> 
> AND all the other Bitnami charts work (PGDB etc.) I have left one example below and commented out the rest.
> 
> but no matter what I do I cannot get `storageClass` parsed in as the `desiredManifest` and I can't do I live manifest change since it's a StatefulSet, so I somehow need to get `storageClass` parsed correctly.
> 
> Already spent quite a lot of time trying everything, looking for typos etc.
> 
> We use Helm and ArgoCD and this is the ArgoCD app:
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: sentry-dev
>   namespace: argocd
>   finalizers:
>   - resources-finalizer.argocd.argoproj.io
> spec:
>   destination:
>     namespace: sentry
>     server: https://kubernetes.default.svc
>   project: default
>   source:
>     repoURL: https://sentry-kubernetes.github.io/charts
>     chart: sentry
>     targetRevision: 13.0.1
>     helm:
>       values: |
>         ingress:
>           enabled: true
>           annotations:
>             kubernetes.io/ingress.class: nginx
>             nginx.ingress.kubernetes.io/use-regex: "true"
>             nginx.ingress.kubernetes.io/ssl-redirect: "true"
>             nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
>             cert-manager.io/cluster-issuer: "letsencrypt-prod"
>           hostname: ...
>           tls:
>           # ...
>         clickhouse:
>           # ..
>         filestore:
>           # ..
>         redis:
>           master:
>           #...
>           replica:
>           #...
>         rabbitmq:
>           persistence:
>             enabled: true
>             annotations:
>               everest.io/disk-volume-type: SSD
>             labels:
>               failure-domain.beta.kubernetes.io/region: eu-de
>               failure-domain.beta.kubernetes.io/zone: 
>             accessModes:
>             - ReadWriteOnce
>             resources:
>               requests:
>                 storage: 8Gi
>             storageClass: csi-disk
>         kafka:
>         # ...
>         postgresql:
>         # ...
>         zookeeper:
>           enabled: true
>           persistence:
>             enabled: true
>             annotations:
>               everest.io/disk-volume-type: SSD
>             labels:
>               failure-domain.beta.kubernetes.io/region: eu-de
>               failure-domain.beta.kubernetes.io/zone: 
>             accessModes:
>             - ReadWriteOnce
>             resources:
>               requests:
>                 storage: 8Gi
>             storageClass: csi-disk
>             storageClassName: csi-disk # tried both storageClass and storageClassName, together and separately!
> ```
> 
> The desired manifest is always stuck at:
> 
> ```yaml
>   volumeClaimTemplates:
>     - metadata:
>         annotations: null
>         name: data
>       spec:
>         accessModes:
>           - ReadWriteOnce
>         resources:
>           requests:
>             storage: 8Gi
> ```
> 
> so neither the metadata, nor the spec is changed. also tried with the Gigs for the storage request. basically the whole zookeeper part is not being parsed and there are no sync errors or syntax errors.

hey I assume you are referring to https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/common/templates/_storage.tpl but what exactly do you mean?

**Comment by tech4242** [comment]
> Did not read careful, the template used in this storageclass field is in _storage.tpl under common subchart.

hey I assume you are referring to https://github.com/bitnami/charts/blob/70d602fea38010145c20e1ca59be06e4cf32bf80/bitnami/common/templates/_storage.tpl but what exactly do you mean?

**Comment by shian15810** [comment]
@tech4242 There is another zookeeper, which is a dependency of kafka

In this case I think what you need is:

```yaml
kafka:
  persistence:
    storageClass: csi-disk
  zookeeper:
    persistence:
      storageClass: csi-disk
```
