### ISSUE TITLE
Support using secret to define external postgres password

### ISSUE THREAD

**Issue by lfdominguez** [sentry-kubernetes/charts#613]
https://github.com/sentry-kubernetes/charts/blob/41932aabba05d0b3095f992818e34511309d4799/sentry/templates/cronjob-sentry-cleanup.yaml#L77

**Comment by lfdominguez** [comment]
I'm deploying sentry using the helm chart and using SOPS to encrypt every secrets file on my GitOps repository, this helm chart doesn't support specify the external postgres password as a secret, but i found a workaround that is replace the all 22 `env` config value of helm values file like this:

```
- name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
            name: sentry-values-secrets
            key: postgresql-password
```

But this CronJob (`sentry-cleanup`) directly don't use this envs and set the clear text password get from values file of helm deployment.
