### ISSUE TITLE
sentry-snuba-migrate Error when upgrading to 14.0.0 chart

### ISSUE THREAD

**Issue by lluczaj** [sentry-kubernetes/charts#618]
I use Sentry version 21.5.0 (Chart version 11) and want to upgrade to latest 14.0.0 version. I use externalClickhouse version deployed with this chart:
https://github.com/sentry-kubernetes/charts/tree/develop/clickhouse

When I run the upgrade there are jobs for sentry-snuba-migrate that fails with
```
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (localhost:9000)
```

I wonder why it fails and tries to connect to localhost ? I have proper configuration in `externalClickhouse:` section. Should this job successfully connect and start migration also for external Clickhouse instance ?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by visla-xugeng** [comment]
@lluczaj I had similar issue but my one is related to user Authentication failed. I installed an external clickhouse by ClickHouse-Operator. (https://github.com/Altinity/clickhouse-operator)
My CH installation has an internal LB as service for connection purpose. 

```
kubectl -n clickhouse get svc
service-ch-install                   LoadBalancer   172.20.57.73   xxxxxxxxxxxxxxxxxxxx.elb.us-west-1.amazonaws.com 8123:32454/TCP,9000:31189/TCP   4h33m
```

```
externalClickhouse:
  host: "xxxxxxxxxxxxxxxxxxxx.elb.us-west-1.amazonaws.com"
  username: default
  password: ""
  singleNode: false
  clusterName: ch-cluster
```
Then got the error below
```
DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name.
```
