### ISSUE TITLE
Volume existing Claims 

### ISSUE THREAD

**Issue by T1loc** [sentry-kubernetes/charts#63]
It would be nice to have this options in order to use an existing volume
```
filestore:
  filesystem:
    persistence:
      enabled: true
      existingClaim: "sentry"
```
