### ISSUE TITLE
Zookeeper and Kafka sub charts don't take care of securityContext as expected.

### ISSUE THREAD

**Issue by inductor** [sentry-kubernetes/charts#630]
I need to deploy pods with PVC running as root. I tried the following but the generated YAML file doesn't change the values as expected and instead returns `runAsUser: 1001` which is the default.

```
zookeeper:
  containerSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
  volumePermissions:
    enabled: true

kafka:
  podSecurityContext:
    runAsUser: 0
    runAsNonRoot: false
```

If it's fixed in later version of those charts, please update them.
