### ISSUE TITLE
Error: can't get a valid version for repositories redis, kafka, rabbitmq, postgresql, nginx.

### ISSUE THREAD

**Issue by RaduDumi** [sentry-kubernetes/charts#637]
I'm getting the following error:
`Error: can't get a valid version for repositories redis, kafka, rabbitmq, postgresql, nginx. Try changing the version constraint in Chart.yaml`

The problem was fixed as soon as I updated the versions in Chart.yaml:
```
apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 14.1.1
appVersion: 22.5.0
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.7.6
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 14.9.3
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.1.2
    condition: clickhouse.enabled
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.0
    condition: clickhouse.enabled,zookeeper.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.32.2
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.14.4
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 9.6.2
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
```
