### ISSUE TITLE
Add metrics relabelings for service Monitor

### ISSUE THREAD

**Issue by Grounz** [sentry-kubernetes/charts#642]
Is your feature request related to a problem? Please describe.
When we deploy sentry with helm-charts we want apply a relabeling on serviceMonitor Endpoint

Describe the solution you'd like
In the values.yaml file we want set a field relabelings which add relabelings object in the serviceMonitor:

Exemple:

Values.yaml:
```yaml
serviceMonitor:
  enabled: false
  additionalLabels: {}
  namespace: ""
  namespaceSelector: {}
  relabelings:
     - action: replace
       regex: (.*)
       replacement: MyLabel
       sourceLabels:
       - mySourceLabel
       targetLabel: MyNewLabel
```

ServiceMonitor [template](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/servicemonitor-metrics.yaml#L18):

```yaml
endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    {{- if .Values.metrics.serviceMonitor.honorLabels }}
    honorLabels: true
    {{- if .Values.controller.metrics.serviceMonitor.relabelings }}
    relabelings: {{ toYaml .Values.controller.metrics.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
```
Environment details (remove if not applicable):

    Kubernetes version: 1.22
    Cloud-provider/provisioner: OVH
    Install method: e.g. helm

/kind feature
