### ISSUE TITLE
connecting external kafka with sasl?

### ISSUE THREAD

**Issue by brianchan661** [sentry-kubernetes/charts#656]
From what I understand, the externalKafka only support to specifying host and port.  
```
# from values.yaml
externalKafka:  
  host: "kafka-confluent"  
  port: 9092  
```

If I am having a kafka (e.g. confluent cloud kafka) which require sasl authentication, 
Do I have any way to set it up?
