### ISSUE TITLE
Adding Secrets for S3 Filestore Access and Secret Keys

### ISSUE THREAD

**Issue by courtneygreif** [sentry-kubernetes/charts#773]
Adding in secrets for the S3 filestore access and secret keys so the values do not need to be in plaintext

https://github.com/sentry-kubernetes/charts/pull/788/

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by Mokto** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by eht16** [comment]
Just for the records and @courtneygreif:

at least in the meantime it's possible. The following config is working for me:
```yaml
filestore:
  backend: s3
  filesystem: {}
  s3:
    existingSecret: sentry
    accessKeyIdRef: s3-accessKey
    secretAccessKeyRef: s3-secretKey
    bucketName: sentry-data
    endpointUrl: XXX
    region_name: XXX
```

It requires an existing secret named "sentry" with the keys "s3-accessKey" and "s3-secretKey".
