### ISSUE TITLE
CSRF error when performing POST/PUT 

### ISSUE THREAD

**Issue by stabacco** [sentry-kubernetes/charts#784]
I have recently deployed the chart on CGP and I  can access it from the web as expected, however anytime I try to perform any write operation (like marking an issue as resolved for example ) I'm getting this error: 

```
CSRF Failed: Referer checking failed - https://sentry.skodel.dev/organizations/sentry/issues/ does not match any trusted origins.
```

I realize this come from the underlying django app, but I'm just not sure which settings have to be changed in the yaml template in order to set those origins. 
These are my current settings: 

```
 CHART                           APP VERSION
 sentry-17.7.0                   22.10.0    
 ingress-nginx-4.4.0             1.5.1      
```

and my `values.yaml` looks like this: 

```



ingress:
  enabled: true
  # If you are using traefik ingress controller, switch this to 'traefik'
  # if you are using AWS ALB Ingress controller, switch this to 'aws-alb' 
  regexPathStyle: nginx

  annotations: 
    kubernetes.io/name: sentry-nginx
    kubernetes.io/ingress.class: sentry-nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-sentry
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.global-static-ip-name: ${sentry_static_ip_address_name}
    nginx.ingress.kubernetes.io/upstream-vhost: ${sentry_host}

  spec:
    ingressClassName: sentry-nginx
    
  hostname: ${sentry_host}
  additionalHostNames: ["sentry-sentry-web"]
 
  tls:
    - hosts:
        - ${sentry_host}
      secretName: sentry-tls-2


config:
  # No YAML Extension Config Given
  configYml: {
    system.url-prefix: "https://${sentry_host}"
  }
  sentryConfPy: |
    # No Python Extension Config Given
  snubaSettingsPy: |
    # No Python Extension Config Given
  relay: |
    # No YAML relay config given

```

details from the request: 
```
{
insertId: "iy6yx4wgvpgetmoc"
labels: {5}
logName: "projects/skodel/logs/stderr"
receiveTimestamp: "2022-11-16T05:57:16.057817667Z"
resource: {2}
severity: "ERROR"
textPayload: "05:57:15 [WARNING] django.request: Forbidden: /api/0/projects/sentry/internal/issues/ (status_code=403 request=<WSGIRequest: PUT '/api/0/projects/sentry/internal/issues/?id=4'>)"
timestamp: "2022-11-16T05:57:15.602800145Z"
}

```
Any help would be greatly appreciated.
