### ISSUE TITLE
executing "sentry/charts/nginx/templates/tls-secrets.yaml" at <.name>: can't evaluate field name in type interface {}

### ISSUE THREAD

**Issue by patsevanton** [sentry-kubernetes/charts#807]
Thanks for sentry-kubernetes

Try Install sentry to kubernetes with letsencrypt
```
helm upgrade --install --wait  -n sentry sentry sentry/sentry -f value-sentry.yaml --timeout 10m
```

with value-sentry.yaml
```
nginx:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    enabled: true
    hostname: sentry.xxxxxxx
    ingressClassName: "nginx"
    secrets:
      secretName: "letsencrypt-prod"
    tls: true
```

Get error
```
Error: UPGRADE FAILED: template: sentry/charts/nginx/templates/tls-secrets.yaml:7:11: executing "sentry/charts/nginx/templates/tls-secrets.yaml" at <.name>: can't evaluate field name in type interface {}
```

**Comment by patsevanton** [comment]
Worked value https:
```
nginx:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    enabled: true
    hostname: sentry.xxxxxxx
    ingressClassName: "nginx"
    tls: true
```
