### ISSUE TITLE
Is there a way to automatically clear zookeeper-clickhouse periodically？

### ISSUE THREAD

**Issue by icewisb** [sentry-kubernetes/charts#809]
I hava to exec to the pod an execute this command periodically
```shell
# ./opt/bitnami/zookeeper/bin/zkCleanup.sh -n 5
```

Is there a better way to do this?

**Comment by pyromaniac3010** [comment]
@icewisb I had the same problem. The bitnamit zookeeper chart has an option to enable automatic purging, which is disabled by default: https://github.com/bitnami/charts/blob/d009cba8bbb12472ba95fe52d3aef6598d1e2984/bitnami/zookeeper/values.yaml#L182
```
## Ongoing data directory cleanup configuration
##
autopurge:
  ## @param autopurge.snapRetainCount The most recent snapshots amount (and corresponding transaction logs) to retain
  ##
  snapRetainCount: 3
  ## @param autopurge.purgeInterval The time interval (in hours) for which the purge task has to be triggered
  ## Set to a positive integer to enable the auto purging
  ##
  purgeInterval: 0
```
