### ISSUE TITLE
CrashLoopBackOff for several pods if using clickhouse with non default user and defined password

### ISSUE THREAD

**Issue by pyromaniac3010** [sentry-kubernetes/charts#812]
I setup the sentry helm chart with the new bitnami clickhouse chart https://github.com/bitnami/charts/tree/main/bitnami/clickhouse as "externalClickhouse":
```
externalClickhouse:
  ## Hostname or ip address of external clickhouse
  ##
  host: "mgmt-k8s1-sentry-clickhouse"
  singleNode: false
  clusterName: "default"
  username: "foo"
  password: "bar"
```
This chart typically sets a password for the admin-user, which is actually good for security.
I was able to run the setup for sentry helm and everything looked good at the beginning.
I then found out, that the following pods where in a CrashLoopBackOff:
1. sentry-snuba-consumer
2. sentry-snuba-outcomes-consumer
3. sentry-snuba-transactions-consumer
The reason was:
`urllib3.exceptions.HTTPError: Received unexpected 403 response: Code: 516. DB::Exception: Received from mgmt-k8s1-sentry-clickhouse-shard0-2.mgmt-k8s1-sentry-clickhouse-headless.sentry.svc.cluster.local:9000. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.`

So these three pods do not authenticate correctly with clickhouse. They completely ignore the provided username and password.
I also tried to manualle run "snuba consumer --storage outcomes_raw --auto-offset-reset earliest --max-batch-size 3" from within the running snuba-api container and it failed with an error about a authentication problem with clickhouse port 8123.

The only way to get sentry up and running with the bitnami clickhouse chart was by removing the password protection from bitnami clickhouse chart and setting the username to "default" by using the following values for the bitnami/clickhouse chart:
```
auth:
  username: default
  existingSecret: mgmt-k8s1-sentry-snuba-env
  existingSecretKey: CLICKHOUSE_PASSWORD
extraEnvVars:
  - name: ALLOW_EMPTY_PASSWORD
    value: "yes"
```
