### ISSUE TITLE
Setting PVC sizes for dependencies

### ISSUE THREAD

**Issue by magikmw** [sentry-kubernetes/charts#824]
Context:  
I'm using a k3s cluster with longhorn storage backend. It's for testing purposes, I'm setting up some CI/CD apps like sentry to see how they work and if they could be useful for our devs.  
Storage is quite limited on the cluster, so default config fails when trying to setup sentry from this chart.

What I've managed to do:  
I figured out how to modify PVCs for the sentry chart itself, but I can't figure out the syntax needed for dependencies. Each claims 8GB and jams up Longhorn.

My current values.yaml file:  
```yaml
---

clickhouse:
  clickhouse:
    persistentVolumeClaim:
      enabled: true
      dataPersistentVolume:
        enabled: true
        accessModes:
          - "ReadWriteOnce"
        storage: "3Gi"

filestore:
  filesystem:
    persistence:
      size: 2Gi
```

What would the syntax be for dependency charts? Any help would be appreciated.

**Comment by source-xm** [comment]
![image](https://user-images.githubusercontent.com/15379012/218035424-289cabbe-ed34-4f95-9660-5290501b5977.png)

**Comment by rkmudunuru** [comment]
@magikmw - Try this out for the below clickhouse (17.0.0 chart version)

```
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "20.8.19.4"
    configmap:
      remote_servers:
        internal_replication: true
        replica:
          backup:
            enabled: false
      zookeeper_servers:
        enabled: true
        config:
          - index: "clickhouse"
            hostTemplate: "{{ .Release.Name }}-zookeeper-clickhouse"
            port: "2181"
        persistence:
          size: 150Gi #### Update your size here for zoookeper
      users:
        enabled: false
        user:
          # the first user will be used if enabled
          - name: default
            config:
              password: ""
              networks:
                - ::/0
              profile: default
              quota: default

    persistentVolumeClaim:
      enabled: true
      dataPersistentVolume:
        enabled: true
        accessModes:
          - "ReadWriteOnce"
        storage: "250Gi" #### Update your size here
```
