### ISSUE TITLE
click-house zookeeper missing values for increasing the size of PVC

### ISSUE THREAD

**Issue by harishgopi** [sentry-kubernetes/charts#838]
The sentry clickhouse uses zookeeper for storing metadata and the storage is full now and I increased the pvc storage manually but there is no values in this helm chart's [values file](https://github.com/sentry-kubernetes/charts/blob/develop/clickhouse/values.yaml#:~:text=Contains%20settings%20that%20allow%20ClickHouse%20to%20interact%20with%20a%20ZooKeeper%20cluster.). Can anyone suggest how to persist this change in the helm chart values file or correct me if am wrong anywhere.

thank you in advance.

**Comment by brzd-me** [comment]
sentry.yml:
```
zookeeper:
    persistence:
      size: 32Gi
    autopurge:
      ## @param autopurge.snapRetainCount The most recent snapshots amount (and corresponding transaction logs) to retain
      snapRetainCount: 3
      ## @param autopurge.purgeInterval The time interval (in hours) for which the purge task has to be triggered
      ## Set to a positive integer to enable the auto purging
      purgeInterval: 48
```
