### ISSUE TITLE
Using chart without dnCheck env results in an invalid manifest

### ISSUE THREAD

**Issue by jhuitema** [sentry-kubernetes/charts#844]
## Expected Behavior

When I use the sentry helm chart with default values, the created resources should be valid.

## Actual Behavior

When the helm chart is run, the `sentry-db-check` job is created with `env: null`. This passes validation on `kubectl apply` but causes issues with the kube-proxy controller as brought up on [this issue](https://github.com/kubernetes/kubernetes/issues/57705). This results in IP addresses created within the cluster to not be reachable.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "-1"
  labels:
    app: sentry
    app.kubernetes.io/created-by: sentry
    app.kubernetes.io/managed-by: sentry
    chart: sentry-17.0.0
    heritage: Helm
    release: sentry
  name: sentry-db-check
  namespace: sentry
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
     <snip>
      name: sentry-db-check
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          <snip>
        env: null
        image: subfuzion/netcat:latest
        imagePullPolicy: IfNotPresent
        name: db-check
        <snip>
      restartPolicy: Never
```

(See `spec.template.spec.containers[0].env`)

## Steps to Reproduce the Problem

1.  Run the sentry helm chart without specifying an `env` for the `dbCheck` hook in the values.yaml: https://github.com/sentry-kubernetes/charts/blob/17.0.0/sentry/values.yaml#L466
1. Apply the created manifest to a k8s cluster
1. Watch the `kube-proxy` pod for the node that the `sentry-db-check` have errors connecting to watch streams.

## Possible Fixes

I _think_ the solution to this would be to add an `else` condition within the `sentry-db-check` job template [here](https://github.com/sentry-kubernetes/charts/blob/17.0.0/sentry/templates/hooks/sentry-db-check.job.yaml#L140-L143):

```diff
                if [ "$KAFKA_STATUS" -eq 0 ]; then
                  echo "Kafka not ready. Sleeping for 10s before trying again"
                  sleep 10;
                fi
              done
              echo "Kafka is up"
-         env:
  {{- if .Values.hooks.dbCheck.env }}
+         env:
  {{ toYaml .Values.hooks.dbCheck.env | indent 8 }}
+ {{- else }}
+         env: []
  {{- end }}
          resources:
  {{ toYaml .Values.hooks.dbCheck.resources | indent 10 }}
        {{- if .Values.hooks.shareProcessNamespace }}
        shareProcessNamespace: {{ .Values.hooks.shareProcessNamespace }}
        {{- end }}
  {{- end }}
```

## Other Notes

I don't know whether it's relevant but we are using kustomize's [helmChartInflationGenerator](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_) to call the Helm chart.

## Specifications

  - Chart Version: 17.0.0
  - Helm Version: 3.9.4
  - Kubernetes Version: 1.24.2
  - Kustomize Version: 4.5.4
  - Platform: Linux/amd64
