### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Sanoj-kumar-DevOps** [sentry-kubernetes/charts#865]
Following the upgrade of k8s from version 1.21 to 1.25, certain deprecations occurred which caused Sentry to fail. As we hadn't upgraded Sentry in a while, we had to perform a fresh installation. However, after the installation, Sentry was unable to pass through the web due to SSL verification problems. This issue arose subsequent to the upgrade of the helm chart from version 11.5.0 to 17.5.0.

```

 File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake                   │
│     self._sslobj.do_handshake()                                                        │
│ ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail │
│                                                                                        │
│ During handling of the above exception, another exception occurred:                    │
│                                                                                        │
│ Traceback (most recent call last):                                                     │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", lin │
│     self._send_envelope(envelope)                                                      │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", lin │
│     self._send_request(                                                                │
│   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 263, in patc │
│     return _send_request(*args, **kwargs)                                              │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", lin │
│     response = self._pool.request(                                                     │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 78, │
│     return self.request_encode_body(                                                   │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 170 │
│     return self.urlopen(method, url, **extra_kw)                                       │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/poolmanager.py", line │
│     response = conn.urlopen(method, u.request_uri, **kw)                               │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", l │
│     return self.urlopen(                                                               │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", l │
│     return self.urlopen(                                                               │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", l │
│     return self.urlopen(                                                               │
│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", l │
│     retries = retries.increment(                                                       │

│   File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/retry.py", line  │
│     raise MaxRetryError(_pool, url, error or ResponseError(cause))                     │
│port=443): Max retries exceeded with url: /api/1 ││ 09:09:22 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk                                                                     ││ 09:09:40 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.home.HomeView' response=302 user_id='None' is_ ││ 09:09:40 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.auth_login.AuthLoginView' response=302 user_id ││ 09:09:40 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.auth_organization_login.AuthOrganizationLoginV 
```

**Comment by Sanoj-kumar-DevOps** [comment]
Current Values.yaml
```
asHook: true
clickhouse:
  clickhouse:
    persistentVolumeClaim:
      dataPersistentVolume:
        enabled: true
        storage: 20G
      enabled: true
    replicas: "1"
    resources:
      limits:
        cpu: 1024m
        memory: 3Gi
      requests:
        cpu: 256m
        memory: 512Mi
  clusterDomain: k8s.tool.loc
  enabled: true
externalPostgresql:
  database: sentry
  host: 1paddress
  password: sentry
  port: 5432
  username: sentry
filestore:
  backend: filesystem
  filesystem:
    path: /var/lib/sentry/files
    persistence:
      accessMode: ReadWriteMany
      enabled: true
      persistentWorkers: true
      size: 30G
      storageClass: vsphere-read-write-many-retain
hooks:
  dbInit:
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-password
    - name: SENTRY_EMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-password
  removeOnSuccess: false
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
  enabled: true
  hostname: sentry.company.cz
  tls:
  - hosts:
    - sentry.company.cz
    secretName: sentry-public-tls-tool
kafka:
  clusterDomain: k8s.tool.loc
  enabled: true
  persistence:
    size: 8G
  resources:
    limits:
      cpu: 1024m
      memory: 3Gi
    requests:
      cpu: 256m
      memory: 512Mi
  zookeeper:
    persistence:
      size: 8G
mail:
  backend: smtp
  from: noreply@company.cz
  host: smtp.office365.com
  password: ""
  port: 587
  useTls: true
  username: technical@company.cz
metrics:
  enabled: true
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 32m
      memory: 64Mi
nginx:
  enabled: false
postgresql:
  enabled: false
rabbitmq:
  enabled: false
redis:
  cluster:
    enabled: false
  clusterDomain: k8s.tool.loc
  enabled: true
  master:
    persistence:
      size: 8G
  nameOverride: sentry-redis
relay:
  resources:
    limits:
      cpu: 256m
      memory: 600Mi
    requests:
      cpu: 64m
      memory: 200Mi
sentry:
  cleanup:
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-password
    - name: SENTRY_EMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-password
  cron:
    resources:
      limits:
        cpu: 256m
        memory: 600Mi
      requests:
        cpu: 64m
        memory: 200Mi
  features:
    orgSubdomains: false
  ingestConsumer:
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-password
    - name: SENTRY_EMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-password
    resources:
      limits:
        cpu: 256m
        memory: 600Mi
      requests:
        cpu: 64m
        memory: 200Mi
  postProcessForward:
    resources:
      limits:
        cpu: 256m
        memory: 600Mi
      requests:
        cpu: 64m
        memory: 200Mi
  singleOrganization: true
  web:
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-password
    - name: SENTRY_EMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-password
    probeInitialDelaySeconds: 60
    replicas: 1
    resources:
      limits:
        cpu: 256m
        memory: 600Mi
      requests:
        cpu: 64m
        memory: 200Mi
    strategyType: Recreate
  worker:
    autoscaling:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      targetCPUUtilizationPercentage: 70
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-password
    - name: SENTRY_EMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: smtp-password
    replicas: 1
    resources:
      limits:
        cpu: 1024m
        memory: 3Gi
      requests:
        cpu: 256m
        memory: 512Mi
snuba:
  api:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  clusterDomain: k8s.tool.loc
  consumer:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  outcomesConsumer:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  replacer:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  sessionsConsumer:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  transactionsConsumer:
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
system:
  secretKey: NcxiVcHLtMDu86NISmnKLuGRwdwdddawdawdawdwdawdawdwdawdawdawdadqawawdawdawdawwnmSmelsKe6ZFdywkNa5okSvBGo
user:
  create: false
x-big-resources:
  resources:
    limits:
      cpu: 1024m
      memory: 3Gi
    requests:
      cpu: 256m
      memory: 512Mi
x-env-setting:
  env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: pg-password
  - name: SENTRY_EMAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: smtp-password
x-medium-resources:
  resources:
    limits:
      cpu: 256m
      memory: 600Mi
    requests:
      cpu: 64m
      memory: 200Mi
x-small-resources:
  resources:
    limits:
      cpu: 128m
      memory: 128Mi
    requests:
      cpu: 32m
      memory: 64Mi

```
