### ISSUE TITLE
1 node(s) had volume node affinity conflict

### ISSUE THREAD

**Issue by juliusoh** [sentry-kubernetes/charts#869]
Clickhouse, zookeeper, rabbitmq having trouble selecting nodes

```
`clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "20.8.19.4"
    persistence: 
      storageClass: "gp2"
    nodeSelector:
      serverType: sentry
      serverSubtype: sentry
    configmap:
      remote_servers:
        internal_replication: true
        replica:
          backup:
            enabled: false
      zookeeper_servers:
        enabled: true
        nodeSelector:
          serverType: sentry
          serverSubtype: sentry
        config:
          - index: "clickhouse"
            hostTemplate: "{{ .Release.Name }}-zookeeper-clickhouse"
            port: "2181"
      users:
        enabled: false
        user:
          # the first user will be used if enabled
          - name: default
            config:
              password: ""
              networks:
                - ::/0
              profile: default
              quota: default

    persistentVolumeClaim:
      enabled: true
      dataPersistentVolume:
        enabled: true
        accessModes:
          - "ReadWriteOnce"
        storage: "30Gi"`
```
