### ISSUE TITLE
Is it ready for production / anyone using it in production?

### ISSUE THREAD

**Issue by fzyzcjy** [sentry-kubernetes/charts#877]
Hi thanks for the helpful chart! I wonder whether it is ready for production / anyone using it in production?

**Comment by brianchan661** [comment]
i am using it on production, although there is some bugs ([e.g.](https://github.com/sentry-kubernetes/charts/issues/862)), but so far it is working quite well

**Comment by fzyzcjy** [comment]
@brianchan661 Thanks for the information!

**Comment by xvilo** [comment]
It works quite well generally. However, Sentry’s architecture is quite resource heavy. Als the fact that Sentry saves all raw event data into Postgres has given us issues too. We at some point had a table of almost 500 gigs. 

That can be circumvented with proper clean up crons and DB vacuuming. The cron itself has a default time limit that’s too short, and we implemented a custom cron for the DB vacuuming. 

If you are a somewhat experienced devops person, it’s doable and ready for prod

**Comment by fzyzcjy** [comment]
I see. Thank you!

**Comment by fzyzcjy** [comment]
@brianchan661 @xvilo So, I wonder how much cpu/memory/disk does your self-hosted Sentry use (and what is the rough amount of events per day)? Thanks!

**Comment by brianchan661** [comment]
@fzyzcjy For my sentry, in total, it is using 300core cpu, 400Gb memory and around 3000Gb disk (disk is far more than enough, but it will be hard to increase after you release your services, so more the better).
it is handling around 400k event per hours. 
I guess there are room to reduce the cpu and memory, but i dont have time to try yet.

**Comment by fzyzcjy** [comment]
@brianchan661 Thank you! That sounds like a big cluster. Did you observe linear increase of CPU/memory with the increase of #events? Because currently I do not have that many events, neither that many cpu/memory, so curious about small-scale results.

**Comment by brianchan661** [comment]
When event increase, the main components which CPU/memory will be increased is sentry-worker, and is the top CPU/memory user.  
The value i gave in the previous comment is for my PROD env, 
for my QA, which have only ~20k event/hour, just need 100CPU & memory, and i guess there are also room to reduce

**Comment by fzyzcjy** [comment]
@brianchan661 I see, thank you! Btw curious why QA has 20000 events per hour, IMHO it does not have large QPS

**Comment by brianchan661** [comment]
@fzyzcjy because QA is just used for me to test and development, i dont need that much errors. And client usually they just send all qa and prod events to prod Sentry directly

**Comment by fzyzcjy** [comment]
@brianchan661 I see. Then I am even more curious: So you (one person) generate 20000 events in an hour?

**Comment by brianchan661** [comment]
@fzyzcjy no, some clients are playing on QA env, I don't generate error myself =]

**Comment by fzyzcjy** [comment]
@brianchan661 Oh I see. Then there are really a lot of clients =]

**Comment by acuD1** [comment]
Hi everyones, we're trying to setup sentry on a very restrictive environment. It will run on a 4C/8G single node for the moment. Does anyone succeeded to makes it work with those ressources ? 
Every replicas are set to `1`, redis and postgresql on standalone mode. No rappitmq, we're only using redis. 
If you have succeded, do you have any tips ?

**Comment by sreedharbukya** [comment]
Hello, anyone running on EKS with AWS ALB Controller?
I am unable to get this setup done in the following setup?


```
user:
  create: true
  email: xxxxxx
  password: xxxxx

filestore:
  filesystem:
    persistence:
      persistentWorkers: true
      storageClass: "efs-storage"
      accessMode: ReadWriteMany

nginx:
  enabled: false

rabbitmq:
  enabled: false

ingress:
  enabled: true
  hostname: example.devops.com
  regexPathStyle: aws-alb
  alb:
    httpRedirect: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: devops-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: example.devops.come

kafka:
  zookeeper:
    enabled: false

relay:
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/relay/healthcheck/ready/
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port

sentry:
  web:
    service:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /_health/
        alb.ingress.kubernetes.io/healthcheck-port: traffic-port
  singleOrganization: true
  worker:
    replicas: 2

sourcemaps:
  enabled: true


## Postgres External Service
postgresql:
  enabled: false
externalPostgresql:
  host: XXXXXX 
  port: 5432
  username: postgres
  password: "XXXXX"
  database: sentry
  sslMode: require

## Redis External Service 
redis:
  enabled: true

# externalRedis:
#   port: 6379
#   host: XXXX
#   password: XXXXX
#   sslMode: true

```

Trying to get Sentry working since last couple of days, finally fixed all the errors related to Kafka, EFS Volume, but still get 503 error on Domain.

Please can you guys suggest me what is the right values needed to apply to make it working on AWS EKS with ALB Controller.
