### ISSUE TITLE
External Kafka for sentry

### ISSUE THREAD

**Issue by therus000** [sentry-kubernetes/charts#886]
Good day
what the way to use an external kafka for sentry
```yaml
externalKafka:
  ## Hostname or ip address of external kafka
  ##
  host: "cluster-01-kafka"
  port: 9092
  user: user
  password: password
```
i tried to used this configs. but it now work
i wonder why is there is no setting for topic and it user
can anyone help with this question?

**Comment by brianchan661** [comment]
i am using internal but did you try to set [asHook](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L18) to true, so it will initial the topics?

**Comment by MrRuban** [comment]
@therus000 Hi, I had the same problem. I solved it in the following way

```yaml
snuba:
  dbInitJob:
    env:
    - name: KAFKA_SECURITY_PROTOCOL
      value: SASL_PLAINTEXT
    - name: KAFKA_SASL_MECHANISM
      value: SCRAM-SHA-512
    - name: KAFKA_SASL_USERNAME
      value: user
    - name: KAFKA_SASL_PASSWORD
      value: "password"
```

Remember that the user must have permissions. I use `Yandex Cloud`, the terraform for it looks like this:

```hcl
resource "yandex_mdb_kafka_cluster" "sentry_kafka_dev" {
  name        = "sentry-kafka-dev"
  environment = "PRESTABLE"
  description = "Kafka dev cluster for Sentry stack"
  network_id  = data.yandex_vpc_network.dev.network_id

  subnet_ids = [data.yandex_vpc_subnet.dev_1b.subnet_id, ]

  config {
    version          = "3.3"
    brokers_count    = 1
    zones            = ["ru-central1-b"]
    assign_public_ip = false
    unmanaged_topics = true     # Important
    schema_registry  = false
    kafka {
      resources {
        resource_preset_id = "b3-c1-m4"
        disk_type_id       = "network-ssd"
        disk_size          = 60
      }
      kafka_config {
        auto_create_topics_enable = true     # Important
        message_max_bytes         = "50000000"     # Important
      }
    }
  }
}

resource "yandex_mdb_kafka_user" "user_events" {
  cluster_id = yandex_mdb_kafka_cluster.sentry_kafka_dev.id
  name       = user
  password   = "password"
  permission {
    role       = "ACCESS_ROLE_ADMIN"     # Important
    topic_name = "*"     # Important
  }
}
```
