### ISSUE TITLE
not possible to run clickhouse without root

### ISSUE THREAD

**Issue by zetaab** [sentry-kubernetes/charts#902]
I am trying following

```
clickhouse:
  enabled: true
  clickhouse:
    podSecurityContext:
      fsGroup: 101
    securityContext:
      runAsUser: 101
      runAsNonRoot: true
      allowPrivilegeEscalation: false
```

This does not work with clickhouse.

Namespace is forced with baseline policy with label `pod-security.kubernetes.io/enforce: baseline`. (or enforce restricted)

The error message is

```
% kubectl logs sentry-clickhouse-1 -c init
mkdir: can't create directory '/etc/clickhouse-server/': Permission denied
```

Any tips how to get this running without root?
