### ISSUE TITLE
Sentry clickhouse instance not use settings from configmap

### ISSUE THREAD

**Issue by cloud-digitaltag** [sentry-kubernetes/charts#905]
Hi. 
Another issue or maybe I'm wrong.
I added to clickhouse definition in values files  option to change keep_alive_timeout:
```
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "20.12.8.5"
    configmap:
      enabled: true
      keep_alive_timeout: "120"
```
On k8s I see in configmap new values. When I login to pod and check config in directory `/etc/clickhouse-server` in config.xml file there is still default value, but in dir `/etc/clickhouse-server/config.d` in config.xml value have changed.

When I look at the procesess running on pod, clickhouse run from default config.xml file:

Listing from ls and ps command:
```
# ls -l /etc/clickhouse-server
total 48
drwxrwxrwx 3 root       root          77 Jun 12 05:41 config.d
-r-------- 1 clickhouse clickhouse 38573 Mar  1  2021 config.xml
drwxrwxrwx 3 root       root          79 Jun 12 05:41 metrica.d
drwxrwxrwx 3 root       root          77 Jun 12 05:41 users.d
-r-------- 1 clickhouse clickhouse  5587 Mar  1  2021 users.xml

# ls -l /etc/clickhouse-server/config.d
total 0
drwxrwxrwx 3 root       root       77 Jun 12 05:41 .
drwx------ 1 clickhouse clickhouse 23 Jun 12 05:41 ..
drwxr-xr-x 2 root       root       24 Jun 12 05:41 ..2023_06_12_05_41_57.261580944
lrwxrwxrwx 1 root       root       17 Jun 12 05:41 config.xml -> ..data/config.xml
lrwxrwxrwx 1 root       root       31 Jun 12 05:41 ..data -> ..2023_06_12_05_41_57.261580944


# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
clickho+     1  2.2  1.0 7656816 169188 ?      Ssl  05:41   4:05 /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
root       127  0.0  0.0   2620  1668 pts/0    Ss+  06:08   0:00 sh
root       164  0.0  0.0   2620  1640 pts/1    Ss   08:42   0:00 sh
root       174  0.0  0.0   8904  3424 pts/1    R+   08:43   0:00 ps aux
```

This is proper behavior or something is wrong with config ?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by cloud-digitaltag** [comment]
Could someone check this ? Is this issue I only have ?

**Comment by Mokto** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by ohjongsung** [comment]
@cloud-digitaltag hi, it's worked!
```yaml
clickhouse:
  enabled: true
  clickhouse:
    imageVersion: "21.8.13.6"
    configmap:
      keep_alive_timeout: 120
```
