### ISSUE TITLE
Failed to upgrade to 19.2.0 from 17.7.1 no ConfigMap with the name "sentry-rabbitmq-config" found

### ISSUE THREAD

**Issue by visla-xugeng** [sentry-kubernetes/charts#908]
I also tried to upgrade the sentry from 17.7.1 to 19.2.0 to try to bypass the Kafka issue and got error below. 

```

│ Error: an error occurred while rolling back the release. original upgrade error: cannot patch "sentry-kafka" with kind StatefulSet: StatefulSet.apps "sentry-kafka" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden: no ConfigMap with the name "sentry-rabbitmq-config" found
```

In the new values.yaml, I just updated kafka volume nothing else. 
```
kafka:
  # TODO: increase the numPartitions of the "event" topic to the number of projects
  persistence:
    enabled: true
    storageClass: ebs-sc
    size: 20Gi
```

Any thoughts will be appreciated.
