### ISSUE TITLE
Adding some documentation on how to scale this chart

### ISSUE THREAD

**Issue by pulse00** [sentry-kubernetes/charts#974]
It would be great to gather some collective advice on how people scale this chart and/or usage examples: How many events are people processing with this chart per hour/month/etc?

We've had a couple of bursts during event ingestion, which lead to outages of some pods, which we could recover from and tweaked the resources a bit afterwards.

But it's all very much guessworks, maybe we can crowd-source some performance/usage information in this repo?

**Comment by stevenyongzion** [comment]
@pulse00 Good idea, are you able to share what pods went down and what resources did you adjust to make it work again?

We have a new one running now for 2 months and really not sure what will cause it to come down later.

**Comment by pulse00** [comment]
> @pulse00 Good idea, are you able to share what pods went down and what resources did you adjust to make it work again?

Sure. We started out with a setup *without* rabbitmq, so redis was the celery backend. During the 2 outages we encountered, from what we could see the main bottleneck was redis memory. We started out with a rather small memory limit for redis, and under heavy load redis was being killed by k8s due to high memory usage.

This then cascaded all the way back to kafka and consumers being out of sync (see here https://develop.sentry.dev/self-hosted/troubleshooting/#kafka).

Redis pods where ending up in a Crashloop in k8s, and it was pretty hard to find out what was causing it at first, because redis was not logging much. Redis loads its data from disk during startup. If the data is larger then the kubernetes resource limit, it will end up in a crashloop. 

Solution was to increase the memory limits of redis.

I'll post our current settings of the resources i think are the most critical and the throughput we see with it in our setup.

## Resource limits and event volume

|  Statefulset  | Memory limits | Memory requests | replicas |
| -------- | ------- | ------- | ------- |
| redis  | 6Gi   | 4Gi  |  1  |  
| kafka  | 2Gi   | 1Gi  |  3  |  
| clickhouse  | 2Gi   | 512Mi  |  1  |  
| postgresql  | none   | 256Mi  |  1  |  
| zookeeper-clickhouse  | 1Gi   | 512Mi  |  1  |  

|  Deployment  | Memory limits | Memory requests | replicas |
| -------- | ------- | ------- | ------- |
| worker  | 1Gi   | 512Mi  |  6  |  
| web  | 1Gi   | 512Mi  |  2  |  
| relay  | 2Gi   | 1Gi  |  2  |  

With this, we are working with a volume of ~ 500k errors and 3 Million transactions per 14 days. 

The UI is still a bit slow, but it's acceptable and it never crashes. 

We are currently upgrading to the latest version of the chart and will be switching to rabbitmq as celery backend. 

## Disk usage

With a retention of 14 days, we have currently the following disk usage for the most important workloads:

| Resource | Current Disk Usage |
| -------- | ------- |
| postgres | 50 Gb |
| clickhouse | 40 Gb |

Everything else is below 10 Gb.


## Other notable problems

### Startup problems 

When installing the chart with the above limits, we are nearly always running in helm timeouts, because `hooks.activeDeadlineSeconds` is by default set to something which is exceeded, which by itself is not a problem. 

Adjusting that to `800` works for us.

### Timeout of cleanup jobs

It is highly important that the cleanup cronjobs run without problems, otherwise disk space of postgres will fill up fairly quickly.

The default cron expression is set to once a day, which will make the jobs run pretty long, so they will run in the `activeDeadlineSeconds` timeout.

Here's settings that work better for us:

`sentry.cleanup.schedule`: `0 * * * *`
`sentry.cleanup.activeDeadlineSeconds`: `3600`

**Comment by elliotdobson** [comment]
We've run into similar issues with redis OOMKills previously when load on our instance spikes higher than usual. If you catch it quick enough you can increase the redis memory limit and recover easily. In some cases we've had to increase the redis memory limit up to 6-8Gi to cope with a sudden load spike.

We're running quite an old version of the Helm chart, v13.0.1. We are in the process of upgrading to the latest version currently. (However after testing the upgrade in staging we found that snuba clickhouse migrations do not apply cleanly and each clickhouse node can end up in differing states with migrations skipped, in-progress or successful. So we are deploying new instances and cutting over our applications.)

We are ingesting 500k errors and 18 million transactions per 14 days. Here is the `values.yaml` file we use with v13.0.1:

```
clickhouse:
  clickhouse:
    persistentVolumeClaim:
      dataPersistentVolume:
        storage: 150Gi
    resources:
      limits:
        cpu: "1"
        memory: 6Gi
      requests:
        cpu: "0.3"
        memory: 6Gi
hooks:
  activeDeadlineSeconds: 300
kafka:
  persistence:
    size: 16Gi
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: "0.1"
      memory: 2Gi
  zookeeper:
    resources:
      limits:
        memory: 768Mi
      requests:
        cpu: "0.025"
        memory: 512Mi
nginx:
  enabled: false
postgresql:
  enabled: false
rabbitmq:
  enabled: false
redis:
  master:
    extraFlags:
    - "--maxmemory 1536mb"
    persistence:
      size: 16Gi
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "0.1"
        memory: 2Gi
  replica:
    extraFlags:
    - "--maxmemory 1536mb"
    persistence:
      size: 16Gi
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "0.1"
        memory: 2Gi
relay:
  replicas: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "0.05"
      memory: 512Mi
sentry:
  cleanup:
    days: 21
  cron:
    resources:
      limits:
        memory: 192Mi
      requests:
        cpu: "0.025"
        memory: 128Mi
  ingestConsumer:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: "0.1"
        memory: 256Mi
  postProcessForward:
    commitBatchSize: 100
    resources:
      limits:
        memory: 384Mi
      requests:
        cpu: "0.1"
        memory: 256Mi
  subscriptionConsumerEvents:
    resources:
      limits:
        memory: 192Mi
      requests:
        cpu: "0.025"
        memory: 128Mi
  subscriptionConsumerTransactions:
    resources:
      limits:
        memory: 192Mi
      requests:
        cpu: "0.025"
        memory: 128Mi
  web:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: "0.025"
        memory: 512Mi
  worker:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "0.25"
        memory: 1Gi
snuba:
  api:
    resources:
      limits:
        memory: 192Mi
      requests:
        cpu: "0.025"
        memory: 96Mi
  consumer:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  outcomesConsumer:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  replacer:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  sessionsConsumer:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  subscriptionConsumerEvents:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  subscriptionConsumerTransactions:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
  transactionsConsumer:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: "0.025"
        memory: 64Mi
```

We're using a t3.small AWS RDS instance for our external postgresql database, with Sentry using around 180GB disk.

We've also seen the same issue with hooks timing out, so have bumped `hooks.activeDeadlineSeconds` to `300` which works for us.
