### ISSUE TITLE
Error: No such option: --max-batch-size [ingest conusmer] 

### ISSUE THREAD

**Issue by ohjongsung** [sentry-kubernetes/charts#993]
--max-batch-size option not working.
version : 20.4.0

```yaml
  ingestConsumer:
    replicas: 1
    # concurrency: 4
    env: []
    resources: {}
    affinity: {}
    nodeSelector: {sentry: sentry}
    securityContext: {}
    containerSecurityContext: {}
    # tolerations: []
    # podLabels: []
    maxBatchSize: "1000"
```
<img width="338" alt="image" src="https://github.com/sentry-kubernetes/charts/assets/17442438/7ac775dc-d9a7-408b-b8e5-b0c02d78d6d4">

<img width="663" alt="image" src="https://github.com/sentry-kubernetes/charts/assets/17442438/4dd1b8c6-5839-47ab-90f8-d82054e5b940">
